import { inputParamsSchema } from "./schema/root.js"
import type { OpenMCPServerTool } from "@open-mcp/core"

const tool: OpenMCPServerTool = {
  "toolName": "dcim_front_port_templates_list",
  "toolDescription": "Get a list of front port template objects.",
  "baseUrl": "https://api.example.com",
  "path": "/api/dcim/front-port-templates/",
  "method": "get",
  "security": [
    {
      "key": "sessionid",
      "value": "<mcp-env-var>SESSIONID</mcp-env-var>",
      "in": "cookie",
      "envVarName": "SESSIONID"
    },
    {
      "key": "Authorization",
      "value": "<mcp-env-var>AUTHORIZATION</mcp-env-var>",
      "in": "header",
      "envVarName": "AUTHORIZATION"
    }
  ],
  "paramsMap": {
    "query": {
      "color": "color",
      "color__empty": "color__empty",
      "color__ic": "color__ic",
      "color__ie": "color__ie",
      "color__iew": "color__iew",
      "color__isw": "color__isw",
      "color__n": "color__n",
      "color__nic": "color__nic",
      "color__nie": "color__nie",
      "color__niew": "color__niew",
      "color__nisw": "color__nisw",
      "created": "created",
      "created__empty": "created__empty",
      "created__gt": "created__gt",
      "created__gte": "created__gte",
      "created__lt": "created__lt",
      "created__lte": "created__lte",
      "created__n": "created__n",
      "created_by_request": "created_by_request",
      "description": "description",
      "description__empty": "description__empty",
      "description__ic": "description__ic",
      "description__ie": "description__ie",
      "description__iew": "description__iew",
      "description__isw": "description__isw",
      "description__n": "description__n",
      "description__nic": "description__nic",
      "description__nie": "description__nie",
      "description__niew": "description__niew",
      "description__nisw": "description__nisw",
      "device_type_id": "device_type_id",
      "device_type_id__n": "device_type_id__n",
      "id": "id",
      "id__empty": "id__empty",
      "id__gt": "id__gt",
      "id__gte": "id__gte",
      "id__lt": "id__lt",
      "id__lte": "id__lte",
      "id__n": "id__n",
      "label": "label",
      "label__empty": "label__empty",
      "label__ic": "label__ic",
      "label__ie": "label__ie",
      "label__iew": "label__iew",
      "label__isw": "label__isw",
      "label__n": "label__n",
      "label__nic": "label__nic",
      "label__nie": "label__nie",
      "label__niew": "label__niew",
      "label__nisw": "label__nisw",
      "last_updated": "last_updated",
      "last_updated__empty": "last_updated__empty",
      "last_updated__gt": "last_updated__gt",
      "last_updated__gte": "last_updated__gte",
      "last_updated__lt": "last_updated__lt",
      "last_updated__lte": "last_updated__lte",
      "last_updated__n": "last_updated__n",
      "limit": "limit",
      "modified_by_request": "modified_by_request",
      "module_type_id": "module_type_id",
      "module_type_id__n": "module_type_id__n",
      "name": "name",
      "name__empty": "name__empty",
      "name__ic": "name__ic",
      "name__ie": "name__ie",
      "name__iew": "name__iew",
      "name__isw": "name__isw",
      "name__n": "name__n",
      "name__nic": "name__nic",
      "name__nie": "name__nie",
      "name__niew": "name__niew",
      "name__nisw": "name__nisw",
      "offset": "offset",
      "ordering": "ordering",
      "q": "q",
      "rear_port_id": "rear_port_id",
      "rear_port_id__n": "rear_port_id__n",
      "rear_port_position": "rear_port_position",
      "rear_port_position__empty": "rear_port_position__empty",
      "rear_port_position__gt": "rear_port_position__gt",
      "rear_port_position__gte": "rear_port_position__gte",
      "rear_port_position__lt": "rear_port_position__lt",
      "rear_port_position__lte": "rear_port_position__lte",
      "rear_port_position__n": "rear_port_position__n",
      "type": "type",
      "type__empty": "type__empty",
      "type__ic": "type__ic",
      "type__ie": "type__ie",
      "type__iew": "type__iew",
      "type__isw": "type__isw",
      "type__n": "type__n",
      "type__nic": "type__nic",
      "type__nie": "type__nie",
      "type__niew": "type__niew",
      "type__nisw": "type__nisw",
      "updated_by_request": "updated_by_request"
    }
  },
  inputParamsSchema
}

export default tool