import { z } from "zod"

export const inputParamsSchema = {
  "language": z.string(),
  "id": z.number().optional(),
  "asset": z.enum(["0","1"]).optional(),
  "date_from": z.string().optional(),
  "date_to": z.string().optional(),
  "organization_id": z.number().optional(),
  "document": z.string().optional(),
  "debet_name": z.string().optional(),
  "credit_name": z.string().optional(),
  "debet_number": z.string().optional(),
  "credit_number": z.string().optional(),
  "object_id": z.number().optional(),
  "unit_id": z.number().optional(),
  "unit_from": z.number().optional(),
  "unit_to": z.number().optional(),
  "amount": z.number().optional(),
  "amount_from": z.number().optional(),
  "amount_to": z.number().optional(),
  "currency": z.number().optional(),
  "description": z.string().optional(),
  "quantity": z.number().optional(),
  "quantity_from": z.number().optional(),
  "quantity_to": z.number().optional(),
  "course_from": z.number().optional(),
  "course_to": z.number().optional(),
  "operation_type": z.number().optional(),
  "transaction_type": z.number().optional(),
  "page_size": z.number().optional(),
  "page": z.number().optional(),
  "operation_id": z.number().optional(),
  "waybillId": z.number().optional(),
  "waybill_number": z.string().optional(),
  "parent_id": z.number().optional(),
  "is_active": z.boolean().optional(),
  "vat": z.boolean().optional(),
  "account_id": z.number().optional(),
  "connectable_account_id": z.number().optional(),
  "with_start_transactions": z.boolean().optional(),
  "card_account_id": z.number().optional(),
  "account_ids": z.array(z.number()).optional(),
  "connectable_account_ids": z.array(z.number()).optional()
}