import { z } from "zod"

export const inputParamsSchema = {
  "children": z.array(z.number().int()).optional(),
  "children__empty": z.array(z.number().int()).optional(),
  "children__gt": z.array(z.number().int()).optional(),
  "children__gte": z.array(z.number().int()).optional(),
  "children__lt": z.array(z.number().int()).optional(),
  "children__lte": z.array(z.number().int()).optional(),
  "children__n": z.array(z.number().int()).optional(),
  "contact": z.array(z.number().int()).describe("Contact").optional(),
  "contact__n": z.array(z.number().int()).describe("Contact").optional(),
  "contact_group": z.array(z.string()).optional(),
  "contact_group__n": z.array(z.string()).optional(),
  "contact_role": z.array(z.number().int()).describe("Contact Role").optional(),
  "contact_role__n": z.array(z.number().int()).describe("Contact Role").optional(),
  "contains": z.string().describe("Prefixes which contain this prefix or IP").optional(),
  "created": z.array(z.string().datetime({ offset: true })).optional(),
  "created__empty": z.array(z.string().datetime({ offset: true })).optional(),
  "created__gt": z.array(z.string().datetime({ offset: true })).optional(),
  "created__gte": z.array(z.string().datetime({ offset: true })).optional(),
  "created__lt": z.array(z.string().datetime({ offset: true })).optional(),
  "created__lte": z.array(z.string().datetime({ offset: true })).optional(),
  "created__n": z.array(z.string().datetime({ offset: true })).optional(),
  "created_by_request": z.string().uuid().optional(),
  "depth": z.array(z.number().int()).optional(),
  "depth__empty": z.array(z.number().int()).optional(),
  "depth__gt": z.array(z.number().int()).optional(),
  "depth__gte": z.array(z.number().int()).optional(),
  "depth__lt": z.array(z.number().int()).optional(),
  "depth__lte": z.array(z.number().int()).optional(),
  "depth__n": z.array(z.number().int()).optional(),
  "description": z.array(z.string()).optional(),
  "description__empty": z.boolean().optional(),
  "description__ic": z.array(z.string()).optional(),
  "description__ie": z.array(z.string()).optional(),
  "description__iew": z.array(z.string()).optional(),
  "description__isw": z.array(z.string()).optional(),
  "description__n": z.array(z.string()).optional(),
  "description__nic": z.array(z.string()).optional(),
  "description__nie": z.array(z.string()).optional(),
  "description__niew": z.array(z.string()).optional(),
  "description__nisw": z.array(z.string()).optional(),
  "family": z.number().optional(),
  "id": z.array(z.number().int()).optional(),
  "id__empty": z.boolean().optional(),
  "id__gt": z.array(z.number().int()).optional(),
  "id__gte": z.array(z.number().int()).optional(),
  "id__lt": z.array(z.number().int()).optional(),
  "id__lte": z.array(z.number().int()).optional(),
  "id__n": z.array(z.number().int()).optional(),
  "is_pool": z.boolean().optional(),
  "last_updated": z.array(z.string().datetime({ offset: true })).optional(),
  "last_updated__empty": z.array(z.string().datetime({ offset: true })).optional(),
  "last_updated__gt": z.array(z.string().datetime({ offset: true })).optional(),
  "last_updated__gte": z.array(z.string().datetime({ offset: true })).optional(),
  "last_updated__lt": z.array(z.string().datetime({ offset: true })).optional(),
  "last_updated__lte": z.array(z.string().datetime({ offset: true })).optional(),
  "last_updated__n": z.array(z.string().datetime({ offset: true })).optional(),
  "limit": z.number().int().describe("Number of results to return per page.").optional(),
  "location": z.array(z.string()).optional(),
  "location__n": z.array(z.string()).optional(),
  "location_id": z.array(z.string()).optional(),
  "location_id__n": z.array(z.string()).optional(),
  "mark_utilized": z.boolean().optional(),
  "mask_length": z.array(z.number().int()).optional(),
  "mask_length__gte": z.number().optional(),
  "mask_length__lte": z.number().optional(),
  "modified_by_request": z.string().uuid().optional(),
  "offset": z.number().int().describe("The initial index from which to return the results.").optional(),
  "ordering": z.string().describe("Which field to use when ordering the results.").optional(),
  "prefix": z.array(z.string()).optional(),
  "present_in_vrf": z.string().optional(),
  "present_in_vrf_id": z.string().optional(),
  "q": z.string().describe("Search").optional(),
  "region": z.array(z.string()).optional(),
  "region__n": z.array(z.string()).optional(),
  "region_id": z.array(z.string()).optional(),
  "region_id__n": z.array(z.string()).optional(),
  "role": z.array(z.string()).describe("Role (slug)").optional(),
  "role__n": z.array(z.string()).describe("Role (slug)").optional(),
  "role_id": z.array(z.number().int().nullable()).describe("Role (ID)").optional(),
  "role_id__n": z.array(z.number().int().nullable()).describe("Role (ID)").optional(),
  "scope_id": z.array(z.number().int()).optional(),
  "scope_id__empty": z.boolean().optional(),
  "scope_id__gt": z.array(z.number().int()).optional(),
  "scope_id__gte": z.array(z.number().int()).optional(),
  "scope_id__lt": z.array(z.number().int()).optional(),
  "scope_id__lte": z.array(z.number().int()).optional(),
  "scope_id__n": z.array(z.number().int()).optional(),
  "scope_type": z.string().optional(),
  "scope_type__n": z.string().optional(),
  "site": z.array(z.string()).describe("Site (slug)").optional(),
  "site__n": z.array(z.string()).describe("Site (slug)").optional(),
  "site_group": z.array(z.string()).optional(),
  "site_group__n": z.array(z.string()).optional(),
  "site_group_id": z.array(z.string()).optional(),
  "site_group_id__n": z.array(z.string()).optional(),
  "site_id": z.array(z.number().int()).describe("Site (ID)").optional(),
  "site_id__n": z.array(z.number().int()).describe("Site (ID)").optional(),
  "status": z.array(z.string()).describe("Operational status of this prefix").optional(),
  "status__empty": z.boolean().optional(),
  "status__ic": z.array(z.string()).describe("Operational status of this prefix").optional(),
  "status__ie": z.array(z.string()).describe("Operational status of this prefix").optional(),
  "status__iew": z.array(z.string()).describe("Operational status of this prefix").optional(),
  "status__isw": z.array(z.string()).describe("Operational status of this prefix").optional(),
  "status__n": z.array(z.string()).describe("Operational status of this prefix").optional(),
  "status__nic": z.array(z.string()).describe("Operational status of this prefix").optional(),
  "status__nie": z.array(z.string()).describe("Operational status of this prefix").optional(),
  "status__niew": z.array(z.string()).describe("Operational status of this prefix").optional(),
  "status__nisw": z.array(z.string()).describe("Operational status of this prefix").optional(),
  "tag": z.array(z.string()).optional(),
  "tag__n": z.array(z.string()).optional(),
  "tag_id": z.array(z.number().int()).optional(),
  "tag_id__n": z.array(z.number().int()).optional(),
  "tenant": z.array(z.string()).describe("Tenant (slug)").optional(),
  "tenant__n": z.array(z.string()).describe("Tenant (slug)").optional(),
  "tenant_group": z.array(z.string()).optional(),
  "tenant_group__n": z.array(z.string()).optional(),
  "tenant_group_id": z.array(z.string()).optional(),
  "tenant_group_id__n": z.array(z.string()).optional(),
  "tenant_id": z.array(z.number().int().nullable()).describe("Tenant (ID)").optional(),
  "tenant_id__n": z.array(z.number().int().nullable()).describe("Tenant (ID)").optional(),
  "updated_by_request": z.string().uuid().optional(),
  "vlan_group": z.array(z.string()).describe("VLAN Group (slug)").optional(),
  "vlan_group__n": z.array(z.string()).describe("VLAN Group (slug)").optional(),
  "vlan_group_id": z.array(z.number().int()).describe("VLAN Group (ID)").optional(),
  "vlan_group_id__n": z.array(z.number().int()).describe("VLAN Group (ID)").optional(),
  "vlan_id": z.array(z.number().int().nullable()).describe("VLAN (ID)").optional(),
  "vlan_id__n": z.array(z.number().int().nullable()).describe("VLAN (ID)").optional(),
  "vlan_vid": z.number().int().describe("VLAN number (1-4094)").optional(),
  "vlan_vid__empty": z.number().int().describe("VLAN number (1-4094)").optional(),
  "vlan_vid__gt": z.number().int().describe("VLAN number (1-4094)").optional(),
  "vlan_vid__gte": z.number().int().describe("VLAN number (1-4094)").optional(),
  "vlan_vid__lt": z.number().int().describe("VLAN number (1-4094)").optional(),
  "vlan_vid__lte": z.number().int().describe("VLAN number (1-4094)").optional(),
  "vlan_vid__n": z.number().int().describe("VLAN number (1-4094)").optional(),
  "vrf": z.array(z.string().nullable()).describe("VRF (RD)").optional(),
  "vrf__n": z.array(z.string().nullable()).describe("VRF (RD)").optional(),
  "vrf_id": z.array(z.number().int().nullable()).describe("VRF").optional(),
  "vrf_id__n": z.array(z.number().int().nullable()).describe("VRF").optional(),
  "within": z.string().describe("Within prefix").optional(),
  "within_include": z.string().describe("Within and including prefix").optional()
}