import { inputParamsSchema } from "./schema/root.js"
import type { OpenMCPServerTool } from "@open-mcp/core"

const tool: OpenMCPServerTool = {
  "toolName": "extras_event_rules_list",
  "toolDescription": "Get a list of event rule objects.",
  "baseUrl": "https://api.example.com",
  "path": "/api/extras/event-rules/",
  "method": "get",
  "security": [
    {
      "key": "sessionid",
      "value": "<mcp-env-var>SESSIONID</mcp-env-var>",
      "in": "cookie",
      "envVarName": "SESSIONID"
    },
    {
      "key": "Authorization",
      "value": "<mcp-env-var>AUTHORIZATION</mcp-env-var>",
      "in": "header",
      "envVarName": "AUTHORIZATION"
    }
  ],
  "paramsMap": {
    "query": {
      "action_object_id": "action_object_id",
      "action_object_id__empty": "action_object_id__empty",
      "action_object_id__gt": "action_object_id__gt",
      "action_object_id__gte": "action_object_id__gte",
      "action_object_id__lt": "action_object_id__lt",
      "action_object_id__lte": "action_object_id__lte",
      "action_object_id__n": "action_object_id__n",
      "action_object_type": "action_object_type",
      "action_object_type__n": "action_object_type__n",
      "action_type": "action_type",
      "action_type__empty": "action_type__empty",
      "action_type__ic": "action_type__ic",
      "action_type__ie": "action_type__ie",
      "action_type__iew": "action_type__iew",
      "action_type__isw": "action_type__isw",
      "action_type__n": "action_type__n",
      "action_type__nic": "action_type__nic",
      "action_type__nie": "action_type__nie",
      "action_type__niew": "action_type__niew",
      "action_type__nisw": "action_type__nisw",
      "created": "created",
      "created__empty": "created__empty",
      "created__gt": "created__gt",
      "created__gte": "created__gte",
      "created__lt": "created__lt",
      "created__lte": "created__lte",
      "created__n": "created__n",
      "created_by_request": "created_by_request",
      "description": "description",
      "description__empty": "description__empty",
      "description__ic": "description__ic",
      "description__ie": "description__ie",
      "description__iew": "description__iew",
      "description__isw": "description__isw",
      "description__n": "description__n",
      "description__nic": "description__nic",
      "description__nie": "description__nie",
      "description__niew": "description__niew",
      "description__nisw": "description__nisw",
      "enabled": "enabled",
      "event_type": "event_type",
      "id": "id",
      "id__empty": "id__empty",
      "id__gt": "id__gt",
      "id__gte": "id__gte",
      "id__lt": "id__lt",
      "id__lte": "id__lte",
      "id__n": "id__n",
      "last_updated": "last_updated",
      "last_updated__empty": "last_updated__empty",
      "last_updated__gt": "last_updated__gt",
      "last_updated__gte": "last_updated__gte",
      "last_updated__lt": "last_updated__lt",
      "last_updated__lte": "last_updated__lte",
      "last_updated__n": "last_updated__n",
      "limit": "limit",
      "modified_by_request": "modified_by_request",
      "name": "name",
      "name__empty": "name__empty",
      "name__ic": "name__ic",
      "name__ie": "name__ie",
      "name__iew": "name__iew",
      "name__isw": "name__isw",
      "name__n": "name__n",
      "name__nic": "name__nic",
      "name__nie": "name__nie",
      "name__niew": "name__niew",
      "name__nisw": "name__nisw",
      "object_type": "object_type",
      "object_type__ic": "object_type__ic",
      "object_type__ie": "object_type__ie",
      "object_type__iew": "object_type__iew",
      "object_type__isw": "object_type__isw",
      "object_type__n": "object_type__n",
      "object_type__nic": "object_type__nic",
      "object_type__nie": "object_type__nie",
      "object_type__niew": "object_type__niew",
      "object_type__nisw": "object_type__nisw",
      "object_type_id": "object_type_id",
      "object_type_id__n": "object_type_id__n",
      "offset": "offset",
      "ordering": "ordering",
      "q": "q",
      "tag": "tag",
      "tag__n": "tag__n",
      "tag_id": "tag_id",
      "tag_id__n": "tag_id__n",
      "updated_by_request": "updated_by_request"
    }
  },
  inputParamsSchema
}

export default tool