import { z } from "zod"

export const inputParams = {
  "agent_id": z.string().describe("服务商的支付宝账号ID（2088开头的16位纯数字，<a href=\"https://opendocs.alipay.com/common/02ncut\">获取方式</a>），由服务商提供给ISV").optional(),
  "business_isv": z.array(z.object({ "business_appid": z.string().describe("业务归属appid").optional(), "business_payee_id": z.string().describe("业务收款pid，business_type为AGREEMENT_PAY时，此参数必传").optional(), "business_pid": z.string().describe("业务归属pid").optional(), "business_type": z.string().describe("业务类型ONLINE_PAY(在线缴费) 、AGREEMENT_PAY(无感停车)\tDEVICE_ONLINE_PAY(车机在线缴费)").optional() })).describe("车场业务归属列表").optional(),
  "charging_rule": z.array(z.object({ "charging_period": z.string().describe("停车收费时间段，输入24小时制的小时时间段格式: \t开始时间-结束时间,\t结束时间必须大于开始时间\t时间取值范围：0到24").optional(), "charging_strategy": z.string().describe("计费策略；\tUP：向上取整\tDOMN：向下取整").optional(), "charging_unit_fee": z.string().describe("跳费金额 单位元").optional(), "charging_unit_minutes": z.string().describe("跳费间隔分钟数").optional(), "enable_rollover_charge_period": z.boolean().describe("超时是否顺延到下个计费区间").optional(), "first_charging_span_minutes": z.string().describe("首段计费周期分钟数").optional(), "first_charging_unit_fee": z.string().describe("首段计费周期跳费金额 单位: 元").optional(), "first_charging_unit_minutes": z.string().describe("首段计费周期跳费间隔 单位分钟").optional(), "free_enter_minutes": z.string().describe("入场免费时间 单位:分钟").optional(), "free_exit_minutes": z.string().describe("离场免费时间 单位:分钟").optional(), "max_fee_per_day": z.string().describe("日封顶金额 单位: 元").optional() })).describe("停车场详细计费规则").optional(),
  "city_id": z.string().describe("该参数废弃").optional(),
  "contact_alipay": z.string().describe("该参数废弃").optional(),
  "contact_emali": z.string().describe("该参数废弃").optional(),
  "contact_mobile": z.string().describe("该参数废弃").optional(),
  "contact_name": z.string().describe("该参数废弃").optional(),
  "contact_tel": z.string().describe("该参数废弃").optional(),
  "contact_weixin": z.string().describe("该参数废弃").optional(),
  "equipment_name": z.string().describe("该参数废弃").optional(),
  "is_support_invoice": z.string().describe("是否支持电子发票。枚举支持：\t0：表示不支持。\t1：表示支持。").optional(),
  "isv_mobile": z.string().describe("ISV电话，传入original_isv_pid、original_isv_appid时，此处为服务商电话").optional(),
  "latitude": z.string().describe("纬度 单位:度").optional(),
  "longitude": z.string().describe("经度 单位:度").optional(),
  "mchnt_id": z.string().describe("收款方的支付宝账号ID（2088开头的16位纯数字，<a href=\"https://opendocs.alipay.com/common/02ncut\">获取方式</a>），由停车场收款的业主方提供给ISV，该字段暂用于机具和物料申领").optional(),
  "original_isv_appid": z.string().describe("ISV的APPID,服务商调用必传，由ISV提供给服务商").optional(),
  "original_isv_mobile": z.string().describe("ISV电话，此值与isv_mobile组合使用").optional(),
  "original_isv_name": z.string().describe("ISV的名称，服务商调用必传，由ISV提供给服务商").optional(),
  "original_isv_pid": z.string().describe("ISV的PID，服务商调用必传,由ISV提供给服务商").optional(),
  "out_parking_id": z.string().describe("ISV停车场ID，由ISV 自定义，同一个isv或商户范围内唯一").optional(),
  "parking_address": z.string().describe("停车场地址").optional(),
  "parking_end_time": z.string().describe("该参数废弃").optional(),
  "parking_fee_description": z.string().describe("收费说明").optional(),
  "parking_fee_description_img": z.string().describe("商户在停车平台露出的停车价格图片；注意：该图片为PNG格式内容为BASE64的字符串，大小不要超过1MB").optional(),
  "parking_lot_type": z.string().describe("停车场类型，1为居民小区、2为商圈停车场（购物中心商业广场商场等）、3为路侧停车、4为公园景点（景点乐园公园老街古镇等）、5为商务楼宇（酒店写字楼商务楼园区等）、6为其他、7为交通枢纽（机场火车站汽车站码头港口等）、8为市政设施（体育场博物图书馆医院学校等）").optional(),
  "parking_mobile": z.string().describe("停车场客服电话").optional(),
  "parking_name": z.string().describe("停车场名称，由ISV定义，尽量与高德地图上的一致。").optional(),
  "parking_number": z.string().describe("该参数废弃").optional(),
  "parking_poiid": z.string().describe("如何获取parking_poiid（高德地图唯一标标识）参考文档 <a href=\"https://opendocs.alipay.com/support/01rghx\">https://opendocs.alipay.com/support/01rghx</a> ；若无法成功获取高德POI时，也可选用经纬度的方式注册。").optional(),
  "parking_start_time": z.string().describe("该参数废弃").optional(),
  "parking_type": z.string().describe("该参数废弃").optional(),
  "pay_type": z.string().describe("支付方式。枚举支持：\t1：表示支付宝在线缴费。\t2：表示支付宝代扣缴费。\t3：表示当面付。\t4:  现金\t说明：如支持多种方式以 ',' 进行分隔。").optional(),
  "payment_mode": z.string().describe("该参数废弃").optional(),
  "serivce_url": z.string().describe("提供用户查看停车状态、缴费功能").optional(),
  "service_list": z.array(z.object({ "service_name": z.string().describe("在线缴费服务名称").optional(), "service_type": z.string().describe("停车场可提供的服务类型\t发票服务：INVOICE_SERVICE\t优惠套餐: DISCOUNT_PACKAGE\t预约停车: RESERVED_PARKING").optional(), "service_url": z.string().describe("商户提供服务对应的跳转链接").optional() })).describe("停车场服务信息列表").optional(),
  "shopingmall_id": z.string().describe("商圈id").optional(),
  "sum_space": z.string().describe("停车场车位数 单位:个").optional(),
  "support_after_pay": z.string().describe("是否支持先离后付。枚举支持：\tY：支持。\tN：不支持。\t说明：默认为空不支持，此参数适用于签约信用代扣的商户。").optional(),
  "time_out": z.string().describe("用户支付未离场的超时时间(以分钟为单位)").optional()
}