import { z } from "zod"

export const inputParamsSchema = {
  "homeMobileCountryCode": z.number().int().describe("The cell tower's Mobile Country Code (MCC).").optional(),
  "homeMobileNetworkCode": z.number().int().describe("The cell tower's Mobile Network Code. This is the MNC for GSM and WCDMA; CDMA uses the System ID (SID).").optional(),
  "radioType": z.string().describe("The mobile radio type. Supported values are lte, gsm, cdma, and wcdma. While this field is optional, it should be included if a value is available, for more accurate results.").optional(),
  "carrier": z.string().describe("The carrier name.").optional(),
  "considerIp": z.string().describe("Specifies whether to fall back to IP geolocation if wifi and cell tower signals are not available. Defaults to true. Set considerIp to false to disable fall back.").optional(),
  "cellTowers": z.array(z.object({ "cellId": z.number().int().describe("Unique identifier of the cell. On GSM, this is the Cell ID (CID); CDMA networks use the Base Station ID (BID). WCDMA networks use the UTRAN/GERAN Cell Identity (UC-Id), which is a 32-bit value concatenating the Radio Network Controller (RNC) and Cell ID. Specifying only the 16-bit Cell ID value in WCDMA networks may return inaccurate results."), "locationAreaCode": z.number().int().describe("The Location Area Code (LAC) for GSM and WCDMA networks. The Network ID (NID) for CDMA networks."), "mobileCountryCode": z.number().int().describe("The cell tower's Mobile Country Code (MCC)."), "mobileNetworkCode": z.number().int().describe("The cell tower's Mobile Network Code. This is the MNC for GSM and WCDMA; CDMA uses the System ID (SID)."), "age": z.number().int().describe("The number of milliseconds since this cell was primary. If age is 0, the cellId represents a current measurement.").optional(), "signalStrength": z.number().describe("Radio signal strength measured in dBm.").optional(), "timingAdvance": z.number().describe("The timing advance value.").optional() }).describe("Attributes used to describe a cell tower. The following optional fields are not currently used, but may be included if values are available: `age`, `signalStrength`, `timingAdvance`.")).describe("The request body's cellTowers array contains zero or more cell tower objects.").optional(),
  "wifiAccessPoints": z.array(z.object({ "macAddress": z.string().describe("The MAC address of the WiFi node. It's typically called a BSS, BSSID or MAC address. Separators must be `:` (colon)."), "signalStrength": z.number().int().describe("The current signal strength measured in dBm.").optional(), "signalToNoiseRatio": z.number().int().describe("The current signal to noise ratio measured in dB.").optional(), "age": z.number().int().describe("The number of milliseconds since this access point was detected.").optional(), "channel": z.number().int().describe("The channel over which the client is communication with the access point.").optional() }).describe("Attributes used to describe a WiFi access point.")).describe("An array of two or more WiFi access point objects.").optional()
}