import { inputParamsSchema } from "./schema/root.js"
import type { OpenMCPServerTool } from "@open-mcp/core"

const tool: OpenMCPServerTool = {
  "toolName": "dcim_mac_addresses_list",
  "toolDescription": "Get a list of MAC address objects.",
  "baseUrl": "https://api.example.com",
  "path": "/api/dcim/mac-addresses/",
  "method": "get",
  "security": [
    {
      "key": "sessionid",
      "value": "<mcp-env-var>SESSIONID</mcp-env-var>",
      "in": "cookie",
      "envVarName": "SESSIONID"
    },
    {
      "key": "Authorization",
      "value": "<mcp-env-var>AUTHORIZATION</mcp-env-var>",
      "in": "header",
      "envVarName": "AUTHORIZATION"
    }
  ],
  "paramsMap": {
    "query": {
      "assigned_object_id": "assigned_object_id",
      "assigned_object_id__empty": "assigned_object_id__empty",
      "assigned_object_id__gt": "assigned_object_id__gt",
      "assigned_object_id__gte": "assigned_object_id__gte",
      "assigned_object_id__lt": "assigned_object_id__lt",
      "assigned_object_id__lte": "assigned_object_id__lte",
      "assigned_object_id__n": "assigned_object_id__n",
      "assigned_object_type": "assigned_object_type",
      "assigned_object_type__n": "assigned_object_type__n",
      "created": "created",
      "created__empty": "created__empty",
      "created__gt": "created__gt",
      "created__gte": "created__gte",
      "created__lt": "created__lt",
      "created__lte": "created__lte",
      "created__n": "created__n",
      "created_by_request": "created_by_request",
      "description": "description",
      "description__empty": "description__empty",
      "description__ic": "description__ic",
      "description__ie": "description__ie",
      "description__iew": "description__iew",
      "description__isw": "description__isw",
      "description__n": "description__n",
      "description__nic": "description__nic",
      "description__nie": "description__nie",
      "description__niew": "description__niew",
      "description__nisw": "description__nisw",
      "device": "device",
      "device_id": "device_id",
      "id": "id",
      "id__empty": "id__empty",
      "id__gt": "id__gt",
      "id__gte": "id__gte",
      "id__lt": "id__lt",
      "id__lte": "id__lte",
      "id__n": "id__n",
      "interface": "interface",
      "interface__n": "interface__n",
      "interface_id": "interface_id",
      "interface_id__n": "interface_id__n",
      "last_updated": "last_updated",
      "last_updated__empty": "last_updated__empty",
      "last_updated__gt": "last_updated__gt",
      "last_updated__gte": "last_updated__gte",
      "last_updated__lt": "last_updated__lt",
      "last_updated__lte": "last_updated__lte",
      "last_updated__n": "last_updated__n",
      "limit": "limit",
      "mac_address": "mac_address",
      "mac_address__ic": "mac_address__ic",
      "mac_address__ie": "mac_address__ie",
      "mac_address__iew": "mac_address__iew",
      "mac_address__isw": "mac_address__isw",
      "mac_address__n": "mac_address__n",
      "mac_address__nic": "mac_address__nic",
      "mac_address__nie": "mac_address__nie",
      "mac_address__niew": "mac_address__niew",
      "mac_address__nisw": "mac_address__nisw",
      "modified_by_request": "modified_by_request",
      "offset": "offset",
      "ordering": "ordering",
      "q": "q",
      "tag": "tag",
      "tag__n": "tag__n",
      "tag_id": "tag_id",
      "tag_id__n": "tag_id__n",
      "updated_by_request": "updated_by_request",
      "virtual_machine": "virtual_machine",
      "virtual_machine_id": "virtual_machine_id",
      "vminterface": "vminterface",
      "vminterface__n": "vminterface__n",
      "vminterface_id": "vminterface_id",
      "vminterface_id__n": "vminterface_id__n"
    }
  },
  inputParamsSchema
}

export default tool