import { inputParamsSchema } from "./schema/root.js"
import type { OpenMCPServerTool } from "@open-mcp/core"

const tool: OpenMCPServerTool = {
  "toolName": "extras_config_templates_list",
  "toolDescription": "Get a list of config template objects.",
  "baseUrl": "https://api.example.com",
  "path": "/api/extras/config-templates/",
  "method": "get",
  "security": [
    {
      "key": "sessionid",
      "value": "<mcp-env-var>SESSIONID</mcp-env-var>",
      "in": "cookie",
      "envVarName": "SESSIONID"
    },
    {
      "key": "Authorization",
      "value": "<mcp-env-var>AUTHORIZATION</mcp-env-var>",
      "in": "header",
      "envVarName": "AUTHORIZATION"
    }
  ],
  "paramsMap": {
    "query": {
      "as_attachment": "as_attachment",
      "auto_sync_enabled": "auto_sync_enabled",
      "created": "created",
      "created__empty": "created__empty",
      "created__gt": "created__gt",
      "created__gte": "created__gte",
      "created__lt": "created__lt",
      "created__lte": "created__lte",
      "created__n": "created__n",
      "created_by_request": "created_by_request",
      "data_file_id": "data_file_id",
      "data_file_id__n": "data_file_id__n",
      "data_source_id": "data_source_id",
      "data_source_id__n": "data_source_id__n",
      "data_synced": "data_synced",
      "data_synced__empty": "data_synced__empty",
      "data_synced__gt": "data_synced__gt",
      "data_synced__gte": "data_synced__gte",
      "data_synced__lt": "data_synced__lt",
      "data_synced__lte": "data_synced__lte",
      "data_synced__n": "data_synced__n",
      "description": "description",
      "description__empty": "description__empty",
      "description__ic": "description__ic",
      "description__ie": "description__ie",
      "description__iew": "description__iew",
      "description__isw": "description__isw",
      "description__n": "description__n",
      "description__nic": "description__nic",
      "description__nie": "description__nie",
      "description__niew": "description__niew",
      "description__nisw": "description__nisw",
      "file_extension": "file_extension",
      "file_extension__empty": "file_extension__empty",
      "file_extension__ic": "file_extension__ic",
      "file_extension__ie": "file_extension__ie",
      "file_extension__iew": "file_extension__iew",
      "file_extension__isw": "file_extension__isw",
      "file_extension__n": "file_extension__n",
      "file_extension__nic": "file_extension__nic",
      "file_extension__nie": "file_extension__nie",
      "file_extension__niew": "file_extension__niew",
      "file_extension__nisw": "file_extension__nisw",
      "file_name": "file_name",
      "file_name__empty": "file_name__empty",
      "file_name__ic": "file_name__ic",
      "file_name__ie": "file_name__ie",
      "file_name__iew": "file_name__iew",
      "file_name__isw": "file_name__isw",
      "file_name__n": "file_name__n",
      "file_name__nic": "file_name__nic",
      "file_name__nie": "file_name__nie",
      "file_name__niew": "file_name__niew",
      "file_name__nisw": "file_name__nisw",
      "id": "id",
      "id__empty": "id__empty",
      "id__gt": "id__gt",
      "id__gte": "id__gte",
      "id__lt": "id__lt",
      "id__lte": "id__lte",
      "id__n": "id__n",
      "last_updated": "last_updated",
      "last_updated__empty": "last_updated__empty",
      "last_updated__gt": "last_updated__gt",
      "last_updated__gte": "last_updated__gte",
      "last_updated__lt": "last_updated__lt",
      "last_updated__lte": "last_updated__lte",
      "last_updated__n": "last_updated__n",
      "limit": "limit",
      "mime_type": "mime_type",
      "mime_type__empty": "mime_type__empty",
      "mime_type__ic": "mime_type__ic",
      "mime_type__ie": "mime_type__ie",
      "mime_type__iew": "mime_type__iew",
      "mime_type__isw": "mime_type__isw",
      "mime_type__n": "mime_type__n",
      "mime_type__nic": "mime_type__nic",
      "mime_type__nie": "mime_type__nie",
      "mime_type__niew": "mime_type__niew",
      "mime_type__nisw": "mime_type__nisw",
      "modified_by_request": "modified_by_request",
      "name": "name",
      "name__empty": "name__empty",
      "name__ic": "name__ic",
      "name__ie": "name__ie",
      "name__iew": "name__iew",
      "name__isw": "name__isw",
      "name__n": "name__n",
      "name__nic": "name__nic",
      "name__nie": "name__nie",
      "name__niew": "name__niew",
      "name__nisw": "name__nisw",
      "offset": "offset",
      "ordering": "ordering",
      "q": "q",
      "tag": "tag",
      "tag__n": "tag__n",
      "tag_id": "tag_id",
      "tag_id__n": "tag_id__n",
      "updated_by_request": "updated_by_request"
    }
  },
  inputParamsSchema
}

export default tool