import { z } from "zod"

export const inputParamsSchema = {
  "businessId": z.string(),
  "query": z.string().optional(),
  "type": z.string().optional(),
  "ticket_type": z.string().optional(),
  "stakeholder": z.string().optional(),
  "status": z.string().optional(),
  "status_out": z.string().optional(),
  "uploaded_start_date": z.string().datetime({ offset: true }).optional(),
  "uploaded_end_date": z.string().datetime({ offset: true }).optional(),
  "start_date": z.string().datetime({ offset: true }).optional(),
  "end_date": z.string().datetime({ offset: true }).optional(),
  "start_registration_date": z.string().datetime({ offset: true }).optional(),
  "end_registration_date": z.string().datetime({ offset: true }).optional(),
  "order_column": z.number().int(),
  "order_dir": z.string().optional(),
  "amount_min": z.number().optional(),
  "amount_max": z.number().optional(),
  "invoice_recurrence": z.number().int().optional(),
  "invoice_status": z.string().optional(),
  "invoice_type": z.string().optional(),
  "expense_accounts": z.string().optional(),
  "line_activities": z.string().optional(),
  "taxes": z.string().optional(),
  "irpf": z.number().int().optional(),
  "tax_regime": z.string().optional(),
  "payment_status": z.string().optional(),
  "payment_status_out": z.string().optional(),
  "serie": z.string().optional(),
  "serie_out": z.string().optional(),
  "product": z.string().optional(),
  "tag": z.string().optional(),
  "size": z.number().int().optional(),
  "offset": z.number().int().optional(),
  "app_type_platform": z.string().optional(),
  "review_tickets_not_processed": z.boolean().optional(),
  "select_all": z.number().int().optional(),
  "ids": z.string().optional()
}