import { z } from "zod"

export const inputParamsSchema = {
  "startDateTime": z.string().datetime({ offset: true }).max(256).describe("Timestamp in ISO 8601 format that indicates the start of the data retrieval range. You can retrieve data for response tasks that were created no later than 180 days ago.\n\nIf no value is specified, 'startDateTime' defaults to the start of the beginning of the retention period of 180 days.\n").optional(),
  "endDateTime": z.string().datetime({ offset: true }).max(256).describe("Timestamp in ISO 8601 format that indicates the end of the data retrieval range.\n\nIf no value is specified, 'endDateTime' defaults to the time the request is made.\n").optional(),
  "dateTimeTarget": z.enum(["loggedDateTime","ingestedDateTime"]).describe("The timestamp to be used for retrieving the target audit log. \n\nAvailable values : loggedDateTime, ingestedDateTime \n\nDefault value : loggedDateTime\n").optional(),
  "orderBy": z.string().max(256).describe("Parameter that allows you to sort the retrieved search results in ascending or descending order. If no order is specified, the results are shown in ascending order. Supported fields and operators:\n* 'loggedDateTime'\n* 'accessType'\n* 'ingestedDateTime'\n* asc - Ascending order\n* desc - Descending order\n").optional(),
  "top": z.union([z.literal(50), z.literal(100), z.literal(200)]).describe("Number of records displayed on a page.").optional(),
  "labels": z.enum(["none","matched","all"]).describe("Parameter that allows you to retrieve the specified elements from the \"details\" field. Possible values:\n* 'none' - Retrieves no elements.\n* 'matched' - Retrieves the specified elements in the \"details\" object.\n* 'all\" - Retrieves all available elements.\n").optional(),
  "Accept": z.enum(["application/json","text/csv"]).optional(),
  "TMV1-Filter": z.string().max(1024).describe("Filter for retrieving a subset of the Audit Logs list. Supported fields and operators:\n\n* 'loggedUser '- The account that was used to perform the activity.\n* 'loggedRole' - Role of the account\n* 'accessType' - Source of the activity. Possible values: 'Console', 'API'.\n* 'category' - Category of the activity. Possible values: _See Response Code 200 description_.\n* 'activity' - The activity that was performed. The 'category' needs to be determined to set this parameter. Possible values: _See Response Code 200 description_.\n* 'result' - Outcome of the activity. Possible values: 'Successful', 'Unsuccessful'.\n* 'eq' - Abbreviation of the operator \"equal to\"\n* 'and' - Operator \"and\"\n* 'or' - Operator \"or\"\n* 'not' - Operator \"not\"\n* '( )' - Symbols for grouping operands with their correct operator.\n").optional()
}