import { inputParamsSchema } from "./schema/root.js"
import type { OpenMCPServerTool } from "@open-mcp/core"

const tool: OpenMCPServerTool = {
  "toolName": "tenancy_contacts_list",
  "toolDescription": "Get a list of contact objects.",
  "baseUrl": "https://api.example.com",
  "path": "/api/tenancy/contacts/",
  "method": "get",
  "security": [
    {
      "key": "sessionid",
      "value": "<mcp-env-var>SESSIONID</mcp-env-var>",
      "in": "cookie",
      "envVarName": "SESSIONID"
    },
    {
      "key": "Authorization",
      "value": "<mcp-env-var>AUTHORIZATION</mcp-env-var>",
      "in": "header",
      "envVarName": "AUTHORIZATION"
    }
  ],
  "paramsMap": {
    "query": {
      "address": "address",
      "address__empty": "address__empty",
      "address__ic": "address__ic",
      "address__ie": "address__ie",
      "address__iew": "address__iew",
      "address__isw": "address__isw",
      "address__n": "address__n",
      "address__nic": "address__nic",
      "address__nie": "address__nie",
      "address__niew": "address__niew",
      "address__nisw": "address__nisw",
      "created": "created",
      "created__empty": "created__empty",
      "created__gt": "created__gt",
      "created__gte": "created__gte",
      "created__lt": "created__lt",
      "created__lte": "created__lte",
      "created__n": "created__n",
      "created_by_request": "created_by_request",
      "description": "description",
      "description__empty": "description__empty",
      "description__ic": "description__ic",
      "description__ie": "description__ie",
      "description__iew": "description__iew",
      "description__isw": "description__isw",
      "description__n": "description__n",
      "description__nic": "description__nic",
      "description__nie": "description__nie",
      "description__niew": "description__niew",
      "description__nisw": "description__nisw",
      "email": "email",
      "email__empty": "email__empty",
      "email__ic": "email__ic",
      "email__ie": "email__ie",
      "email__iew": "email__iew",
      "email__isw": "email__isw",
      "email__n": "email__n",
      "email__nic": "email__nic",
      "email__nie": "email__nie",
      "email__niew": "email__niew",
      "email__nisw": "email__nisw",
      "group": "group",
      "group__n": "group__n",
      "group_id": "group_id",
      "group_id__n": "group_id__n",
      "id": "id",
      "id__empty": "id__empty",
      "id__gt": "id__gt",
      "id__gte": "id__gte",
      "id__lt": "id__lt",
      "id__lte": "id__lte",
      "id__n": "id__n",
      "last_updated": "last_updated",
      "last_updated__empty": "last_updated__empty",
      "last_updated__gt": "last_updated__gt",
      "last_updated__gte": "last_updated__gte",
      "last_updated__lt": "last_updated__lt",
      "last_updated__lte": "last_updated__lte",
      "last_updated__n": "last_updated__n",
      "limit": "limit",
      "link": "link",
      "link__empty": "link__empty",
      "link__ic": "link__ic",
      "link__ie": "link__ie",
      "link__iew": "link__iew",
      "link__isw": "link__isw",
      "link__n": "link__n",
      "link__nic": "link__nic",
      "link__nie": "link__nie",
      "link__niew": "link__niew",
      "link__nisw": "link__nisw",
      "modified_by_request": "modified_by_request",
      "name": "name",
      "name__empty": "name__empty",
      "name__ic": "name__ic",
      "name__ie": "name__ie",
      "name__iew": "name__iew",
      "name__isw": "name__isw",
      "name__n": "name__n",
      "name__nic": "name__nic",
      "name__nie": "name__nie",
      "name__niew": "name__niew",
      "name__nisw": "name__nisw",
      "offset": "offset",
      "ordering": "ordering",
      "phone": "phone",
      "phone__empty": "phone__empty",
      "phone__ic": "phone__ic",
      "phone__ie": "phone__ie",
      "phone__iew": "phone__iew",
      "phone__isw": "phone__isw",
      "phone__n": "phone__n",
      "phone__nic": "phone__nic",
      "phone__nie": "phone__nie",
      "phone__niew": "phone__niew",
      "phone__nisw": "phone__nisw",
      "q": "q",
      "tag": "tag",
      "tag__n": "tag__n",
      "tag_id": "tag_id",
      "tag_id__n": "tag_id__n",
      "title": "title",
      "title__empty": "title__empty",
      "title__ic": "title__ic",
      "title__ie": "title__ie",
      "title__iew": "title__iew",
      "title__isw": "title__isw",
      "title__n": "title__n",
      "title__nic": "title__nic",
      "title__nie": "title__nie",
      "title__niew": "title__niew",
      "title__nisw": "title__nisw",
      "updated_by_request": "updated_by_request"
    }
  },
  inputParamsSchema
}

export default tool