import { z } from "zod"

export const inputParamsSchema = {
  "assignedTo": z.array(z.string()).max(2).optional(),
  "assignedToTeam": z.boolean().optional(),
  "title": z.string().min(0).max(15).nullable().optional(),
  "name": z.string().min(0).max(255).nullable().optional(),
  "surname": z.string().min(0).max(255).nullable().optional(),
  "company": z.string().min(0).max(255).nullable().optional(),
  "address": z.string().min(0).max(2000).nullable().optional(),
  "notes": z.string().min(0).max(25000).nullable().optional(),
  "identcard": z.string().min(0).max(50).nullable().optional(),
  "email": z.string().email().min(0).max(255).nullable().optional(),
  "mobile": z.string().min(0).max(50).nullable().describe("A phone number in full international format includes a plus sign (+)").optional(),
  "telephone": z.string().min(0).max(50).nullable().describe("A phone number in full international format includes a plus sign (+)").optional(),
  "fax": z.string().nullable().optional(),
  "web": z.string().min(0).max(255).nullable().optional(),
  "language": z.string().nullable().describe("ISO 639-1 Code, https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes").optional(),
  "country": z.string().nullable().describe("ISO 3166-1 alpha-2 Code, https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#Officially_assigned_code_elements").optional(),
  "archived": z.boolean().optional(),
  "typeBuyer": z.boolean().optional(),
  "typeCollaborator": z.boolean().optional(),
  "typeDeveloper": z.boolean().optional(),
  "typeLawyer": z.boolean().optional(),
  "typeOwner": z.boolean().optional(),
  "typeServiceco": z.boolean().optional(),
  "typeTenantLong": z.boolean().optional(),
  "typeTenantShort": z.boolean().optional(),
  "sentBy": z.number().int().nullable().describe("Contact ID collaborator").optional(),
  "sentTo": z.number().int().nullable().describe("Contact ID collaborator").optional(),
  "lawyer": z.number().int().nullable().describe("Contact ID lawyer").optional(),
  "source": z.string().nullable().optional(),
  "sourceDetails": z.string().nullable().optional(),
  "leadStatus": z.string().nullable().optional(),
  "saleStage": z.enum(["CLOSED","CLOSING","DISQUALIFIED","LEAD_CAPTURING","LISTINGMATCHING","OFFERING","VIEWINGS"]).nullable().optional(),
  "tags": z.array(z.string()).optional(),
  "allowAutoEmailDealAlert": z.boolean().optional(),
  "allowAutoEmailMarketing": z.boolean().optional()
}