import { z } from "zod"

export const inputParamsSchema = {
  "asn": z.array(z.number().int().gte(1).lte(4294967295)).describe("AS (ID)").optional(),
  "asn__n": z.array(z.number().int().gte(1).lte(4294967295)).describe("AS (ID)").optional(),
  "asn_id": z.array(z.number().int()).describe("AS (ID)").optional(),
  "asn_id__n": z.array(z.number().int()).describe("AS (ID)").optional(),
  "contact": z.array(z.number().int()).describe("Contact").optional(),
  "contact__n": z.array(z.number().int()).describe("Contact").optional(),
  "contact_group": z.array(z.string()).optional(),
  "contact_group__n": z.array(z.string()).optional(),
  "contact_role": z.array(z.number().int()).describe("Contact Role").optional(),
  "contact_role__n": z.array(z.number().int()).describe("Contact Role").optional(),
  "created": z.array(z.string().datetime({ offset: true })).optional(),
  "created__empty": z.array(z.string().datetime({ offset: true })).optional(),
  "created__gt": z.array(z.string().datetime({ offset: true })).optional(),
  "created__gte": z.array(z.string().datetime({ offset: true })).optional(),
  "created__lt": z.array(z.string().datetime({ offset: true })).optional(),
  "created__lte": z.array(z.string().datetime({ offset: true })).optional(),
  "created__n": z.array(z.string().datetime({ offset: true })).optional(),
  "created_by_request": z.string().uuid().optional(),
  "description": z.array(z.string()).optional(),
  "description__empty": z.boolean().optional(),
  "description__ic": z.array(z.string()).optional(),
  "description__ie": z.array(z.string()).optional(),
  "description__iew": z.array(z.string()).optional(),
  "description__isw": z.array(z.string()).optional(),
  "description__n": z.array(z.string()).optional(),
  "description__nic": z.array(z.string()).optional(),
  "description__nie": z.array(z.string()).optional(),
  "description__niew": z.array(z.string()).optional(),
  "description__nisw": z.array(z.string()).optional(),
  "facility": z.array(z.string()).optional(),
  "facility__empty": z.boolean().optional(),
  "facility__ic": z.array(z.string()).optional(),
  "facility__ie": z.array(z.string()).optional(),
  "facility__iew": z.array(z.string()).optional(),
  "facility__isw": z.array(z.string()).optional(),
  "facility__n": z.array(z.string()).optional(),
  "facility__nic": z.array(z.string()).optional(),
  "facility__nie": z.array(z.string()).optional(),
  "facility__niew": z.array(z.string()).optional(),
  "facility__nisw": z.array(z.string()).optional(),
  "group": z.array(z.string()).optional(),
  "group__n": z.array(z.string()).optional(),
  "group_id": z.array(z.string()).optional(),
  "group_id__n": z.array(z.string()).optional(),
  "id": z.array(z.number().int()).optional(),
  "id__empty": z.boolean().optional(),
  "id__gt": z.array(z.number().int()).optional(),
  "id__gte": z.array(z.number().int()).optional(),
  "id__lt": z.array(z.number().int()).optional(),
  "id__lte": z.array(z.number().int()).optional(),
  "id__n": z.array(z.number().int()).optional(),
  "last_updated": z.array(z.string().datetime({ offset: true })).optional(),
  "last_updated__empty": z.array(z.string().datetime({ offset: true })).optional(),
  "last_updated__gt": z.array(z.string().datetime({ offset: true })).optional(),
  "last_updated__gte": z.array(z.string().datetime({ offset: true })).optional(),
  "last_updated__lt": z.array(z.string().datetime({ offset: true })).optional(),
  "last_updated__lte": z.array(z.string().datetime({ offset: true })).optional(),
  "last_updated__n": z.array(z.string().datetime({ offset: true })).optional(),
  "latitude": z.array(z.number()).optional(),
  "latitude__empty": z.boolean().optional(),
  "latitude__gt": z.array(z.number()).optional(),
  "latitude__gte": z.array(z.number()).optional(),
  "latitude__lt": z.array(z.number()).optional(),
  "latitude__lte": z.array(z.number()).optional(),
  "latitude__n": z.array(z.number()).optional(),
  "limit": z.number().int().describe("Number of results to return per page.").optional(),
  "longitude": z.array(z.number()).optional(),
  "longitude__empty": z.boolean().optional(),
  "longitude__gt": z.array(z.number()).optional(),
  "longitude__gte": z.array(z.number()).optional(),
  "longitude__lt": z.array(z.number()).optional(),
  "longitude__lte": z.array(z.number()).optional(),
  "longitude__n": z.array(z.number()).optional(),
  "modified_by_request": z.string().uuid().optional(),
  "name": z.array(z.string()).optional(),
  "name__empty": z.boolean().optional(),
  "name__ic": z.array(z.string()).optional(),
  "name__ie": z.array(z.string()).optional(),
  "name__iew": z.array(z.string()).optional(),
  "name__isw": z.array(z.string()).optional(),
  "name__n": z.array(z.string()).optional(),
  "name__nic": z.array(z.string()).optional(),
  "name__nie": z.array(z.string()).optional(),
  "name__niew": z.array(z.string()).optional(),
  "name__nisw": z.array(z.string()).optional(),
  "offset": z.number().int().describe("The initial index from which to return the results.").optional(),
  "ordering": z.string().describe("Which field to use when ordering the results.").optional(),
  "q": z.string().describe("Search").optional(),
  "region": z.array(z.string()).optional(),
  "region__n": z.array(z.string()).optional(),
  "region_id": z.array(z.string()).optional(),
  "region_id__n": z.array(z.string()).optional(),
  "slug": z.array(z.string()).optional(),
  "slug__empty": z.boolean().optional(),
  "slug__ic": z.array(z.string()).optional(),
  "slug__ie": z.array(z.string()).optional(),
  "slug__iew": z.array(z.string()).optional(),
  "slug__isw": z.array(z.string()).optional(),
  "slug__n": z.array(z.string()).optional(),
  "slug__nic": z.array(z.string()).optional(),
  "slug__nie": z.array(z.string()).optional(),
  "slug__niew": z.array(z.string()).optional(),
  "slug__nisw": z.array(z.string()).optional(),
  "status": z.array(z.string()).optional(),
  "status__empty": z.boolean().optional(),
  "status__ic": z.array(z.string()).optional(),
  "status__ie": z.array(z.string()).optional(),
  "status__iew": z.array(z.string()).optional(),
  "status__isw": z.array(z.string()).optional(),
  "status__n": z.array(z.string()).optional(),
  "status__nic": z.array(z.string()).optional(),
  "status__nie": z.array(z.string()).optional(),
  "status__niew": z.array(z.string()).optional(),
  "status__nisw": z.array(z.string()).optional(),
  "tag": z.array(z.string()).optional(),
  "tag__n": z.array(z.string()).optional(),
  "tag_id": z.array(z.number().int()).optional(),
  "tag_id__n": z.array(z.number().int()).optional(),
  "tenant": z.array(z.string()).describe("Tenant (slug)").optional(),
  "tenant__n": z.array(z.string()).describe("Tenant (slug)").optional(),
  "tenant_group": z.array(z.string()).optional(),
  "tenant_group__n": z.array(z.string()).optional(),
  "tenant_group_id": z.array(z.string()).optional(),
  "tenant_group_id__n": z.array(z.string()).optional(),
  "tenant_id": z.array(z.number().int().nullable()).describe("Tenant (ID)").optional(),
  "tenant_id__n": z.array(z.number().int().nullable()).describe("Tenant (ID)").optional(),
  "time_zone": z.array(z.string()).optional(),
  "time_zone__ic": z.array(z.string()).optional(),
  "time_zone__ie": z.array(z.string()).optional(),
  "time_zone__iew": z.array(z.string()).optional(),
  "time_zone__isw": z.array(z.string()).optional(),
  "time_zone__n": z.array(z.string()).optional(),
  "time_zone__nic": z.array(z.string()).optional(),
  "time_zone__nie": z.array(z.string()).optional(),
  "time_zone__niew": z.array(z.string()).optional(),
  "time_zone__nisw": z.array(z.string()).optional(),
  "updated_by_request": z.string().uuid().optional()
}