import { z } from "zod"

export const inputParamsSchema = {
  "part": z.array(z.string()).describe("The *part* parameter specifies a comma-separated list of one or more search resource properties that the API response will include. Set the parameter value to snippet."),
  "channelId": z.string().describe("Filter on resources belonging to this channelId.").optional(),
  "channelType": z.enum(["channelTypeUnspecified","any","show"]).describe("Add a filter on the channel search.").optional(),
  "eventType": z.enum(["none","upcoming","live","completed"]).describe("Filter on the livestream status of the videos.").optional(),
  "forContentOwner": z.boolean().describe("Search owned by a content owner.").optional(),
  "forDeveloper": z.boolean().describe("Restrict the search to only retrieve videos uploaded using the project id of the authenticated user.").optional(),
  "forMine": z.boolean().describe("Search for the private videos of the authenticated user.").optional(),
  "location": z.string().describe("Filter on location of the video").optional(),
  "locationRadius": z.string().describe("Filter on distance from the location (specified above).").optional(),
  "maxResults": z.number().int().gte(0).lte(50).describe("The *maxResults* parameter specifies the maximum number of items that should be returned in the result set.").optional(),
  "onBehalfOfContentOwner": z.string().describe("*Note:* This parameter is intended exclusively for YouTube content partners. The *onBehalfOfContentOwner* parameter indicates that the request's authorization credentials identify a YouTube CMS user who is acting on behalf of the content owner specified in the parameter value. This parameter is intended for YouTube content partners that own and manage many different YouTube channels. It allows content owners to authenticate once and get access to all their video and channel data, without having to provide authentication credentials for each individual channel. The CMS account that the user authenticates with must be linked to the specified YouTube content owner.").optional(),
  "order": z.enum(["searchSortUnspecified","date","rating","viewCount","relevance","title","videoCount"]).describe("Sort order of the results.").optional(),
  "pageToken": z.string().describe("The *pageToken* parameter identifies a specific page in the result set that should be returned. In an API response, the nextPageToken and prevPageToken properties identify other pages that could be retrieved.").optional(),
  "publishedAfter": z.string().describe("Filter on resources published after this date.").optional(),
  "publishedBefore": z.string().describe("Filter on resources published before this date.").optional(),
  "q": z.string().describe("Textual search terms to match.").optional(),
  "regionCode": z.string().describe("Display the content as seen by viewers in this country.").optional(),
  "relevanceLanguage": z.string().describe("Return results relevant to this language.").optional(),
  "safeSearch": z.enum(["safeSearchSettingUnspecified","none","moderate","strict"]).describe("Indicates whether the search results should include restricted content as well as standard content.").optional(),
  "topicId": z.string().describe("Restrict results to a particular topic.").optional(),
  "type": z.array(z.string()).describe("Restrict results to a particular set of resource types from One Platform.").optional(),
  "videoCaption": z.enum(["videoCaptionUnspecified","any","closedCaption","none"]).describe("Filter on the presence of captions on the videos.").optional(),
  "videoCategoryId": z.string().describe("Filter on videos in a specific category.").optional(),
  "videoDefinition": z.enum(["any","standard","high"]).describe("Filter on the definition of the videos.").optional(),
  "videoDimension": z.enum(["any","2d","3d"]).describe("Filter on 3d videos.").optional(),
  "videoDuration": z.enum(["videoDurationUnspecified","any","short","medium","long"]).describe("Filter on the duration of the videos.").optional(),
  "videoEmbeddable": z.enum(["videoEmbeddableUnspecified","any","true"]).describe("Filter on embeddable videos.").optional(),
  "videoLicense": z.enum(["any","youtube","creativeCommon"]).describe("Filter on the license of the videos.").optional(),
  "videoPaidProductPlacement": z.enum(["videoPaidProductPlacementUnspecified","any","true"]).optional(),
  "videoSyndicated": z.enum(["videoSyndicatedUnspecified","any","true"]).describe("Filter on syndicated videos.").optional(),
  "videoType": z.enum(["videoTypeUnspecified","any","movie","episode"]).describe("Filter on videos of a specific type.").optional()
}