import { z } from "zod"

export const inputParamsSchema = {
  "instanceId": z.string(),
  "projectId": z.string(),
  "emailConfigs": z.array(z.object({ "authIdentity": z.string().min(1).max(200).describe("SMTP authentication information.\n`Additional Validators:`\n* must be a syntactically valid email address").optional(), "authPassword": z.string().min(1).max(200).describe("SMTP authentication information.").optional(), "authUsername": z.string().min(1).max(200).describe("SMTP authentication information.").optional(), "from": z.string().min(1).max(200).describe("The sender address.\n`Additional Validators:`\n* must be a syntactically valid email address").optional(), "sendResolved": z.boolean().describe("Whether to notify about resolved alerts."), "smarthost": z.string().min(1).max(200).describe("The SMTP host through which emails are sent.\n`Additional Validators:`\n* should only include the characters: a-zA-Z0-9_./@&?:-").optional(), "to": z.string().min(1).max(200).describe("The email address to send notifications to.\n`Additional Validators:`\n* must be a syntactically valid email address").optional() })).describe("Email configurations").optional(),
  "name": z.string().min(1).max(200).describe("`Additional Validators:`\n* must be unique\n* should only include the characters: a-zA-Z0-9-"),
  "opsgenieConfigs": z.array(z.object({ "apiKey": z.string().min(1).max(200).describe("The API key to use when talking to the OpsGenie API.\n`Additional Validators:`\n* should only include the characters: a-zA-Z0-9-").optional(), "apiUrl": z.string().min(1).max(200).describe("The host to send OpsGenie API requests to.\n`Additional Validators:`\n* must be a syntactically valid url address").optional(), "priority": z.string().min(2).max(2).describe("Priority level of alert. Possible values are P1, P2, P3, P4, and P5.").optional(), "sendResolved": z.boolean().describe("Whether to notify about resolved alerts."), "tags": z.string().min(1).max(400).describe("Comma separated list of tags attached to the notifications.").optional() })).describe("Configuration for ops genie.").optional(),
  "webHookConfigs": z.array(z.object({ "msTeams": z.boolean().describe("Microsoft Teams webhooks require special handling. If you set this property to true, it is treated as such"), "sendResolved": z.boolean().describe("Whether to notify about resolved alerts."), "url": z.string().min(1).max(500).describe("The endpoint to send HTTP POST requests to.\n`Additional Validators:`\n* must be a syntactically valid url address").optional() })).optional(),
  "Authorization": z.string().describe("Accepts technical credentials and api gateway access.")
}