export const OPENAPI_URL = "https://sensors-docs.bgs.ac.uk/openapi.yml"
export const SERVER_NAME = "sensors_bgs_ac_uk_frost_server"
export const SERVER_VERSION = "0.0.1"
export const OPERATION_FILES_RELATIVE = [
  "./tools/get_v1_1_datastreams/index.js",
  "./tools/get_v1_1_datastreams_entityid_/index.js",
  "./tools/get_v1_1_datastreams_entityid_observations/index.js",
  "./tools/get_v1_1_datastreams_entityid_observedproperty/index.js",
  "./tools/get_v1_1_datastreams_entityid_observedproperty_datastreams/index.js",
  "./tools/get_v1_1_datastreams_entityid_sensor/index.js",
  "./tools/get_v1_1_datastreams_entityid_sensor_datastreams/index.js",
  "./tools/get_v1_1_datastreams_entityid_thing/index.js",
  "./tools/get_v1_1_datastreams_entityid_thing_datastreams/index.js",
  "./tools/get_v1_1_datastreams_entityid_thing_locations/index.js",
  "./tools/get_v1_1_featuresofinterest/index.js",
  "./tools/get_v1_1_featuresofinterest_entityid_/index.js",
  "./tools/get_v1_1_featuresofinterest_entityid_observations/index.js",
  "./tools/get_v1_1_locations/index.js",
  "./tools/get_v1_1_locations_entityid_/index.js",
  "./tools/get_v1_1_locations_entityid_things/index.js",
  "./tools/get_v1_1_observations/index.js",
  "./tools/get_v1_1_observations_entityid_/index.js",
  "./tools/get_v1_1_observations_entityid_datastream/index.js",
  "./tools/get_v1_1_observations_entityid_datastream_observations/index.js",
  "./tools/get_v1_1_observations_entityid_datastream_observedproperty/index.js",
  "./tools/get_v1_1_observations_entityid_datastream_observedproperty_datas/index.js",
  "./tools/get_v1_1_observations_entityid_datastream_sensor/index.js",
  "./tools/get_v1_1_observations_entityid_datastream_sensor_datastreams/index.js",
  "./tools/get_v1_1_observations_entityid_datastream_thing/index.js",
  "./tools/get_v1_1_observations_entityid_datastream_thing_datastreams/index.js",
  "./tools/get_v1_1_observations_entityid_datastream_thing_locations/index.js",
  "./tools/get_v1_1_observations_entityid_featureofinterest/index.js",
  "./tools/get_v1_1_observations_entityid_featureofinterest_observations/index.js",
  "./tools/get_v1_1_observedproperties/index.js",
  "./tools/get_v1_1_observedproperties_entityid_/index.js",
  "./tools/get_v1_1_observedproperties_entityid_datastreams/index.js",
  "./tools/get_v1_1_sensors/index.js",
  "./tools/get_v1_1_sensors_entityid_/index.js",
  "./tools/get_v1_1_sensors_entityid_datastreams/index.js",
  "./tools/get_v1_1_things/index.js",
  "./tools/get_v1_1_things_entityid_/index.js",
  "./tools/get_v1_1_things_entityid_datastreams/index.js",
  "./tools/get_v1_1_things_entityid_locations/index.js"
]