import { z } from "zod"

export const inputParamsSchema = {
  "assocAssignedCode": z.string().optional(),
  "commonAccessRef": z.string().optional(),
  "controllingAgency": z.enum(["AA","AB","AC","AD","AE","CC","CE","EC","ED","EE","EN","ER","EU","EX","IA","KE","LI","OD","RI","RT","UN"]).optional(),
  "release": z.enum(["EDIFACTRELEASE_1","EDIFACTRELEASE_2","EDIFACTRELEASE_902","EDIFACTRELEASE_911","EDIFACTRELEASE_912","EDIFACTRELEASE_921","EDIFACTRELEASE_932","EDIFACTRELEASE_93A","EDIFACTRELEASE_94A","EDIFACTRELEASE_94B","EDIFACTRELEASE_95A","EDIFACTRELEASE_95B","EDIFACTRELEASE_96A","EDIFACTRELEASE_96B","EDIFACTRELEASE_97A","EDIFACTRELEASE_97B","EDIFACTRELEASE_98A","EDIFACTRELEASE_98B","EDIFACTRELEASE_99A","EDIFACTRELEASE_99B","EDIFACTRELEASE_00A","EDIFACTRELEASE_00B","EDIFACTRELEASE_01A","EDIFACTRELEASE_01B","EDIFACTRELEASE_02A","EDIFACTRELEASE_02B","EDIFACTRELEASE_03A","EDIFACTRELEASE_03B","EDIFACTRELEASE_04A","EDIFACTRELEASE_04B","EDIFACTRELEASE_05A","EDIFACTRELEASE_05B","EDIFACTRELEASE_06A","EDIFACTRELEASE_06B","EDIFACTRELEASE_07A","EDIFACTRELEASE_07B","EDIFACTRELEASE_08A","EDIFACTRELEASE_08B","EDIFACTRELEASE_09A","EDIFACTRELEASE_09B"]).optional(),
  "version": z.enum(["EDIFACTVERSION_1","EDIFACTVERSION_2","EDIFACTVERSION_4","EDIFACTVERSION_88","EDIFACTVERSION_89","EDIFACTVERSION_90","EDIFACTVERSION_D","EDIFACTVERSION_S"]).optional()
}