export const OPENAPI_URL = "http://soulpet-ai.com/full_documentation.json"
export const SERVER_NAME = "localhost_1338_api"
export const SERVER_VERSION = "0.0.1"
export const OPERATION_FILES_RELATIVE = [
  "./tools/get_clientes/index.js",
  "./tools/post_clientes/index.js",
  "./tools/get_clientes_id_/index.js",
  "./tools/put_clientes_id_/index.js",
  "./tools/delete_clientes_id_/index.js",
  "./tools/get_establecimientos/index.js",
  "./tools/post_establecimientos/index.js",
  "./tools/get_establecimientos_id_/index.js",
  "./tools/put_establecimientos_id_/index.js",
  "./tools/delete_establecimientos_id_/index.js",
  "./tools/get_trasteros/index.js",
  "./tools/post_trasteros/index.js",
  "./tools/get_trasteros_id_/index.js",
  "./tools/put_trasteros_id_/index.js",
  "./tools/delete_trasteros_id_/index.js",
  "./tools/post_upload/index.js",
  "./tools/post_upload_id_id_/index.js",
  "./tools/get_upload_files/index.js",
  "./tools/get_upload_files_id_/index.js",
  "./tools/delete_upload_files_id_/index.js",
  "./tools/get_connect_provider_/index.js",
  "./tools/post_auth_local/index.js",
  "./tools/post_auth_local_register/index.js",
  "./tools/get_auth_provider_callback/index.js",
  "./tools/post_auth_forgot_password/index.js",
  "./tools/post_auth_reset_password/index.js",
  "./tools/post_auth_change_password/index.js",
  "./tools/get_auth_email_confirmation/index.js",
  "./tools/post_auth_send_email_confirmation/index.js",
  "./tools/get_users_permissions_permissions/index.js",
  "./tools/get_users_permissions_roles/index.js",
  "./tools/post_users_permissions_roles/index.js",
  "./tools/get_users_permissions_roles_id_/index.js",
  "./tools/put_users_permissions_roles_role_/index.js",
  "./tools/delete_users_permissions_roles_role_/index.js",
  "./tools/get_users/index.js",
  "./tools/post_users/index.js",
  "./tools/get_users_id_/index.js",
  "./tools/put_users_id_/index.js",
  "./tools/delete_users_id_/index.js",
  "./tools/get_users_me/index.js",
  "./tools/get_users_count/index.js"
]