import { inputParamsSchema } from "./schema/root.js"
import type { OpenMCPServerTool } from "@open-mcp/core"

const tool: OpenMCPServerTool = {
  "toolName": "extras_config_contexts_list",
  "toolDescription": "Get a list of config context objects.",
  "baseUrl": "https://api.example.com",
  "path": "/api/extras/config-contexts/",
  "method": "get",
  "security": [
    {
      "key": "sessionid",
      "value": "<mcp-env-var>SESSIONID</mcp-env-var>",
      "in": "cookie",
      "envVarName": "SESSIONID"
    },
    {
      "key": "Authorization",
      "value": "<mcp-env-var>AUTHORIZATION</mcp-env-var>",
      "in": "header",
      "envVarName": "AUTHORIZATION"
    }
  ],
  "paramsMap": {
    "query": {
      "auto_sync_enabled": "auto_sync_enabled",
      "cluster_group": "cluster_group",
      "cluster_group__n": "cluster_group__n",
      "cluster_group_id": "cluster_group_id",
      "cluster_group_id__n": "cluster_group_id__n",
      "cluster_id": "cluster_id",
      "cluster_id__n": "cluster_id__n",
      "cluster_type": "cluster_type",
      "cluster_type__n": "cluster_type__n",
      "cluster_type_id": "cluster_type_id",
      "cluster_type_id__n": "cluster_type_id__n",
      "created": "created",
      "created__empty": "created__empty",
      "created__gt": "created__gt",
      "created__gte": "created__gte",
      "created__lt": "created__lt",
      "created__lte": "created__lte",
      "created__n": "created__n",
      "created_by_request": "created_by_request",
      "data_file_id": "data_file_id",
      "data_file_id__n": "data_file_id__n",
      "data_source_id": "data_source_id",
      "data_source_id__n": "data_source_id__n",
      "data_synced": "data_synced",
      "data_synced__empty": "data_synced__empty",
      "data_synced__gt": "data_synced__gt",
      "data_synced__gte": "data_synced__gte",
      "data_synced__lt": "data_synced__lt",
      "data_synced__lte": "data_synced__lte",
      "data_synced__n": "data_synced__n",
      "description": "description",
      "description__empty": "description__empty",
      "description__ic": "description__ic",
      "description__ie": "description__ie",
      "description__iew": "description__iew",
      "description__isw": "description__isw",
      "description__n": "description__n",
      "description__nic": "description__nic",
      "description__nie": "description__nie",
      "description__niew": "description__niew",
      "description__nisw": "description__nisw",
      "device_role": "device_role",
      "device_role__n": "device_role__n",
      "device_role_id": "device_role_id",
      "device_role_id__n": "device_role_id__n",
      "device_type_id": "device_type_id",
      "device_type_id__n": "device_type_id__n",
      "id": "id",
      "id__empty": "id__empty",
      "id__gt": "id__gt",
      "id__gte": "id__gte",
      "id__lt": "id__lt",
      "id__lte": "id__lte",
      "id__n": "id__n",
      "is_active": "is_active",
      "last_updated": "last_updated",
      "last_updated__empty": "last_updated__empty",
      "last_updated__gt": "last_updated__gt",
      "last_updated__gte": "last_updated__gte",
      "last_updated__lt": "last_updated__lt",
      "last_updated__lte": "last_updated__lte",
      "last_updated__n": "last_updated__n",
      "limit": "limit",
      "location": "location",
      "location__n": "location__n",
      "location_id": "location_id",
      "location_id__n": "location_id__n",
      "modified_by_request": "modified_by_request",
      "name": "name",
      "name__empty": "name__empty",
      "name__ic": "name__ic",
      "name__ie": "name__ie",
      "name__iew": "name__iew",
      "name__isw": "name__isw",
      "name__n": "name__n",
      "name__nic": "name__nic",
      "name__nie": "name__nie",
      "name__niew": "name__niew",
      "name__nisw": "name__nisw",
      "offset": "offset",
      "ordering": "ordering",
      "platform": "platform",
      "platform__n": "platform__n",
      "platform_id": "platform_id",
      "platform_id__n": "platform_id__n",
      "q": "q",
      "region": "region",
      "region__n": "region__n",
      "region_id": "region_id",
      "region_id__n": "region_id__n",
      "site": "site",
      "site__n": "site__n",
      "site_group": "site_group",
      "site_group__n": "site_group__n",
      "site_group_id": "site_group_id",
      "site_group_id__n": "site_group_id__n",
      "site_id": "site_id",
      "site_id__n": "site_id__n",
      "tag": "tag",
      "tag__n": "tag__n",
      "tag_id": "tag_id",
      "tag_id__n": "tag_id__n",
      "tenant": "tenant",
      "tenant__n": "tenant__n",
      "tenant_group": "tenant_group",
      "tenant_group__n": "tenant_group__n",
      "tenant_group_id": "tenant_group_id",
      "tenant_group_id__n": "tenant_group_id__n",
      "tenant_id": "tenant_id",
      "tenant_id__n": "tenant_id__n",
      "updated_by_request": "updated_by_request",
      "weight": "weight",
      "weight__empty": "weight__empty",
      "weight__gt": "weight__gt",
      "weight__gte": "weight__gte",
      "weight__lt": "weight__lt",
      "weight__lte": "weight__lte",
      "weight__n": "weight__n"
    }
  },
  inputParamsSchema
}

export default tool