import { z } from "zod"

export const inputParamsSchema = {
  "cable": z.number().int().optional(),
  "cable__n": z.number().int().optional(),
  "cable_end": z.enum(["A","B"]).describe("* `A` - A\n* `B` - B").optional(),
  "created": z.array(z.string().datetime({ offset: true })).optional(),
  "created__empty": z.array(z.string().datetime({ offset: true })).optional(),
  "created__gt": z.array(z.string().datetime({ offset: true })).optional(),
  "created__gte": z.array(z.string().datetime({ offset: true })).optional(),
  "created__lt": z.array(z.string().datetime({ offset: true })).optional(),
  "created__lte": z.array(z.string().datetime({ offset: true })).optional(),
  "created__n": z.array(z.string().datetime({ offset: true })).optional(),
  "created_by_request": z.string().uuid().optional(),
  "id": z.array(z.number().int()).optional(),
  "id__empty": z.boolean().optional(),
  "id__gt": z.array(z.number().int()).optional(),
  "id__gte": z.array(z.number().int()).optional(),
  "id__lt": z.array(z.number().int()).optional(),
  "id__lte": z.array(z.number().int()).optional(),
  "id__n": z.array(z.number().int()).optional(),
  "last_updated": z.array(z.string().datetime({ offset: true })).optional(),
  "last_updated__empty": z.array(z.string().datetime({ offset: true })).optional(),
  "last_updated__gt": z.array(z.string().datetime({ offset: true })).optional(),
  "last_updated__gte": z.array(z.string().datetime({ offset: true })).optional(),
  "last_updated__lt": z.array(z.string().datetime({ offset: true })).optional(),
  "last_updated__lte": z.array(z.string().datetime({ offset: true })).optional(),
  "last_updated__n": z.array(z.string().datetime({ offset: true })).optional(),
  "limit": z.number().int().describe("Number of results to return per page.").optional(),
  "modified_by_request": z.string().uuid().optional(),
  "offset": z.number().int().describe("The initial index from which to return the results.").optional(),
  "ordering": z.string().describe("Which field to use when ordering the results.").optional(),
  "termination_id": z.array(z.number().int()).optional(),
  "termination_id__empty": z.boolean().optional(),
  "termination_id__gt": z.array(z.number().int()).optional(),
  "termination_id__gte": z.array(z.number().int()).optional(),
  "termination_id__lt": z.array(z.number().int()).optional(),
  "termination_id__lte": z.array(z.number().int()).optional(),
  "termination_id__n": z.array(z.number().int()).optional(),
  "termination_type": z.string().optional(),
  "termination_type__n": z.string().optional(),
  "updated_by_request": z.string().uuid().optional()
}