import { z } from "zod"

export const inputParamsSchema = {
  "address": z.array(z.string()).optional(),
  "assigned": z.boolean().describe("Is assigned").optional(),
  "assigned_object_id": z.array(z.number().int()).optional(),
  "assigned_object_id__empty": z.boolean().optional(),
  "assigned_object_id__gt": z.array(z.number().int()).optional(),
  "assigned_object_id__gte": z.array(z.number().int()).optional(),
  "assigned_object_id__lt": z.array(z.number().int()).optional(),
  "assigned_object_id__lte": z.array(z.number().int()).optional(),
  "assigned_object_id__n": z.array(z.number().int()).optional(),
  "assigned_object_type": z.number().int().optional(),
  "assigned_object_type__n": z.number().int().optional(),
  "assigned_to_interface": z.boolean().describe("Is assigned to an interface").optional(),
  "contact": z.array(z.number().int()).describe("Contact").optional(),
  "contact__n": z.array(z.number().int()).describe("Contact").optional(),
  "contact_group": z.array(z.string()).optional(),
  "contact_group__n": z.array(z.string()).optional(),
  "contact_role": z.array(z.number().int()).describe("Contact Role").optional(),
  "contact_role__n": z.array(z.number().int()).describe("Contact Role").optional(),
  "created": z.array(z.string().datetime({ offset: true })).optional(),
  "created__empty": z.array(z.string().datetime({ offset: true })).optional(),
  "created__gt": z.array(z.string().datetime({ offset: true })).optional(),
  "created__gte": z.array(z.string().datetime({ offset: true })).optional(),
  "created__lt": z.array(z.string().datetime({ offset: true })).optional(),
  "created__lte": z.array(z.string().datetime({ offset: true })).optional(),
  "created__n": z.array(z.string().datetime({ offset: true })).optional(),
  "created_by_request": z.string().uuid().optional(),
  "description": z.array(z.string()).optional(),
  "description__empty": z.boolean().optional(),
  "description__ic": z.array(z.string()).optional(),
  "description__ie": z.array(z.string()).optional(),
  "description__iew": z.array(z.string()).optional(),
  "description__isw": z.array(z.string()).optional(),
  "description__n": z.array(z.string()).optional(),
  "description__nic": z.array(z.string()).optional(),
  "description__nie": z.array(z.string()).optional(),
  "description__niew": z.array(z.string()).optional(),
  "description__nisw": z.array(z.string()).optional(),
  "device": z.array(z.string()).optional(),
  "device_id": z.array(z.number().int()).optional(),
  "dns_name": z.array(z.string()).optional(),
  "dns_name__empty": z.boolean().optional(),
  "dns_name__ic": z.array(z.string()).optional(),
  "dns_name__ie": z.array(z.string()).optional(),
  "dns_name__iew": z.array(z.string()).optional(),
  "dns_name__isw": z.array(z.string()).optional(),
  "dns_name__n": z.array(z.string()).optional(),
  "dns_name__nic": z.array(z.string()).optional(),
  "dns_name__nie": z.array(z.string()).optional(),
  "dns_name__niew": z.array(z.string()).optional(),
  "dns_name__nisw": z.array(z.string()).optional(),
  "family": z.number().optional(),
  "fhrpgroup_id": z.array(z.number().int()).describe("FHRP group (ID)").optional(),
  "fhrpgroup_id__n": z.array(z.number().int()).describe("FHRP group (ID)").optional(),
  "id": z.array(z.number().int()).optional(),
  "id__empty": z.boolean().optional(),
  "id__gt": z.array(z.number().int()).optional(),
  "id__gte": z.array(z.number().int()).optional(),
  "id__lt": z.array(z.number().int()).optional(),
  "id__lte": z.array(z.number().int()).optional(),
  "id__n": z.array(z.number().int()).optional(),
  "interface": z.array(z.string()).describe("Interface (name)").optional(),
  "interface__n": z.array(z.string()).describe("Interface (name)").optional(),
  "interface_id": z.array(z.number().int()).describe("Interface (ID)").optional(),
  "interface_id__n": z.array(z.number().int()).describe("Interface (ID)").optional(),
  "last_updated": z.array(z.string().datetime({ offset: true })).optional(),
  "last_updated__empty": z.array(z.string().datetime({ offset: true })).optional(),
  "last_updated__gt": z.array(z.string().datetime({ offset: true })).optional(),
  "last_updated__gte": z.array(z.string().datetime({ offset: true })).optional(),
  "last_updated__lt": z.array(z.string().datetime({ offset: true })).optional(),
  "last_updated__lte": z.array(z.string().datetime({ offset: true })).optional(),
  "last_updated__n": z.array(z.string().datetime({ offset: true })).optional(),
  "limit": z.number().int().describe("Number of results to return per page.").optional(),
  "mask_length": z.array(z.number().int()).optional(),
  "mask_length__gte": z.number().optional(),
  "mask_length__lte": z.number().optional(),
  "modified_by_request": z.string().uuid().optional(),
  "nat_inside_id": z.array(z.number().int()).describe("NAT inside IP address (ID)").optional(),
  "nat_inside_id__n": z.array(z.number().int()).describe("NAT inside IP address (ID)").optional(),
  "offset": z.number().int().describe("The initial index from which to return the results.").optional(),
  "ordering": z.string().describe("Which field to use when ordering the results.").optional(),
  "parent": z.array(z.string()).optional(),
  "present_in_vrf": z.string().optional(),
  "present_in_vrf_id": z.string().optional(),
  "q": z.string().describe("Search").optional(),
  "role": z.array(z.string().nullable()).describe("The functional role of this IP").optional(),
  "role__empty": z.boolean().optional(),
  "role__ic": z.array(z.string().nullable()).describe("The functional role of this IP").optional(),
  "role__ie": z.array(z.string().nullable()).describe("The functional role of this IP").optional(),
  "role__iew": z.array(z.string().nullable()).describe("The functional role of this IP").optional(),
  "role__isw": z.array(z.string().nullable()).describe("The functional role of this IP").optional(),
  "role__n": z.array(z.string().nullable()).describe("The functional role of this IP").optional(),
  "role__nic": z.array(z.string().nullable()).describe("The functional role of this IP").optional(),
  "role__nie": z.array(z.string().nullable()).describe("The functional role of this IP").optional(),
  "role__niew": z.array(z.string().nullable()).describe("The functional role of this IP").optional(),
  "role__nisw": z.array(z.string().nullable()).describe("The functional role of this IP").optional(),
  "service_id": z.array(z.number().int()).describe("Service (ID)").optional(),
  "service_id__n": z.array(z.number().int()).describe("Service (ID)").optional(),
  "status": z.array(z.string()).describe("The operational status of this IP").optional(),
  "status__empty": z.boolean().optional(),
  "status__ic": z.array(z.string()).describe("The operational status of this IP").optional(),
  "status__ie": z.array(z.string()).describe("The operational status of this IP").optional(),
  "status__iew": z.array(z.string()).describe("The operational status of this IP").optional(),
  "status__isw": z.array(z.string()).describe("The operational status of this IP").optional(),
  "status__n": z.array(z.string()).describe("The operational status of this IP").optional(),
  "status__nic": z.array(z.string()).describe("The operational status of this IP").optional(),
  "status__nie": z.array(z.string()).describe("The operational status of this IP").optional(),
  "status__niew": z.array(z.string()).describe("The operational status of this IP").optional(),
  "status__nisw": z.array(z.string()).describe("The operational status of this IP").optional(),
  "tag": z.array(z.string()).optional(),
  "tag__n": z.array(z.string()).optional(),
  "tag_id": z.array(z.number().int()).optional(),
  "tag_id__n": z.array(z.number().int()).optional(),
  "tenant": z.array(z.string()).describe("Tenant (slug)").optional(),
  "tenant__n": z.array(z.string()).describe("Tenant (slug)").optional(),
  "tenant_group": z.array(z.string()).optional(),
  "tenant_group__n": z.array(z.string()).optional(),
  "tenant_group_id": z.array(z.string()).optional(),
  "tenant_group_id__n": z.array(z.string()).optional(),
  "tenant_id": z.array(z.number().int().nullable()).describe("Tenant (ID)").optional(),
  "tenant_id__n": z.array(z.number().int().nullable()).describe("Tenant (ID)").optional(),
  "updated_by_request": z.string().uuid().optional(),
  "virtual_machine": z.array(z.string()).optional(),
  "virtual_machine_id": z.array(z.number().int()).optional(),
  "vminterface": z.array(z.string()).describe("VM interface (name)").optional(),
  "vminterface__n": z.array(z.string()).describe("VM interface (name)").optional(),
  "vminterface_id": z.array(z.number().int()).describe("VM interface (ID)").optional(),
  "vminterface_id__n": z.array(z.number().int()).describe("VM interface (ID)").optional(),
  "vrf": z.array(z.string().nullable()).describe("VRF (RD)").optional(),
  "vrf__n": z.array(z.string().nullable()).describe("VRF (RD)").optional(),
  "vrf_id": z.array(z.number().int().nullable()).describe("VRF").optional(),
  "vrf_id__n": z.array(z.number().int().nullable()).describe("VRF").optional()
}