import { inputParamsSchema } from "./schema/root.js"
import type { OpenMCPServerTool } from "@open-mcp/core"

const tool: OpenMCPServerTool = {
  "toolName": "dcim_device_bays_list",
  "toolDescription": "Get a list of device bay objects.",
  "baseUrl": "https://api.example.com",
  "path": "/api/dcim/device-bays/",
  "method": "get",
  "security": [
    {
      "key": "sessionid",
      "value": "<mcp-env-var>SESSIONID</mcp-env-var>",
      "in": "cookie",
      "envVarName": "SESSIONID"
    },
    {
      "key": "Authorization",
      "value": "<mcp-env-var>AUTHORIZATION</mcp-env-var>",
      "in": "header",
      "envVarName": "AUTHORIZATION"
    }
  ],
  "paramsMap": {
    "query": {
      "created": "created",
      "created__empty": "created__empty",
      "created__gt": "created__gt",
      "created__gte": "created__gte",
      "created__lt": "created__lt",
      "created__lte": "created__lte",
      "created__n": "created__n",
      "created_by_request": "created_by_request",
      "description": "description",
      "description__empty": "description__empty",
      "description__ic": "description__ic",
      "description__ie": "description__ie",
      "description__iew": "description__iew",
      "description__isw": "description__isw",
      "description__n": "description__n",
      "description__nic": "description__nic",
      "description__nie": "description__nie",
      "description__niew": "description__niew",
      "description__nisw": "description__nisw",
      "device": "device",
      "device__n": "device__n",
      "device_id": "device_id",
      "device_id__n": "device_id__n",
      "device_role": "device_role",
      "device_role__n": "device_role__n",
      "device_role_id": "device_role_id",
      "device_role_id__n": "device_role_id__n",
      "device_status": "device_status",
      "device_status__empty": "device_status__empty",
      "device_status__ic": "device_status__ic",
      "device_status__ie": "device_status__ie",
      "device_status__iew": "device_status__iew",
      "device_status__isw": "device_status__isw",
      "device_status__n": "device_status__n",
      "device_status__nic": "device_status__nic",
      "device_status__nie": "device_status__nie",
      "device_status__niew": "device_status__niew",
      "device_status__nisw": "device_status__nisw",
      "device_type": "device_type",
      "device_type__n": "device_type__n",
      "device_type_id": "device_type_id",
      "device_type_id__n": "device_type_id__n",
      "id": "id",
      "id__empty": "id__empty",
      "id__gt": "id__gt",
      "id__gte": "id__gte",
      "id__lt": "id__lt",
      "id__lte": "id__lte",
      "id__n": "id__n",
      "installed_device": "installed_device",
      "installed_device__n": "installed_device__n",
      "installed_device_id": "installed_device_id",
      "installed_device_id__n": "installed_device_id__n",
      "label": "label",
      "label__empty": "label__empty",
      "label__ic": "label__ic",
      "label__ie": "label__ie",
      "label__iew": "label__iew",
      "label__isw": "label__isw",
      "label__n": "label__n",
      "label__nic": "label__nic",
      "label__nie": "label__nie",
      "label__niew": "label__niew",
      "label__nisw": "label__nisw",
      "last_updated": "last_updated",
      "last_updated__empty": "last_updated__empty",
      "last_updated__gt": "last_updated__gt",
      "last_updated__gte": "last_updated__gte",
      "last_updated__lt": "last_updated__lt",
      "last_updated__lte": "last_updated__lte",
      "last_updated__n": "last_updated__n",
      "limit": "limit",
      "location": "location",
      "location__n": "location__n",
      "location_id": "location_id",
      "location_id__n": "location_id__n",
      "modified_by_request": "modified_by_request",
      "name": "name",
      "name__empty": "name__empty",
      "name__ic": "name__ic",
      "name__ie": "name__ie",
      "name__iew": "name__iew",
      "name__isw": "name__isw",
      "name__n": "name__n",
      "name__nic": "name__nic",
      "name__nie": "name__nie",
      "name__niew": "name__niew",
      "name__nisw": "name__nisw",
      "offset": "offset",
      "ordering": "ordering",
      "q": "q",
      "rack": "rack",
      "rack__n": "rack__n",
      "rack_id": "rack_id",
      "rack_id__n": "rack_id__n",
      "region": "region",
      "region__n": "region__n",
      "region_id": "region_id",
      "region_id__n": "region_id__n",
      "site": "site",
      "site__n": "site__n",
      "site_group": "site_group",
      "site_group__n": "site_group__n",
      "site_group_id": "site_group_id",
      "site_group_id__n": "site_group_id__n",
      "site_id": "site_id",
      "site_id__n": "site_id__n",
      "tag": "tag",
      "tag__n": "tag__n",
      "tag_id": "tag_id",
      "tag_id__n": "tag_id__n",
      "updated_by_request": "updated_by_request",
      "virtual_chassis": "virtual_chassis",
      "virtual_chassis__n": "virtual_chassis__n",
      "virtual_chassis_id": "virtual_chassis_id",
      "virtual_chassis_id__n": "virtual_chassis_id__n"
    }
  },
  inputParamsSchema
}

export default tool