import { z } from "zod"

export const inputParams = {
  "app_origin": z.string().describe("业务来源，新接入方需要向支付宝申请专用来源，否则不予接入。https://yuque.antfin-inc.com/tinyapp-all/qddncu/bidushixiang").optional(),
  "build_app_type": z.string().describe("IDE开发打包类型，写死tinyApp").optional(),
  "build_extra_info": z.string().describe("扩展信息，比如adaptorName、tinycliVersion、tinycliName、import-module、allowPrecompile、extJson、allowInstallDependency、aggregationMainAppId，如果没有特殊要求，tinycliVersion版本请用最新的：\thttps://registry.npm.alibaba-inc.com/@alipay/tiny-cli/huoban-prod").optional(),
  "build_extra_mini_project_config": z.string().describe("用于覆盖开发者配置字段，实现止血和灰度逻辑").optional(),
  "build_js_permission": z.string().describe("jsapi 权限文件,钉钉外请勿传").optional(),
  "build_main_url": z.string().describe("小程序页面主入口。/index.html#page/component/index，该值需要和extendInfo中的page参数保持一致").optional(),
  "build_max_android_client_version": z.string().describe("最大Android客户端版本号，禁止使用，如果需要使用请联系小程序平台评估，否则端上会出现问题").optional(),
  "build_max_ios_client_version": z.string().describe("最大iOS客户单版本号，禁止使用，如果需要使用请联系小程序平台评估，否则端上会出现问题").optional(),
  "build_min_android_client_version": z.string().describe("最小Android客户端版本号，禁止使用，如果需要使用请联系小程序平台评估，否则端上会出现问题").optional(),
  "build_min_ios_client_version": z.string().describe("最小iOS客户单版本号，禁止使用，如果需要使用请联系小程序平台评估，否则端上会出现问题").optional(),
  "build_package_md_5": z.string().describe("源码包文件流的MD5字符串").optional(),
  "build_package_name": z.string().describe("包名称").optional(),
  "build_package_stream": z.string().describe("base64编码后的小程序源码包文件流").optional(),
  "build_qcloud_info": z.string().describe("打包平台扩展信息").optional(),
  "build_signed_pkg_url": z.string().describe("已经构建加签过的包地址").optional(),
  "build_source_pkg_size": z.string().describe("源码包大小").optional(),
  "build_source_pkg_url": z.string().describe("源码包地址，源码包大小不能超过20M且地址必须永久有效，若超20M，将限制业务来源调用。将源码文件夹整个用zip格式压缩成后缀amr文件传至文件服务器").optional(),
  "build_sub_url": z.string().describe("子入口").optional(),
  "build_version": z.string().describe("小程序版本").optional(),
  "builded_package_size": z.string().describe("已经构建过的包大小，单位是字节，主要是给自行构建的场景使用").optional(),
  "builded_package_url": z.string().describe("已经构建的包地址，目前主要自行构建的场景使用").optional(),
  "bundle_id": z.string().describe("一个端的标识，用于区分不同的客户端，每接入一个客户端，都需要向小程序应用中心申请bundleId入驻").optional(),
  "client_type": z.string().describe("多端类型，除了钉钉外其他业务方禁止使用").optional(),
  "inst_code": z.string().describe("上传调试版的接入租户类型。").optional(),
  "mini_app_id": z.string().describe("小程序ID").optional(),
  "plugin_refs": z.array(z.object({ "lazy": z.boolean().describe("是否懒加载").optional(), "plugin_id": z.string().describe("插件id，即插件的唯一标识，形如小程序的appId").optional(), "plugin_lazy": z.boolean().describe("是否懒加载").optional(), "plugin_version": z.string().describe("小程序引用的插件版本，可以指定插件版本，如：1.0.11；也可以填*，表示引用最新的插件版本，此时，当插件发布新版本后，小程序内的插件会自动更新到最新的版本。").optional() })).describe("小程序代码中引用的插件列表，包含插件id和插件版本信息，业务方需要自行解析源码包的app.json里面的plugins信息").optional()
}