import { z } from "zod"

export const inputParamsSchema = {
  "contact_id": z.array(z.number().int()).describe("Contact (ID)").optional(),
  "contact_id__n": z.array(z.number().int()).describe("Contact (ID)").optional(),
  "created": z.array(z.string().datetime({ offset: true })).optional(),
  "created__empty": z.array(z.string().datetime({ offset: true })).optional(),
  "created__gt": z.array(z.string().datetime({ offset: true })).optional(),
  "created__gte": z.array(z.string().datetime({ offset: true })).optional(),
  "created__lt": z.array(z.string().datetime({ offset: true })).optional(),
  "created__lte": z.array(z.string().datetime({ offset: true })).optional(),
  "created__n": z.array(z.string().datetime({ offset: true })).optional(),
  "created_by_request": z.string().uuid().optional(),
  "group": z.array(z.string()).optional(),
  "group__n": z.array(z.string()).optional(),
  "group_id": z.array(z.string()).optional(),
  "group_id__n": z.array(z.string()).optional(),
  "id": z.array(z.number().int()).optional(),
  "id__empty": z.boolean().optional(),
  "id__gt": z.array(z.number().int()).optional(),
  "id__gte": z.array(z.number().int()).optional(),
  "id__lt": z.array(z.number().int()).optional(),
  "id__lte": z.array(z.number().int()).optional(),
  "id__n": z.array(z.number().int()).optional(),
  "last_updated": z.array(z.string().datetime({ offset: true })).optional(),
  "last_updated__empty": z.array(z.string().datetime({ offset: true })).optional(),
  "last_updated__gt": z.array(z.string().datetime({ offset: true })).optional(),
  "last_updated__gte": z.array(z.string().datetime({ offset: true })).optional(),
  "last_updated__lt": z.array(z.string().datetime({ offset: true })).optional(),
  "last_updated__lte": z.array(z.string().datetime({ offset: true })).optional(),
  "last_updated__n": z.array(z.string().datetime({ offset: true })).optional(),
  "limit": z.number().int().describe("Number of results to return per page.").optional(),
  "modified_by_request": z.string().uuid().optional(),
  "object_id": z.array(z.number().int()).optional(),
  "object_id__empty": z.boolean().optional(),
  "object_id__gt": z.array(z.number().int()).optional(),
  "object_id__gte": z.array(z.number().int()).optional(),
  "object_id__lt": z.array(z.number().int()).optional(),
  "object_id__lte": z.array(z.number().int()).optional(),
  "object_id__n": z.array(z.number().int()).optional(),
  "object_type": z.string().optional(),
  "object_type__n": z.string().optional(),
  "object_type_id": z.number().int().optional(),
  "object_type_id__n": z.number().int().optional(),
  "offset": z.number().int().describe("The initial index from which to return the results.").optional(),
  "ordering": z.string().describe("Which field to use when ordering the results.").optional(),
  "priority": z.enum(["inactive","primary","secondary","tertiary"]).nullable().describe("* `primary` - Primary\n* `secondary` - Secondary\n* `tertiary` - Tertiary\n* `inactive` - Inactive").optional(),
  "q": z.string().describe("Search").optional(),
  "role": z.array(z.string()).describe("Contact role (slug)").optional(),
  "role__n": z.array(z.string()).describe("Contact role (slug)").optional(),
  "role_id": z.array(z.number().int()).describe("Contact role (ID)").optional(),
  "role_id__n": z.array(z.number().int()).describe("Contact role (ID)").optional(),
  "tag": z.array(z.string()).optional(),
  "tag__n": z.array(z.string()).optional(),
  "tag_id": z.array(z.number().int()).optional(),
  "tag_id__n": z.array(z.number().int()).optional(),
  "updated_by_request": z.string().uuid().optional()
}