import { inputParamsSchema } from "./schema/root.js"
import type { OpenMCPServerTool } from "@open-mcp/core"

const tool: OpenMCPServerTool = {
  "toolName": "ipam_vlans_list",
  "toolDescription": "Get a list of VLAN objects.",
  "baseUrl": "https://api.example.com",
  "path": "/api/ipam/vlans/",
  "method": "get",
  "security": [
    {
      "key": "sessionid",
      "value": "<mcp-env-var>SESSIONID</mcp-env-var>",
      "in": "cookie",
      "envVarName": "SESSIONID"
    },
    {
      "key": "Authorization",
      "value": "<mcp-env-var>AUTHORIZATION</mcp-env-var>",
      "in": "header",
      "envVarName": "AUTHORIZATION"
    }
  ],
  "paramsMap": {
    "query": {
      "available_at_site": "available_at_site",
      "available_on_device": "available_on_device",
      "available_on_virtualmachine": "available_on_virtualmachine",
      "created": "created",
      "created__empty": "created__empty",
      "created__gt": "created__gt",
      "created__gte": "created__gte",
      "created__lt": "created__lt",
      "created__lte": "created__lte",
      "created__n": "created__n",
      "created_by_request": "created_by_request",
      "description": "description",
      "description__empty": "description__empty",
      "description__ic": "description__ic",
      "description__ie": "description__ie",
      "description__iew": "description__iew",
      "description__isw": "description__isw",
      "description__n": "description__n",
      "description__nic": "description__nic",
      "description__nie": "description__nie",
      "description__niew": "description__niew",
      "description__nisw": "description__nisw",
      "group": "group",
      "group__n": "group__n",
      "group_id": "group_id",
      "group_id__n": "group_id__n",
      "id": "id",
      "id__empty": "id__empty",
      "id__gt": "id__gt",
      "id__gte": "id__gte",
      "id__lt": "id__lt",
      "id__lte": "id__lte",
      "id__n": "id__n",
      "interface_id": "interface_id",
      "l2vpn": "l2vpn",
      "l2vpn__n": "l2vpn__n",
      "l2vpn_id": "l2vpn_id",
      "l2vpn_id__n": "l2vpn_id__n",
      "last_updated": "last_updated",
      "last_updated__empty": "last_updated__empty",
      "last_updated__gt": "last_updated__gt",
      "last_updated__gte": "last_updated__gte",
      "last_updated__lt": "last_updated__lt",
      "last_updated__lte": "last_updated__lte",
      "last_updated__n": "last_updated__n",
      "limit": "limit",
      "modified_by_request": "modified_by_request",
      "name": "name",
      "name__empty": "name__empty",
      "name__ic": "name__ic",
      "name__ie": "name__ie",
      "name__iew": "name__iew",
      "name__isw": "name__isw",
      "name__n": "name__n",
      "name__nic": "name__nic",
      "name__nie": "name__nie",
      "name__niew": "name__niew",
      "name__nisw": "name__nisw",
      "offset": "offset",
      "ordering": "ordering",
      "q": "q",
      "qinq_role": "qinq_role",
      "qinq_role__empty": "qinq_role__empty",
      "qinq_role__ic": "qinq_role__ic",
      "qinq_role__ie": "qinq_role__ie",
      "qinq_role__iew": "qinq_role__iew",
      "qinq_role__isw": "qinq_role__isw",
      "qinq_role__n": "qinq_role__n",
      "qinq_role__nic": "qinq_role__nic",
      "qinq_role__nie": "qinq_role__nie",
      "qinq_role__niew": "qinq_role__niew",
      "qinq_role__nisw": "qinq_role__nisw",
      "qinq_svlan_id": "qinq_svlan_id",
      "qinq_svlan_id__n": "qinq_svlan_id__n",
      "qinq_svlan_vid": "qinq_svlan_vid",
      "qinq_svlan_vid__empty": "qinq_svlan_vid__empty",
      "qinq_svlan_vid__gt": "qinq_svlan_vid__gt",
      "qinq_svlan_vid__gte": "qinq_svlan_vid__gte",
      "qinq_svlan_vid__lt": "qinq_svlan_vid__lt",
      "qinq_svlan_vid__lte": "qinq_svlan_vid__lte",
      "qinq_svlan_vid__n": "qinq_svlan_vid__n",
      "region": "region",
      "region__n": "region__n",
      "region_id": "region_id",
      "region_id__n": "region_id__n",
      "role": "role",
      "role__n": "role__n",
      "role_id": "role_id",
      "role_id__n": "role_id__n",
      "site": "site",
      "site__n": "site__n",
      "site_group": "site_group",
      "site_group__n": "site_group__n",
      "site_group_id": "site_group_id",
      "site_group_id__n": "site_group_id__n",
      "site_id": "site_id",
      "site_id__n": "site_id__n",
      "status": "status",
      "status__empty": "status__empty",
      "status__ic": "status__ic",
      "status__ie": "status__ie",
      "status__iew": "status__iew",
      "status__isw": "status__isw",
      "status__n": "status__n",
      "status__nic": "status__nic",
      "status__nie": "status__nie",
      "status__niew": "status__niew",
      "status__nisw": "status__nisw",
      "tag": "tag",
      "tag__n": "tag__n",
      "tag_id": "tag_id",
      "tag_id__n": "tag_id__n",
      "tenant": "tenant",
      "tenant__n": "tenant__n",
      "tenant_group": "tenant_group",
      "tenant_group__n": "tenant_group__n",
      "tenant_group_id": "tenant_group_id",
      "tenant_group_id__n": "tenant_group_id__n",
      "tenant_id": "tenant_id",
      "tenant_id__n": "tenant_id__n",
      "updated_by_request": "updated_by_request",
      "vid": "vid",
      "vid__empty": "vid__empty",
      "vid__gt": "vid__gt",
      "vid__gte": "vid__gte",
      "vid__lt": "vid__lt",
      "vid__lte": "vid__lte",
      "vid__n": "vid__n",
      "vminterface_id": "vminterface_id"
    }
  },
  inputParamsSchema
}

export default tool