export const OPENAPI_URL = "https://raw.githubusercontent.com/suryamaulana1337/mcp/refs/heads/main/openaiapi.json?token=GHSAT0AAAAAADHUNJG7UEIOYT3ATFVJCJXK2D3OSBA"
export const SERVER_NAME = "_apiurl_"
export const SERVER_VERSION = "0.0.1"
export const OPERATION_FILES_RELATIVE = [
  "./tools/get_api_v1_cellular_profiling_basic/index.js",
  "./tools/get_api_v1_personal_name/index.js",
  "./tools/get_api_v1_personal_nik/index.js",
  "./tools/get_api_v1_personal_nokk/index.js",
  "./tools/get_api_v1_vrn/index.js",
  "./tools/get_api_v1_vrn_v2/index.js",
  "./tools/get_api_v1_vrn_name/index.js",
  "./tools/get_api_v1_vrn_nik/index.js",
  "./tools/get_api_v1_simcard_name/index.js",
  "./tools/get_api_v1_simcard/index.js",
  "./tools/get_api_v1_simcard_registration/index.js",
  "./tools/get_api_v1_company_name/index.js",
  "./tools/get_api_v1_company_detail_37efacb14800d25380aed1864216d921/index.js",
  "./tools/get_api_v1_dukcapil_name/index.js",
  "./tools/get_api_v1_dukcapil_nik/index.js",
  "./tools/get_api_v1_dukcapil_nokk/index.js",
  "./tools/get_api_v1_dukcapil_photo/index.js",
  "./tools/get_api_v1_dukcapil_nik_v2/index.js",
  "./tools/get_api_v1_dukcapil_nokk_v2/index.js",
  "./tools/get_api_v1_passport_name/index.js",
  "./tools/get_api_v1_passport_detail_x860827/index.js",
  "./tools/get_api_v1_boarding_name/index.js",
  "./tools/get_api_v1_boarding_detail_x860827/index.js",
  "./tools/get_api_v1_flight_name/index.js",
  "./tools/get_api_v1_flight_domestic/index.js",
  "./tools/get_api_v1_flight_detail_eyjpdii6indycgftowp1rwhjmuleegswrxbvmwc/index.js",
  "./tools/get_api_v1_leaks_search/index.js",
  "./tools/post_api_v1_leaks_search/index.js",
  "./tools/get_api_v1_business_nib/index.js",
  "./tools/get_api_v1_business_npwp/index.js",
  "./tools/get_api_v1_inet_subscription/index.js",
  "./tools/get_api_v1_inet_subdomain/index.js",
  "./tools/get_api_v1_inet_whois/index.js",
  "./tools/get_api_v1_inet_firewall/index.js",
  "./tools/get_api_v1_inet_scanport/index.js",
  "./tools/get_api_v1_inet_ip/index.js",
  "./tools/get_api_v1_inet_isdown/index.js"
]