import { inputParamsSchema } from "./schema/root.js"
import type { OpenMCPServerTool } from "@open-mcp/core"

const tool: OpenMCPServerTool = {
  "toolName": "dcim_rack_reservations_list",
  "toolDescription": "Get a list of rack reservation objects.",
  "baseUrl": "https://api.example.com",
  "path": "/api/dcim/rack-reservations/",
  "method": "get",
  "security": [
    {
      "key": "sessionid",
      "value": "<mcp-env-var>SESSIONID</mcp-env-var>",
      "in": "cookie",
      "envVarName": "SESSIONID"
    },
    {
      "key": "Authorization",
      "value": "<mcp-env-var>AUTHORIZATION</mcp-env-var>",
      "in": "header",
      "envVarName": "AUTHORIZATION"
    }
  ],
  "paramsMap": {
    "query": {
      "created": "created",
      "created__empty": "created__empty",
      "created__gt": "created__gt",
      "created__gte": "created__gte",
      "created__lt": "created__lt",
      "created__lte": "created__lte",
      "created__n": "created__n",
      "created_by_request": "created_by_request",
      "description": "description",
      "description__empty": "description__empty",
      "description__ic": "description__ic",
      "description__ie": "description__ie",
      "description__iew": "description__iew",
      "description__isw": "description__isw",
      "description__n": "description__n",
      "description__nic": "description__nic",
      "description__nie": "description__nie",
      "description__niew": "description__niew",
      "description__nisw": "description__nisw",
      "id": "id",
      "id__empty": "id__empty",
      "id__gt": "id__gt",
      "id__gte": "id__gte",
      "id__lt": "id__lt",
      "id__lte": "id__lte",
      "id__n": "id__n",
      "last_updated": "last_updated",
      "last_updated__empty": "last_updated__empty",
      "last_updated__gt": "last_updated__gt",
      "last_updated__gte": "last_updated__gte",
      "last_updated__lt": "last_updated__lt",
      "last_updated__lte": "last_updated__lte",
      "last_updated__n": "last_updated__n",
      "limit": "limit",
      "location": "location",
      "location__n": "location__n",
      "location_id": "location_id",
      "location_id__n": "location_id__n",
      "modified_by_request": "modified_by_request",
      "offset": "offset",
      "ordering": "ordering",
      "q": "q",
      "rack_id": "rack_id",
      "rack_id__n": "rack_id__n",
      "region": "region",
      "region__n": "region__n",
      "region_id": "region_id",
      "region_id__n": "region_id__n",
      "site": "site",
      "site__n": "site__n",
      "site_group": "site_group",
      "site_group__n": "site_group__n",
      "site_group_id": "site_group_id",
      "site_group_id__n": "site_group_id__n",
      "site_id": "site_id",
      "site_id__n": "site_id__n",
      "tag": "tag",
      "tag__n": "tag__n",
      "tag_id": "tag_id",
      "tag_id__n": "tag_id__n",
      "tenant": "tenant",
      "tenant__n": "tenant__n",
      "tenant_group": "tenant_group",
      "tenant_group__n": "tenant_group__n",
      "tenant_group_id": "tenant_group_id",
      "tenant_group_id__n": "tenant_group_id__n",
      "tenant_id": "tenant_id",
      "tenant_id__n": "tenant_id__n",
      "unit": "unit",
      "updated_by_request": "updated_by_request",
      "user": "user",
      "user__n": "user__n",
      "user_id": "user_id",
      "user_id__n": "user_id__n"
    }
  },
  inputParamsSchema
}

export default tool