import { inputParamsSchema } from "./schema/root.js"
import type { OpenMCPServerTool } from "@open-mcp/core"

const tool: OpenMCPServerTool = {
  "toolName": "extras_tags_list",
  "toolDescription": "Get a list of tag objects.",
  "baseUrl": "https://api.example.com",
  "path": "/api/extras/tags/",
  "method": "get",
  "security": [
    {
      "key": "sessionid",
      "value": "<mcp-env-var>SESSIONID</mcp-env-var>",
      "in": "cookie",
      "envVarName": "SESSIONID"
    },
    {
      "key": "Authorization",
      "value": "<mcp-env-var>AUTHORIZATION</mcp-env-var>",
      "in": "header",
      "envVarName": "AUTHORIZATION"
    }
  ],
  "paramsMap": {
    "query": {
      "color": "color",
      "color__empty": "color__empty",
      "color__ic": "color__ic",
      "color__ie": "color__ie",
      "color__iew": "color__iew",
      "color__isw": "color__isw",
      "color__n": "color__n",
      "color__nic": "color__nic",
      "color__nie": "color__nie",
      "color__niew": "color__niew",
      "color__nisw": "color__nisw",
      "content_type": "content_type",
      "content_type_id": "content_type_id",
      "created": "created",
      "created__empty": "created__empty",
      "created__gt": "created__gt",
      "created__gte": "created__gte",
      "created__lt": "created__lt",
      "created__lte": "created__lte",
      "created__n": "created__n",
      "created_by_request": "created_by_request",
      "description": "description",
      "description__empty": "description__empty",
      "description__ic": "description__ic",
      "description__ie": "description__ie",
      "description__iew": "description__iew",
      "description__isw": "description__isw",
      "description__n": "description__n",
      "description__nic": "description__nic",
      "description__nie": "description__nie",
      "description__niew": "description__niew",
      "description__nisw": "description__nisw",
      "for_object_type_id": "for_object_type_id",
      "id": "id",
      "id__empty": "id__empty",
      "id__gt": "id__gt",
      "id__gte": "id__gte",
      "id__lt": "id__lt",
      "id__lte": "id__lte",
      "id__n": "id__n",
      "last_updated": "last_updated",
      "last_updated__empty": "last_updated__empty",
      "last_updated__gt": "last_updated__gt",
      "last_updated__gte": "last_updated__gte",
      "last_updated__lt": "last_updated__lt",
      "last_updated__lte": "last_updated__lte",
      "last_updated__n": "last_updated__n",
      "limit": "limit",
      "modified_by_request": "modified_by_request",
      "name": "name",
      "name__empty": "name__empty",
      "name__ic": "name__ic",
      "name__ie": "name__ie",
      "name__iew": "name__iew",
      "name__isw": "name__isw",
      "name__n": "name__n",
      "name__nic": "name__nic",
      "name__nie": "name__nie",
      "name__niew": "name__niew",
      "name__nisw": "name__nisw",
      "object_types": "object_types",
      "object_types__n": "object_types__n",
      "offset": "offset",
      "ordering": "ordering",
      "q": "q",
      "slug": "slug",
      "slug__empty": "slug__empty",
      "slug__ic": "slug__ic",
      "slug__ie": "slug__ie",
      "slug__iew": "slug__iew",
      "slug__isw": "slug__isw",
      "slug__n": "slug__n",
      "slug__nic": "slug__nic",
      "slug__nie": "slug__nie",
      "slug__niew": "slug__niew",
      "slug__nisw": "slug__nisw",
      "updated_by_request": "updated_by_request",
      "weight": "weight",
      "weight__empty": "weight__empty",
      "weight__gt": "weight__gt",
      "weight__gte": "weight__gte",
      "weight__lt": "weight__lt",
      "weight__lte": "weight__lte",
      "weight__n": "weight__n"
    }
  },
  inputParamsSchema
}

export default tool