import { z } from "zod"

export const inputParamsSchema = {
  "startDateTime": z.string().max(20).describe("The start of the data retrieval range in ISO 8601 format. Default:startDateTime defaults to 24 hours before the request is made.").optional(),
  "endDateTime": z.string().max(20).describe("Timestamp in ISO 8601 format that indicates the end of the data retrieval time range. If no value is specified, 'endDateTime' defaults to the time the request is made.").optional(),
  "top": z.union([z.literal(50), z.literal(100), z.literal(500), z.literal(1000), z.literal(5000)]).describe("The number of records displayed on a page in default mode.").optional(),
  "mode": z.enum(["default","countOnly","performance"]).describe("The type of data returned by the query results (\"default\" displays all data returned by the query, \"countOnly\" displays the number of records returned, and \"performance\" limits the returned records to 500.):\n* 'default' - Displays the data returned by the query\n* 'countOnly' - Displays the number of records returned by the query\n* 'performance' - 'performance' - Displays the data in performance mode, but the \"top\" parameter does not work and there may be zero records returned even though progressRate has not reached 100. To display all records, call the API again via nextLink until progressRate has reached 100. Use count mode to avoid returning empty data.\n").optional(),
  "select": z.string().max(2048).describe("The list of fields included in search results (If no fields are specified, the query returns all supported fields.)").optional(),
  "TMV1-Query": z.string().max(2048).describe("Statement that allows you to retrieve a subset of the collected secure access activity data. \n\nSupported fields:\n\n| Field                       | Match support |\n|-----------------------------|---------------|\n| 'eventId'                   | Full match    |\n| 'eventSubId'                | Full match    |\n| 'eventTime'                 | Full match    |\n| 'objectFilePath'            | Partial match |\n| 'srcFilePath'               | Partial match |\n| 'tags'                      | Partial match |\n| 'uuid'                      | Partial match |\n| 'productCode'               | Partial match |       \n| 'filterRiskLevel'           | Partial match |           \n| 'clusterId'                 | Partial match |     \n| 'clusterName'               | Partial match |       \n| 'k8sNamespace'              | Partial match |        \n| 'containerName'             | Partial match |         \n| 'containerId'               | Partial match |       \n| 'containerImage'            | Partial match |          \n| 'processCmd'                | Partial match |      \n| 'parentCmd'                 | Partial match |     \n| 'processFilePath'           | Partial match |           \n| 'parentFilePath'            | Partial match |          \n| 'processName'               | Partial match |       \n| 'processPid'                | Full match    |      \n| 'parentPid'                 | Full match    |     \n| 'dpt'                       | Full match    |\n| 'dst'                       | Partial match |   \n| 'spt'                       | Full match    |\n| 'src'                       | Partial match |   \n| 'objectCmd'                 | Partial match |        \n| 'objectUser'                | Partial match |         \n| 'pname'                     | Partial match |         \n\nSupported operators:\n* ':' - Abbreviation of the operator \"equal to\"\n* 'and' - Operator \"and\"\n* 'or' - Operator \"or\"\n* 'not' - Operator \"not\"\n* '( )' - Symbols for grouping operands with their correct operator.\n\nNote: For more information about the query syntax and supported fields, see https://docs.trendmicro.com/en-us/enterprise/trend-micro-xdr-help/DataMappingTables.\n")
}