import { inputParamsSchema } from "./schema/root.js"
import type { OpenMCPServerTool } from "@open-mcp/core"

const tool: OpenMCPServerTool = {
  "toolName": "dcim_inventory_item_templates_list",
  "toolDescription": "Get a list of inventory item template objects.",
  "baseUrl": "https://api.example.com",
  "path": "/api/dcim/inventory-item-templates/",
  "method": "get",
  "security": [
    {
      "key": "sessionid",
      "value": "<mcp-env-var>SESSIONID</mcp-env-var>",
      "in": "cookie",
      "envVarName": "SESSIONID"
    },
    {
      "key": "Authorization",
      "value": "<mcp-env-var>AUTHORIZATION</mcp-env-var>",
      "in": "header",
      "envVarName": "AUTHORIZATION"
    }
  ],
  "paramsMap": {
    "query": {
      "component_id": "component_id",
      "component_id__empty": "component_id__empty",
      "component_id__gt": "component_id__gt",
      "component_id__gte": "component_id__gte",
      "component_id__lt": "component_id__lt",
      "component_id__lte": "component_id__lte",
      "component_id__n": "component_id__n",
      "component_type": "component_type",
      "component_type__n": "component_type__n",
      "created": "created",
      "created__empty": "created__empty",
      "created__gt": "created__gt",
      "created__gte": "created__gte",
      "created__lt": "created__lt",
      "created__lte": "created__lte",
      "created__n": "created__n",
      "created_by_request": "created_by_request",
      "description": "description",
      "description__empty": "description__empty",
      "description__ic": "description__ic",
      "description__ie": "description__ie",
      "description__iew": "description__iew",
      "description__isw": "description__isw",
      "description__n": "description__n",
      "description__nic": "description__nic",
      "description__nie": "description__nie",
      "description__niew": "description__niew",
      "description__nisw": "description__nisw",
      "device_type_id": "device_type_id",
      "device_type_id__n": "device_type_id__n",
      "id": "id",
      "id__empty": "id__empty",
      "id__gt": "id__gt",
      "id__gte": "id__gte",
      "id__lt": "id__lt",
      "id__lte": "id__lte",
      "id__n": "id__n",
      "label": "label",
      "label__empty": "label__empty",
      "label__ic": "label__ic",
      "label__ie": "label__ie",
      "label__iew": "label__iew",
      "label__isw": "label__isw",
      "label__n": "label__n",
      "label__nic": "label__nic",
      "label__nie": "label__nie",
      "label__niew": "label__niew",
      "label__nisw": "label__nisw",
      "last_updated": "last_updated",
      "last_updated__empty": "last_updated__empty",
      "last_updated__gt": "last_updated__gt",
      "last_updated__gte": "last_updated__gte",
      "last_updated__lt": "last_updated__lt",
      "last_updated__lte": "last_updated__lte",
      "last_updated__n": "last_updated__n",
      "limit": "limit",
      "manufacturer": "manufacturer",
      "manufacturer__n": "manufacturer__n",
      "manufacturer_id": "manufacturer_id",
      "manufacturer_id__n": "manufacturer_id__n",
      "modified_by_request": "modified_by_request",
      "name": "name",
      "name__empty": "name__empty",
      "name__ic": "name__ic",
      "name__ie": "name__ie",
      "name__iew": "name__iew",
      "name__isw": "name__isw",
      "name__n": "name__n",
      "name__nic": "name__nic",
      "name__nie": "name__nie",
      "name__niew": "name__niew",
      "name__nisw": "name__nisw",
      "offset": "offset",
      "ordering": "ordering",
      "parent_id": "parent_id",
      "parent_id__n": "parent_id__n",
      "part_id": "part_id",
      "part_id__empty": "part_id__empty",
      "part_id__ic": "part_id__ic",
      "part_id__ie": "part_id__ie",
      "part_id__iew": "part_id__iew",
      "part_id__isw": "part_id__isw",
      "part_id__n": "part_id__n",
      "part_id__nic": "part_id__nic",
      "part_id__nie": "part_id__nie",
      "part_id__niew": "part_id__niew",
      "part_id__nisw": "part_id__nisw",
      "q": "q",
      "role": "role",
      "role__n": "role__n",
      "role_id": "role_id",
      "role_id__n": "role_id__n",
      "updated_by_request": "updated_by_request"
    }
  },
  inputParamsSchema
}

export default tool