import { inputParamsSchema } from "./schema/root.js"
import type { OpenMCPServerTool } from "@open-mcp/core"

const tool: OpenMCPServerTool = {
  "toolName": "dcim_sites_list",
  "toolDescription": "Get a list of site objects.",
  "baseUrl": "https://api.example.com",
  "path": "/api/dcim/sites/",
  "method": "get",
  "security": [
    {
      "key": "sessionid",
      "value": "<mcp-env-var>SESSIONID</mcp-env-var>",
      "in": "cookie",
      "envVarName": "SESSIONID"
    },
    {
      "key": "Authorization",
      "value": "<mcp-env-var>AUTHORIZATION</mcp-env-var>",
      "in": "header",
      "envVarName": "AUTHORIZATION"
    }
  ],
  "paramsMap": {
    "query": {
      "asn": "asn",
      "asn__n": "asn__n",
      "asn_id": "asn_id",
      "asn_id__n": "asn_id__n",
      "contact": "contact",
      "contact__n": "contact__n",
      "contact_group": "contact_group",
      "contact_group__n": "contact_group__n",
      "contact_role": "contact_role",
      "contact_role__n": "contact_role__n",
      "created": "created",
      "created__empty": "created__empty",
      "created__gt": "created__gt",
      "created__gte": "created__gte",
      "created__lt": "created__lt",
      "created__lte": "created__lte",
      "created__n": "created__n",
      "created_by_request": "created_by_request",
      "description": "description",
      "description__empty": "description__empty",
      "description__ic": "description__ic",
      "description__ie": "description__ie",
      "description__iew": "description__iew",
      "description__isw": "description__isw",
      "description__n": "description__n",
      "description__nic": "description__nic",
      "description__nie": "description__nie",
      "description__niew": "description__niew",
      "description__nisw": "description__nisw",
      "facility": "facility",
      "facility__empty": "facility__empty",
      "facility__ic": "facility__ic",
      "facility__ie": "facility__ie",
      "facility__iew": "facility__iew",
      "facility__isw": "facility__isw",
      "facility__n": "facility__n",
      "facility__nic": "facility__nic",
      "facility__nie": "facility__nie",
      "facility__niew": "facility__niew",
      "facility__nisw": "facility__nisw",
      "group": "group",
      "group__n": "group__n",
      "group_id": "group_id",
      "group_id__n": "group_id__n",
      "id": "id",
      "id__empty": "id__empty",
      "id__gt": "id__gt",
      "id__gte": "id__gte",
      "id__lt": "id__lt",
      "id__lte": "id__lte",
      "id__n": "id__n",
      "last_updated": "last_updated",
      "last_updated__empty": "last_updated__empty",
      "last_updated__gt": "last_updated__gt",
      "last_updated__gte": "last_updated__gte",
      "last_updated__lt": "last_updated__lt",
      "last_updated__lte": "last_updated__lte",
      "last_updated__n": "last_updated__n",
      "latitude": "latitude",
      "latitude__empty": "latitude__empty",
      "latitude__gt": "latitude__gt",
      "latitude__gte": "latitude__gte",
      "latitude__lt": "latitude__lt",
      "latitude__lte": "latitude__lte",
      "latitude__n": "latitude__n",
      "limit": "limit",
      "longitude": "longitude",
      "longitude__empty": "longitude__empty",
      "longitude__gt": "longitude__gt",
      "longitude__gte": "longitude__gte",
      "longitude__lt": "longitude__lt",
      "longitude__lte": "longitude__lte",
      "longitude__n": "longitude__n",
      "modified_by_request": "modified_by_request",
      "name": "name",
      "name__empty": "name__empty",
      "name__ic": "name__ic",
      "name__ie": "name__ie",
      "name__iew": "name__iew",
      "name__isw": "name__isw",
      "name__n": "name__n",
      "name__nic": "name__nic",
      "name__nie": "name__nie",
      "name__niew": "name__niew",
      "name__nisw": "name__nisw",
      "offset": "offset",
      "ordering": "ordering",
      "q": "q",
      "region": "region",
      "region__n": "region__n",
      "region_id": "region_id",
      "region_id__n": "region_id__n",
      "slug": "slug",
      "slug__empty": "slug__empty",
      "slug__ic": "slug__ic",
      "slug__ie": "slug__ie",
      "slug__iew": "slug__iew",
      "slug__isw": "slug__isw",
      "slug__n": "slug__n",
      "slug__nic": "slug__nic",
      "slug__nie": "slug__nie",
      "slug__niew": "slug__niew",
      "slug__nisw": "slug__nisw",
      "status": "status",
      "status__empty": "status__empty",
      "status__ic": "status__ic",
      "status__ie": "status__ie",
      "status__iew": "status__iew",
      "status__isw": "status__isw",
      "status__n": "status__n",
      "status__nic": "status__nic",
      "status__nie": "status__nie",
      "status__niew": "status__niew",
      "status__nisw": "status__nisw",
      "tag": "tag",
      "tag__n": "tag__n",
      "tag_id": "tag_id",
      "tag_id__n": "tag_id__n",
      "tenant": "tenant",
      "tenant__n": "tenant__n",
      "tenant_group": "tenant_group",
      "tenant_group__n": "tenant_group__n",
      "tenant_group_id": "tenant_group_id",
      "tenant_group_id__n": "tenant_group_id__n",
      "tenant_id": "tenant_id",
      "tenant_id__n": "tenant_id__n",
      "time_zone": "time_zone",
      "time_zone__ic": "time_zone__ic",
      "time_zone__ie": "time_zone__ie",
      "time_zone__iew": "time_zone__iew",
      "time_zone__isw": "time_zone__isw",
      "time_zone__n": "time_zone__n",
      "time_zone__nic": "time_zone__nic",
      "time_zone__nie": "time_zone__nie",
      "time_zone__niew": "time_zone__niew",
      "time_zone__nisw": "time_zone__nisw",
      "updated_by_request": "updated_by_request"
    }
  },
  inputParamsSchema
}

export default tool