export const OPENAPI_URL = "https://docs.n8n.io/api/v1/openapi.yml"
export const SERVER_NAME = "n8n"
export const SERVER_VERSION = "0.0.1"
export const OPERATION_FILES_RELATIVE = [
  "./tools/post_audit/index.js",
  "./tools/post_credentials/index.js",
  "./tools/deletecredential/index.js",
  "./tools/get_credentials_schema_credentialtypename_/index.js",
  "./tools/get_executions/index.js",
  "./tools/get_executions_id_/index.js",
  "./tools/delete_executions_id_/index.js",
  "./tools/post_tags/index.js",
  "./tools/get_tags/index.js",
  "./tools/get_tags_id_/index.js",
  "./tools/delete_tags_id_/index.js",
  "./tools/put_tags_id_/index.js",
  "./tools/post_workflows/index.js",
  "./tools/get_workflows/index.js",
  "./tools/get_workflows_id_/index.js",
  "./tools/delete_workflows_id_/index.js",
  "./tools/put_workflows_id_/index.js",
  "./tools/post_workflows_id_activate/index.js",
  "./tools/post_workflows_id_deactivate/index.js",
  "./tools/put_workflows_id_transfer/index.js",
  "./tools/put_credentials_id_transfer/index.js",
  "./tools/get_workflows_id_tags/index.js",
  "./tools/put_workflows_id_tags/index.js",
  "./tools/get_users/index.js",
  "./tools/post_users/index.js",
  "./tools/get_users_id_/index.js",
  "./tools/delete_users_id_/index.js",
  "./tools/patch_users_id_role/index.js",
  "./tools/post_source_control_pull/index.js",
  "./tools/post_variables/index.js",
  "./tools/get_variables/index.js",
  "./tools/delete_variables_id_/index.js",
  "./tools/put_variables_id_/index.js",
  "./tools/post_projects/index.js",
  "./tools/get_projects/index.js",
  "./tools/delete_projects_projectid_/index.js",
  "./tools/put_projects_projectid_/index.js",
  "./tools/post_projects_projectid_users/index.js",
  "./tools/delete_projects_projectid_users_userid_/index.js",
  "./tools/patch_projects_projectid_users_userid_/index.js"
]