import { z } from "zod"

export const inputParamsSchema = {
  "color": z.array(z.string()).optional(),
  "color__empty": z.boolean().optional(),
  "color__ic": z.array(z.string()).optional(),
  "color__ie": z.array(z.string()).optional(),
  "color__iew": z.array(z.string()).optional(),
  "color__isw": z.array(z.string()).optional(),
  "color__n": z.array(z.string()).optional(),
  "color__nic": z.array(z.string()).optional(),
  "color__nie": z.array(z.string()).optional(),
  "color__niew": z.array(z.string()).optional(),
  "color__nisw": z.array(z.string()).optional(),
  "created": z.array(z.string().datetime({ offset: true })).optional(),
  "created__empty": z.array(z.string().datetime({ offset: true })).optional(),
  "created__gt": z.array(z.string().datetime({ offset: true })).optional(),
  "created__gte": z.array(z.string().datetime({ offset: true })).optional(),
  "created__lt": z.array(z.string().datetime({ offset: true })).optional(),
  "created__lte": z.array(z.string().datetime({ offset: true })).optional(),
  "created__n": z.array(z.string().datetime({ offset: true })).optional(),
  "created_by_request": z.string().uuid().optional(),
  "description": z.array(z.string()).optional(),
  "description__empty": z.boolean().optional(),
  "description__ic": z.array(z.string()).optional(),
  "description__ie": z.array(z.string()).optional(),
  "description__iew": z.array(z.string()).optional(),
  "description__isw": z.array(z.string()).optional(),
  "description__n": z.array(z.string()).optional(),
  "description__nic": z.array(z.string()).optional(),
  "description__nie": z.array(z.string()).optional(),
  "description__niew": z.array(z.string()).optional(),
  "description__nisw": z.array(z.string()).optional(),
  "device_type_id": z.array(z.number().int().nullable()).describe("Device type (ID)").optional(),
  "device_type_id__n": z.array(z.number().int().nullable()).describe("Device type (ID)").optional(),
  "id": z.array(z.number().int()).optional(),
  "id__empty": z.boolean().optional(),
  "id__gt": z.array(z.number().int()).optional(),
  "id__gte": z.array(z.number().int()).optional(),
  "id__lt": z.array(z.number().int()).optional(),
  "id__lte": z.array(z.number().int()).optional(),
  "id__n": z.array(z.number().int()).optional(),
  "label": z.array(z.string()).optional(),
  "label__empty": z.boolean().optional(),
  "label__ic": z.array(z.string()).optional(),
  "label__ie": z.array(z.string()).optional(),
  "label__iew": z.array(z.string()).optional(),
  "label__isw": z.array(z.string()).optional(),
  "label__n": z.array(z.string()).optional(),
  "label__nic": z.array(z.string()).optional(),
  "label__nie": z.array(z.string()).optional(),
  "label__niew": z.array(z.string()).optional(),
  "label__nisw": z.array(z.string()).optional(),
  "last_updated": z.array(z.string().datetime({ offset: true })).optional(),
  "last_updated__empty": z.array(z.string().datetime({ offset: true })).optional(),
  "last_updated__gt": z.array(z.string().datetime({ offset: true })).optional(),
  "last_updated__gte": z.array(z.string().datetime({ offset: true })).optional(),
  "last_updated__lt": z.array(z.string().datetime({ offset: true })).optional(),
  "last_updated__lte": z.array(z.string().datetime({ offset: true })).optional(),
  "last_updated__n": z.array(z.string().datetime({ offset: true })).optional(),
  "limit": z.number().int().describe("Number of results to return per page.").optional(),
  "modified_by_request": z.string().uuid().optional(),
  "module_type_id": z.array(z.number().int().nullable()).describe("Module type (ID)").optional(),
  "module_type_id__n": z.array(z.number().int().nullable()).describe("Module type (ID)").optional(),
  "name": z.array(z.string()).optional(),
  "name__empty": z.boolean().optional(),
  "name__ic": z.array(z.string()).optional(),
  "name__ie": z.array(z.string()).optional(),
  "name__iew": z.array(z.string()).optional(),
  "name__isw": z.array(z.string()).optional(),
  "name__n": z.array(z.string()).optional(),
  "name__nic": z.array(z.string()).optional(),
  "name__nie": z.array(z.string()).optional(),
  "name__niew": z.array(z.string()).optional(),
  "name__nisw": z.array(z.string()).optional(),
  "offset": z.number().int().describe("The initial index from which to return the results.").optional(),
  "ordering": z.string().describe("Which field to use when ordering the results.").optional(),
  "positions": z.array(z.number().int()).optional(),
  "positions__empty": z.boolean().optional(),
  "positions__gt": z.array(z.number().int()).optional(),
  "positions__gte": z.array(z.number().int()).optional(),
  "positions__lt": z.array(z.number().int()).optional(),
  "positions__lte": z.array(z.number().int()).optional(),
  "positions__n": z.array(z.number().int()).optional(),
  "q": z.string().describe("Search").optional(),
  "type": z.array(z.string()).optional(),
  "type__empty": z.boolean().optional(),
  "type__ic": z.array(z.string()).optional(),
  "type__ie": z.array(z.string()).optional(),
  "type__iew": z.array(z.string()).optional(),
  "type__isw": z.array(z.string()).optional(),
  "type__n": z.array(z.string()).optional(),
  "type__nic": z.array(z.string()).optional(),
  "type__nie": z.array(z.string()).optional(),
  "type__niew": z.array(z.string()).optional(),
  "type__nisw": z.array(z.string()).optional(),
  "updated_by_request": z.string().uuid().optional()
}