import { inputParamsSchema } from "./schema/root.js"
import type { OpenMCPServerTool } from "@open-mcp/core"

const tool: OpenMCPServerTool = {
  "toolName": "extras_webhooks_list",
  "toolDescription": "Get a list of webhook objects.",
  "baseUrl": "https://api.example.com",
  "path": "/api/extras/webhooks/",
  "method": "get",
  "security": [
    {
      "key": "sessionid",
      "value": "<mcp-env-var>SESSIONID</mcp-env-var>",
      "in": "cookie",
      "envVarName": "SESSIONID"
    },
    {
      "key": "Authorization",
      "value": "<mcp-env-var>AUTHORIZATION</mcp-env-var>",
      "in": "header",
      "envVarName": "AUTHORIZATION"
    }
  ],
  "paramsMap": {
    "query": {
      "ca_file_path": "ca_file_path",
      "ca_file_path__empty": "ca_file_path__empty",
      "ca_file_path__ic": "ca_file_path__ic",
      "ca_file_path__ie": "ca_file_path__ie",
      "ca_file_path__iew": "ca_file_path__iew",
      "ca_file_path__isw": "ca_file_path__isw",
      "ca_file_path__n": "ca_file_path__n",
      "ca_file_path__nic": "ca_file_path__nic",
      "ca_file_path__nie": "ca_file_path__nie",
      "ca_file_path__niew": "ca_file_path__niew",
      "ca_file_path__nisw": "ca_file_path__nisw",
      "created": "created",
      "created__empty": "created__empty",
      "created__gt": "created__gt",
      "created__gte": "created__gte",
      "created__lt": "created__lt",
      "created__lte": "created__lte",
      "created__n": "created__n",
      "created_by_request": "created_by_request",
      "description": "description",
      "description__empty": "description__empty",
      "description__ic": "description__ic",
      "description__ie": "description__ie",
      "description__iew": "description__iew",
      "description__isw": "description__isw",
      "description__n": "description__n",
      "description__nic": "description__nic",
      "description__nie": "description__nie",
      "description__niew": "description__niew",
      "description__nisw": "description__nisw",
      "http_content_type": "http_content_type",
      "http_content_type__empty": "http_content_type__empty",
      "http_content_type__ic": "http_content_type__ic",
      "http_content_type__ie": "http_content_type__ie",
      "http_content_type__iew": "http_content_type__iew",
      "http_content_type__isw": "http_content_type__isw",
      "http_content_type__n": "http_content_type__n",
      "http_content_type__nic": "http_content_type__nic",
      "http_content_type__nie": "http_content_type__nie",
      "http_content_type__niew": "http_content_type__niew",
      "http_content_type__nisw": "http_content_type__nisw",
      "http_method": "http_method",
      "http_method__empty": "http_method__empty",
      "http_method__ic": "http_method__ic",
      "http_method__ie": "http_method__ie",
      "http_method__iew": "http_method__iew",
      "http_method__isw": "http_method__isw",
      "http_method__n": "http_method__n",
      "http_method__nic": "http_method__nic",
      "http_method__nie": "http_method__nie",
      "http_method__niew": "http_method__niew",
      "http_method__nisw": "http_method__nisw",
      "id": "id",
      "id__empty": "id__empty",
      "id__gt": "id__gt",
      "id__gte": "id__gte",
      "id__lt": "id__lt",
      "id__lte": "id__lte",
      "id__n": "id__n",
      "last_updated": "last_updated",
      "last_updated__empty": "last_updated__empty",
      "last_updated__gt": "last_updated__gt",
      "last_updated__gte": "last_updated__gte",
      "last_updated__lt": "last_updated__lt",
      "last_updated__lte": "last_updated__lte",
      "last_updated__n": "last_updated__n",
      "limit": "limit",
      "modified_by_request": "modified_by_request",
      "name": "name",
      "name__empty": "name__empty",
      "name__ic": "name__ic",
      "name__ie": "name__ie",
      "name__iew": "name__iew",
      "name__isw": "name__isw",
      "name__n": "name__n",
      "name__nic": "name__nic",
      "name__nie": "name__nie",
      "name__niew": "name__niew",
      "name__nisw": "name__nisw",
      "offset": "offset",
      "ordering": "ordering",
      "payload_url": "payload_url",
      "q": "q",
      "secret": "secret",
      "secret__empty": "secret__empty",
      "secret__ic": "secret__ic",
      "secret__ie": "secret__ie",
      "secret__iew": "secret__iew",
      "secret__isw": "secret__isw",
      "secret__n": "secret__n",
      "secret__nic": "secret__nic",
      "secret__nie": "secret__nie",
      "secret__niew": "secret__niew",
      "secret__nisw": "secret__nisw",
      "ssl_verification": "ssl_verification",
      "tag": "tag",
      "tag__n": "tag__n",
      "tag_id": "tag_id",
      "tag_id__n": "tag_id__n",
      "updated_by_request": "updated_by_request"
    }
  },
  inputParamsSchema
}

export default tool