import { z } from "zod"

export const inputParamsSchema = {
  "id": z.number().int().describe("A unique integer value identifying this team."),
  "hire_date_after": z.string().optional(),
  "hire_date_at": z.string().optional(),
  "hire_date_before": z.string().optional(),
  "hire_date_match_all": z.boolean().optional(),
  "hire_date_not_at": z.string().optional(),
  "is_paginated": z.boolean().optional(),
  "last_active_after": z.string().optional(),
  "last_active_at": z.string().optional(),
  "last_active_before": z.string().optional(),
  "last_active_match_all": z.boolean().optional(),
  "last_active_not_at": z.string().optional(),
  "manager": z.string().optional(),
  "name": z.string().optional(),
  "name_contains": z.string().optional(),
  "name_ends_with": z.string().optional(),
  "name_equals": z.string().optional(),
  "name_match_all": z.boolean().optional(),
  "name_not_contains": z.string().optional(),
  "name_not_equals": z.string().optional(),
  "name_starts_with": z.string().optional(),
  "order_by": z.enum(["asc","desc"]).optional(),
  "page_no": z.number().int().describe("A page number within the paginated result set.").optional(),
  "page_size": z.number().int().describe("Number of results to return per page.").optional(),
  "position_contains": z.string().optional(),
  "position_ends_with": z.string().optional(),
  "position_equals": z.string().optional(),
  "position_match_all": z.boolean().optional(),
  "position_not_contains": z.string().optional(),
  "position_not_equals": z.string().optional(),
  "position_starts_with": z.string().optional(),
  "show_deactivated": z.boolean().optional(),
  "sort_by": z.string().optional(),
  "status": z.string().optional(),
  "status_contains": z.string().optional(),
  "status_ends_with": z.string().optional(),
  "status_equals": z.string().optional(),
  "status_match_all": z.boolean().optional(),
  "status_not_contains": z.string().optional(),
  "status_not_equals": z.string().optional(),
  "status_starts_with": z.string().optional(),
  "term_date_after": z.string().optional(),
  "term_date_at": z.string().optional(),
  "term_date_before": z.string().optional(),
  "term_date_match_all": z.boolean().optional(),
  "term_date_not_at": z.string().optional(),
  "user_role_contains": z.string().optional(),
  "user_role_ends_with": z.string().optional(),
  "user_role_equals": z.string().optional(),
  "user_role_match_all": z.boolean().optional(),
  "user_role_not_contains": z.string().optional(),
  "user_role_not_equals": z.string().optional(),
  "user_role_starts_with": z.string().optional()
}