import { z } from "zod"

export const inputParamsSchema = {
  "businessId": z.string(),
  "id": z.string().optional(),
  "cif": z.string().optional(),
  "zip": z.string().optional(),
  "address": z.string().optional(),
  "email": z.string().optional(),
  "city": z.string().optional(),
  "business_name": z.string().optional(),
  "tel": z.string().optional(),
  "type": z.array(z.enum(["CLIENT","PROVIDER","TPV"])).optional(),
  "category": z.string().optional(),
  "state": z.string().optional(),
  "eu_country": z.string().optional(),
  "roi": z.boolean().optional(),
  "image_id": z.string().optional(),
  "image_url": z.string().optional(),
  "accounting_account": z.string().optional(),
  "expense_account": z.string().optional(),
  "line_activity": z.string().optional(),
  "irpf": z.string().optional(),
  "tax_regime": z.string().optional(),
  "email_extra": z.string().optional(),
  "iban": z.string().optional(),
  "sepa_file": z.string().optional(),
  "expense_account_client": z.string().optional(),
  "expense_account_provider": z.string().optional(),
  "include_country": z.boolean().optional(),
  "activity_type": z.string().optional(),
  "allow_provider_auto_processing": z.boolean().optional(),
  "provider_max_quantity_auto_processing": z.number().int().optional(),
  "provider_default_currency_auto_processing": z.string().optional()
}