export const OPENAPI_URL = "https://dev.southparkdata.com/rest/v0/openapi.json"
export const SERVER_NAME = "puzzle-dev"
export const SERVER_VERSION = "0.0.1"
export const OPERATION_FILES_RELATIVE = [
  "./tools/createcompanyapi/index.js",
  "./tools/financialaccounts/index.js",
  "./tools/createfinancialaccount/index.js",
  "./tools/balances/index.js",
  "./tools/createaccountbalance/index.js",
  "./tools/vendors/index.js",
  "./tools/createvendorapi/index.js",
  "./tools/requests/index.js",
  "./tools/createrequests/index.js",
  "./tools/vendorspendingreportapi/index.js",
  "./tools/expensemetrics/index.js",
  "./tools/revenuemetrics/index.js",
  "./tools/employeemetrics/index.js",
  "./tools/createtemporarylinktoken/index.js",
  "./tools/me/index.js",
  "./tools/chartofaccounts/index.js",
  "./tools/classifications/index.js",
  "./tools/ledgeraccount/index.js",
  "./tools/workerslist/index.js",
  "./tools/journalentries/index.js",
  "./tools/upsertjournalentry/index.js",
  "./tools/gettransactions/index.js",
  "./tools/createtransactions/index.js",
  "./tools/gettransaction/index.js",
  "./tools/updatetransaction/index.js",
  "./tools/createdocument/index.js",
  "./tools/departments/index.js",
  "./tools/createdepartment/index.js",
  "./tools/locations/index.js",
  "./tools/createlocation/index.js",
  "./tools/createcontractor/index.js",
  "./tools/createemployee/index.js",
  "./tools/benefits/index.js",
  "./tools/createbenefit/index.js",
  "./tools/createdetailedpayroll/index.js",
  "./tools/getpayroll/index.js",
  "./tools/ledgerreportdownload/index.js",
  "./tools/initiateprefilledonboarding/index.js",
  "./tools/monthlychecklists/index.js"
]