import { z } from "zod"

export const inputParamsSchema = {
  "companyId": z.string(),
  "status": z.enum(["paymentOrder","cancel","paid","payment_in_progress","overdue","pending","shipped"]).describe("An enumeration.").optional(),
  "paymentDate": z.string().datetime({ offset: true }).optional(),
  "chargeAccount": z.string().describe("IBAN").optional(),
  "contactAccount": z.string().describe("IBAN").optional(),
  "issuanceDate": z.string().datetime({ offset: true }),
  "dueDate": z.string().datetime({ offset: true }),
  "accountingCode": z.string().optional(),
  "accountingName": z.string().optional(),
  "operationsCustomIds": z.array(z.string()).optional(),
  "concept": z.string(),
  "amount": z.number(),
  "accountingAmount": z.number().optional(),
  "currency": z.enum(["AED","AFN","ALL","AMD","ANG","AOA","ARS","AUD","AWG","AZN","BAM","BBD","BDT","BGN","BHD","BIF","BMD","BND","BOB","BOV","BRL","BSD","BTC","BTN","BWP","BYN","BZD","CAD","CDF","CHE","CHF","CHW","CLF","CLP","CNY","COP","COU","CRC","CUP","CVE","CZK","DJF","DKK","DOP","DZD","EEK","EGP","ERN","ETB","ETH","EUR","FJD","FKP","GBP","GEL","GHS","GIP","GMD","GNF","GTQ","GYD","HKD","HNL","HRK","HTG","HUF","IDR","ILS","INR","IQD","IRR","ISK","JMD","JOD","JPY","KES","KGS","KHR","KMF","KPW","KRW","KWD","KYD","KZT","LAK","LBP","LKR","LRD","LSL","LTC","LTL","LVL","LYD","MAD","MDL","MGA","MKD","MMK","MNT","MOP","MRU","MUR","MVR","MWK","MXN","MXV","MYR","MZN","NAD","NGN","NIO","NOK","NPR","NZD","OMR","PAB","PEN","PGK","PHP","PKR","PLN","PYG","QAR","RON","RSD","RUB","RWF","SAR","SBD","SCR","SDG","SEK","SGD","SHP","SLE","SOS","SRD","SSP","STN","SVC","SYP","SZL","THB","TJS","TMT","TND","TOP","TRY","TTD","TWD","TZS","UAH","UGX","USD","USN","UYI","UYU","UYW","UZS","VED","VEF","VES","VND","VUV","WST","XAF","XAG","XAU","XBA","XBB","XBC","XBD","XCD","XDR","XOF","XPD","XPF","XPT","XSU","XTS","XUA","XXX","YER","ZAR","ZMK","ZMW","ZWG","ZWL"]).describe("An enumeration."),
  "accountingCurrency": z.enum(["AED","AFN","ALL","AMD","ANG","AOA","ARS","AUD","AWG","AZN","BAM","BBD","BDT","BGN","BHD","BIF","BMD","BND","BOB","BOV","BRL","BSD","BTC","BTN","BWP","BYN","BZD","CAD","CDF","CHE","CHF","CHW","CLF","CLP","CNY","COP","COU","CRC","CUP","CVE","CZK","DJF","DKK","DOP","DZD","EEK","EGP","ERN","ETB","ETH","EUR","FJD","FKP","GBP","GEL","GHS","GIP","GMD","GNF","GTQ","GYD","HKD","HNL","HRK","HTG","HUF","IDR","ILS","INR","IQD","IRR","ISK","JMD","JOD","JPY","KES","KGS","KHR","KMF","KPW","KRW","KWD","KYD","KZT","LAK","LBP","LKR","LRD","LSL","LTC","LTL","LVL","LYD","MAD","MDL","MGA","MKD","MMK","MNT","MOP","MRU","MUR","MVR","MWK","MXN","MXV","MYR","MZN","NAD","NGN","NIO","NOK","NPR","NZD","OMR","PAB","PEN","PGK","PHP","PKR","PLN","PYG","QAR","RON","RSD","RUB","RWF","SAR","SBD","SCR","SDG","SEK","SGD","SHP","SLE","SOS","SRD","SSP","STN","SVC","SYP","SZL","THB","TJS","TMT","TND","TOP","TRY","TTD","TWD","TZS","UAH","UGX","USD","USN","UYI","UYU","UYW","UZS","VED","VEF","VES","VND","VUV","WST","XAF","XAG","XAU","XBA","XBB","XBC","XBD","XCD","XDR","XOF","XPD","XPF","XPT","XSU","XTS","XUA","XXX","YER","ZAR","ZMK","ZMW","ZWG","ZWL"]).describe("An enumeration.").optional(),
  "exchangeRate": z.number().optional(),
  "paymentMethod": z.string().optional(),
  "contact": z.record(z.any()).describe("<llm-instruction>This part of the input schema is truncated. If you want to pass the property `contact` to the tool, first call the tool `expandSchema` with \"/properties/contact\" in the list of pointers. This will return the expanded input schema which you can then use in the tool call. You may have to call `expandSchema` multiple times if the schema is nested.</llm-instruction>").optional(),
  "additionalInfo": z.record(z.any()).describe("<llm-instruction>This part of the input schema is truncated. If you want to pass the property `additionalInfo` to the tool, first call the tool `expandSchema` with \"/properties/additionalInfo\" in the list of pointers. This will return the expanded input schema which you can then use in the tool call. You may have to call `expandSchema` multiple times if the schema is nested.</llm-instruction>").optional(),
  "invoiceGroupDocumentId": z.string().optional(),
  "sync": z.boolean().optional(),
  "attributes": z.array(z.object({ "customId": z.string(), "value": z.string(), "valueCustomId": z.string().optional() })).optional(),
  "customId": z.string().optional(),
  "pendingAmount": z.number().optional(),
  "pendingAccountingAmount": z.number().optional(),
  "documentId": z.string().optional(),
  "documentType": z.enum(["invoice","other","note","invoiceGroup","confirming","deposit","factoring","tax","amortizationQuote","amortizationInterest","amortizationTax","refund","paymentDocument","cheque","deliveryNote","purchaseOrder"]).describe("An enumeration.").optional()
}