import { z } from "zod"

export const inputParamsSchema = {
  "ancestor": z.array(z.string()).optional(),
  "ancestor__n": z.array(z.string()).optional(),
  "ancestor_id": z.array(z.string()).optional(),
  "ancestor_id__n": z.array(z.string()).optional(),
  "color": z.array(z.string()).optional(),
  "color__empty": z.boolean().optional(),
  "color__ic": z.array(z.string()).optional(),
  "color__ie": z.array(z.string()).optional(),
  "color__iew": z.array(z.string()).optional(),
  "color__isw": z.array(z.string()).optional(),
  "color__n": z.array(z.string()).optional(),
  "color__nic": z.array(z.string()).optional(),
  "color__nie": z.array(z.string()).optional(),
  "color__niew": z.array(z.string()).optional(),
  "color__nisw": z.array(z.string()).optional(),
  "config_template_id": z.array(z.number().int().nullable()).describe("Config template (ID)").optional(),
  "config_template_id__n": z.array(z.number().int().nullable()).describe("Config template (ID)").optional(),
  "created": z.array(z.string().datetime({ offset: true })).optional(),
  "created__empty": z.array(z.string().datetime({ offset: true })).optional(),
  "created__gt": z.array(z.string().datetime({ offset: true })).optional(),
  "created__gte": z.array(z.string().datetime({ offset: true })).optional(),
  "created__lt": z.array(z.string().datetime({ offset: true })).optional(),
  "created__lte": z.array(z.string().datetime({ offset: true })).optional(),
  "created__n": z.array(z.string().datetime({ offset: true })).optional(),
  "created_by_request": z.string().uuid().optional(),
  "description": z.array(z.string()).optional(),
  "description__empty": z.boolean().optional(),
  "description__ic": z.array(z.string()).optional(),
  "description__ie": z.array(z.string()).optional(),
  "description__iew": z.array(z.string()).optional(),
  "description__isw": z.array(z.string()).optional(),
  "description__n": z.array(z.string()).optional(),
  "description__nic": z.array(z.string()).optional(),
  "description__nie": z.array(z.string()).optional(),
  "description__niew": z.array(z.string()).optional(),
  "description__nisw": z.array(z.string()).optional(),
  "id": z.array(z.number().int()).optional(),
  "id__empty": z.boolean().optional(),
  "id__gt": z.array(z.number().int()).optional(),
  "id__gte": z.array(z.number().int()).optional(),
  "id__lt": z.array(z.number().int()).optional(),
  "id__lte": z.array(z.number().int()).optional(),
  "id__n": z.array(z.number().int()).optional(),
  "last_updated": z.array(z.string().datetime({ offset: true })).optional(),
  "last_updated__empty": z.array(z.string().datetime({ offset: true })).optional(),
  "last_updated__gt": z.array(z.string().datetime({ offset: true })).optional(),
  "last_updated__gte": z.array(z.string().datetime({ offset: true })).optional(),
  "last_updated__lt": z.array(z.string().datetime({ offset: true })).optional(),
  "last_updated__lte": z.array(z.string().datetime({ offset: true })).optional(),
  "last_updated__n": z.array(z.string().datetime({ offset: true })).optional(),
  "limit": z.number().int().describe("Number of results to return per page.").optional(),
  "modified_by_request": z.string().uuid().optional(),
  "name": z.array(z.string()).optional(),
  "name__empty": z.boolean().optional(),
  "name__ic": z.array(z.string()).optional(),
  "name__ie": z.array(z.string()).optional(),
  "name__iew": z.array(z.string()).optional(),
  "name__isw": z.array(z.string()).optional(),
  "name__n": z.array(z.string()).optional(),
  "name__nic": z.array(z.string()).optional(),
  "name__nie": z.array(z.string()).optional(),
  "name__niew": z.array(z.string()).optional(),
  "name__nisw": z.array(z.string()).optional(),
  "offset": z.number().int().describe("The initial index from which to return the results.").optional(),
  "ordering": z.string().describe("Which field to use when ordering the results.").optional(),
  "parent": z.array(z.string()).describe("Parent device role (slug)").optional(),
  "parent__n": z.array(z.string()).describe("Parent device role (slug)").optional(),
  "parent_id": z.array(z.number().int().nullable()).describe("Parent device role (ID)").optional(),
  "parent_id__n": z.array(z.number().int().nullable()).describe("Parent device role (ID)").optional(),
  "q": z.string().describe("Search").optional(),
  "slug": z.array(z.string()).optional(),
  "slug__empty": z.boolean().optional(),
  "slug__ic": z.array(z.string()).optional(),
  "slug__ie": z.array(z.string()).optional(),
  "slug__iew": z.array(z.string()).optional(),
  "slug__isw": z.array(z.string()).optional(),
  "slug__n": z.array(z.string()).optional(),
  "slug__nic": z.array(z.string()).optional(),
  "slug__nie": z.array(z.string()).optional(),
  "slug__niew": z.array(z.string()).optional(),
  "slug__nisw": z.array(z.string()).optional(),
  "tag": z.array(z.string()).optional(),
  "tag__n": z.array(z.string()).optional(),
  "tag_id": z.array(z.number().int()).optional(),
  "tag_id__n": z.array(z.number().int()).optional(),
  "updated_by_request": z.string().uuid().optional(),
  "vm_role": z.boolean().optional()
}