export const SERVER_NAME = "api_sanity_io"
export const SERVER_VERSION = "0.0.1"
export const OPERATION_FILES_RELATIVE = [
  "./operations/getpermissions.js",
  "./operations/createpermission.js",
  "./operations/getpermission.js",
  "./operations/updatepermission.js",
  "./operations/deletepermission.js",
  "./operations/getmypermissions.js",
  "./operations/getuserpermissions.js",
  "./operations/getusers.js",
  "./operations/adddefaultroletousers.js",
  "./operations/getuser.js",
  "./operations/removeuser.js",
  "./operations/addroletouser.js",
  "./operations/removerolefromuser.js",
  "./operations/getuserpermissions.js",
  "./operations/getroles.js",
  "./operations/createrole.js",
  "./operations/getrole.js",
  "./operations/updaterole.js",
  "./operations/deleterole.js",
  "./operations/getrequests.js",
  "./operations/createrequest.js",
  "./operations/acceptrequest.js",
  "./operations/declinerequest.js",
  "./operations/getmyrequests.js",
  "./operations/getinvites.js",
  "./operations/createinvite.js",
  "./operations/revokeinvite.js",
  "./operations/getinvitebytoken.js",
  "./operations/acceptinvite.js",
  "./operations/getrobots.js",
  "./operations/createrobot.js",
  "./operations/getrobot.js",
  "./operations/deleterobot.js",
  "./operations/checkuserpermissions.js"
]