import { inputParamsSchema } from "./schema/root.js"
import type { OpenMCPServerTool } from "@open-mcp/core"

const tool: OpenMCPServerTool = {
  "toolName": "dcim_modules_list",
  "toolDescription": "Get a list of module objects.",
  "baseUrl": "https://api.example.com",
  "path": "/api/dcim/modules/",
  "method": "get",
  "security": [
    {
      "key": "sessionid",
      "value": "<mcp-env-var>SESSIONID</mcp-env-var>",
      "in": "cookie",
      "envVarName": "SESSIONID"
    },
    {
      "key": "Authorization",
      "value": "<mcp-env-var>AUTHORIZATION</mcp-env-var>",
      "in": "header",
      "envVarName": "AUTHORIZATION"
    }
  ],
  "paramsMap": {
    "query": {
      "asset_tag": "asset_tag",
      "asset_tag__empty": "asset_tag__empty",
      "asset_tag__ic": "asset_tag__ic",
      "asset_tag__ie": "asset_tag__ie",
      "asset_tag__iew": "asset_tag__iew",
      "asset_tag__isw": "asset_tag__isw",
      "asset_tag__n": "asset_tag__n",
      "asset_tag__nic": "asset_tag__nic",
      "asset_tag__nie": "asset_tag__nie",
      "asset_tag__niew": "asset_tag__niew",
      "asset_tag__nisw": "asset_tag__nisw",
      "created": "created",
      "created__empty": "created__empty",
      "created__gt": "created__gt",
      "created__gte": "created__gte",
      "created__lt": "created__lt",
      "created__lte": "created__lte",
      "created__n": "created__n",
      "created_by_request": "created_by_request",
      "description": "description",
      "description__empty": "description__empty",
      "description__ic": "description__ic",
      "description__ie": "description__ie",
      "description__iew": "description__iew",
      "description__isw": "description__isw",
      "description__n": "description__n",
      "description__nic": "description__nic",
      "description__nie": "description__nie",
      "description__niew": "description__niew",
      "description__nisw": "description__nisw",
      "device": "device",
      "device__n": "device__n",
      "device_id": "device_id",
      "device_id__n": "device_id__n",
      "id": "id",
      "id__empty": "id__empty",
      "id__gt": "id__gt",
      "id__gte": "id__gte",
      "id__lt": "id__lt",
      "id__lte": "id__lte",
      "id__n": "id__n",
      "last_updated": "last_updated",
      "last_updated__empty": "last_updated__empty",
      "last_updated__gt": "last_updated__gt",
      "last_updated__gte": "last_updated__gte",
      "last_updated__lt": "last_updated__lt",
      "last_updated__lte": "last_updated__lte",
      "last_updated__n": "last_updated__n",
      "limit": "limit",
      "location": "location",
      "location__n": "location__n",
      "location_id": "location_id",
      "location_id__n": "location_id__n",
      "manufacturer": "manufacturer",
      "manufacturer__n": "manufacturer__n",
      "manufacturer_id": "manufacturer_id",
      "manufacturer_id__n": "manufacturer_id__n",
      "modified_by_request": "modified_by_request",
      "module_bay_id": "module_bay_id",
      "module_bay_id__n": "module_bay_id__n",
      "module_type": "module_type",
      "module_type__n": "module_type__n",
      "module_type_id": "module_type_id",
      "module_type_id__n": "module_type_id__n",
      "offset": "offset",
      "ordering": "ordering",
      "q": "q",
      "rack": "rack",
      "rack__n": "rack__n",
      "rack_id": "rack_id",
      "rack_id__n": "rack_id__n",
      "region": "region",
      "region__n": "region__n",
      "region_id": "region_id",
      "region_id__n": "region_id__n",
      "serial": "serial",
      "serial__empty": "serial__empty",
      "serial__ic": "serial__ic",
      "serial__ie": "serial__ie",
      "serial__iew": "serial__iew",
      "serial__isw": "serial__isw",
      "serial__n": "serial__n",
      "serial__nic": "serial__nic",
      "serial__nie": "serial__nie",
      "serial__niew": "serial__niew",
      "serial__nisw": "serial__nisw",
      "site": "site",
      "site__n": "site__n",
      "site_group": "site_group",
      "site_group__n": "site_group__n",
      "site_group_id": "site_group_id",
      "site_group_id__n": "site_group_id__n",
      "site_id": "site_id",
      "site_id__n": "site_id__n",
      "status": "status",
      "status__empty": "status__empty",
      "status__ic": "status__ic",
      "status__ie": "status__ie",
      "status__iew": "status__iew",
      "status__isw": "status__isw",
      "status__n": "status__n",
      "status__nic": "status__nic",
      "status__nie": "status__nie",
      "status__niew": "status__niew",
      "status__nisw": "status__nisw",
      "tag": "tag",
      "tag__n": "tag__n",
      "tag_id": "tag_id",
      "tag_id__n": "tag_id__n",
      "updated_by_request": "updated_by_request"
    }
  },
  inputParamsSchema
}

export default tool