import { inputParamsSchema } from "./schema/root.js"
import type { OpenMCPServerTool } from "@open-mcp/core"

const tool: OpenMCPServerTool = {
  "toolName": "dcim_power_feeds_list",
  "toolDescription": "Get a list of power feed objects.",
  "baseUrl": "https://api.example.com",
  "path": "/api/dcim/power-feeds/",
  "method": "get",
  "security": [
    {
      "key": "sessionid",
      "value": "<mcp-env-var>SESSIONID</mcp-env-var>",
      "in": "cookie",
      "envVarName": "SESSIONID"
    },
    {
      "key": "Authorization",
      "value": "<mcp-env-var>AUTHORIZATION</mcp-env-var>",
      "in": "header",
      "envVarName": "AUTHORIZATION"
    }
  ],
  "paramsMap": {
    "query": {
      "amperage": "amperage",
      "amperage__empty": "amperage__empty",
      "amperage__gt": "amperage__gt",
      "amperage__gte": "amperage__gte",
      "amperage__lt": "amperage__lt",
      "amperage__lte": "amperage__lte",
      "amperage__n": "amperage__n",
      "available_power": "available_power",
      "available_power__empty": "available_power__empty",
      "available_power__gt": "available_power__gt",
      "available_power__gte": "available_power__gte",
      "available_power__lt": "available_power__lt",
      "available_power__lte": "available_power__lte",
      "available_power__n": "available_power__n",
      "cable_end": "cable_end",
      "cable_id": "cable_id",
      "cable_id__n": "cable_id__n",
      "cabled": "cabled",
      "connected": "connected",
      "created": "created",
      "created__empty": "created__empty",
      "created__gt": "created__gt",
      "created__gte": "created__gte",
      "created__lt": "created__lt",
      "created__lte": "created__lte",
      "created__n": "created__n",
      "created_by_request": "created_by_request",
      "description": "description",
      "description__empty": "description__empty",
      "description__ic": "description__ic",
      "description__ie": "description__ie",
      "description__iew": "description__iew",
      "description__isw": "description__isw",
      "description__n": "description__n",
      "description__nic": "description__nic",
      "description__nie": "description__nie",
      "description__niew": "description__niew",
      "description__nisw": "description__nisw",
      "id": "id",
      "id__empty": "id__empty",
      "id__gt": "id__gt",
      "id__gte": "id__gte",
      "id__lt": "id__lt",
      "id__lte": "id__lte",
      "id__n": "id__n",
      "last_updated": "last_updated",
      "last_updated__empty": "last_updated__empty",
      "last_updated__gt": "last_updated__gt",
      "last_updated__gte": "last_updated__gte",
      "last_updated__lt": "last_updated__lt",
      "last_updated__lte": "last_updated__lte",
      "last_updated__n": "last_updated__n",
      "limit": "limit",
      "mark_connected": "mark_connected",
      "max_utilization": "max_utilization",
      "max_utilization__empty": "max_utilization__empty",
      "max_utilization__gt": "max_utilization__gt",
      "max_utilization__gte": "max_utilization__gte",
      "max_utilization__lt": "max_utilization__lt",
      "max_utilization__lte": "max_utilization__lte",
      "max_utilization__n": "max_utilization__n",
      "modified_by_request": "modified_by_request",
      "name": "name",
      "name__empty": "name__empty",
      "name__ic": "name__ic",
      "name__ie": "name__ie",
      "name__iew": "name__iew",
      "name__isw": "name__isw",
      "name__n": "name__n",
      "name__nic": "name__nic",
      "name__nie": "name__nie",
      "name__niew": "name__niew",
      "name__nisw": "name__nisw",
      "occupied": "occupied",
      "offset": "offset",
      "ordering": "ordering",
      "phase": "phase",
      "power_panel_id": "power_panel_id",
      "power_panel_id__n": "power_panel_id__n",
      "q": "q",
      "rack_id": "rack_id",
      "rack_id__n": "rack_id__n",
      "region": "region",
      "region__n": "region__n",
      "region_id": "region_id",
      "region_id__n": "region_id__n",
      "site": "site",
      "site__n": "site__n",
      "site_group": "site_group",
      "site_group__n": "site_group__n",
      "site_group_id": "site_group_id",
      "site_group_id__n": "site_group_id__n",
      "site_id": "site_id",
      "site_id__n": "site_id__n",
      "status": "status",
      "status__empty": "status__empty",
      "status__ic": "status__ic",
      "status__ie": "status__ie",
      "status__iew": "status__iew",
      "status__isw": "status__isw",
      "status__n": "status__n",
      "status__nic": "status__nic",
      "status__nie": "status__nie",
      "status__niew": "status__niew",
      "status__nisw": "status__nisw",
      "supply": "supply",
      "tag": "tag",
      "tag__n": "tag__n",
      "tag_id": "tag_id",
      "tag_id__n": "tag_id__n",
      "tenant": "tenant",
      "tenant__n": "tenant__n",
      "tenant_group": "tenant_group",
      "tenant_group__n": "tenant_group__n",
      "tenant_group_id": "tenant_group_id",
      "tenant_group_id__n": "tenant_group_id__n",
      "tenant_id": "tenant_id",
      "tenant_id__n": "tenant_id__n",
      "type": "type",
      "updated_by_request": "updated_by_request",
      "voltage": "voltage",
      "voltage__empty": "voltage__empty",
      "voltage__gt": "voltage__gt",
      "voltage__gte": "voltage__gte",
      "voltage__lt": "voltage__lt",
      "voltage__lte": "voltage__lte",
      "voltage__n": "voltage__n"
    }
  },
  inputParamsSchema
}

export default tool