import { z } from "zod"

export const inputParamsSchema = {
  "ca_file_path": z.array(z.string()).optional(),
  "ca_file_path__empty": z.boolean().optional(),
  "ca_file_path__ic": z.array(z.string()).optional(),
  "ca_file_path__ie": z.array(z.string()).optional(),
  "ca_file_path__iew": z.array(z.string()).optional(),
  "ca_file_path__isw": z.array(z.string()).optional(),
  "ca_file_path__n": z.array(z.string()).optional(),
  "ca_file_path__nic": z.array(z.string()).optional(),
  "ca_file_path__nie": z.array(z.string()).optional(),
  "ca_file_path__niew": z.array(z.string()).optional(),
  "ca_file_path__nisw": z.array(z.string()).optional(),
  "created": z.array(z.string().datetime({ offset: true })).optional(),
  "created__empty": z.array(z.string().datetime({ offset: true })).optional(),
  "created__gt": z.array(z.string().datetime({ offset: true })).optional(),
  "created__gte": z.array(z.string().datetime({ offset: true })).optional(),
  "created__lt": z.array(z.string().datetime({ offset: true })).optional(),
  "created__lte": z.array(z.string().datetime({ offset: true })).optional(),
  "created__n": z.array(z.string().datetime({ offset: true })).optional(),
  "created_by_request": z.string().uuid().optional(),
  "description": z.array(z.string()).optional(),
  "description__empty": z.boolean().optional(),
  "description__ic": z.array(z.string()).optional(),
  "description__ie": z.array(z.string()).optional(),
  "description__iew": z.array(z.string()).optional(),
  "description__isw": z.array(z.string()).optional(),
  "description__n": z.array(z.string()).optional(),
  "description__nic": z.array(z.string()).optional(),
  "description__nie": z.array(z.string()).optional(),
  "description__niew": z.array(z.string()).optional(),
  "description__nisw": z.array(z.string()).optional(),
  "http_content_type": z.array(z.string()).optional(),
  "http_content_type__empty": z.boolean().optional(),
  "http_content_type__ic": z.array(z.string()).optional(),
  "http_content_type__ie": z.array(z.string()).optional(),
  "http_content_type__iew": z.array(z.string()).optional(),
  "http_content_type__isw": z.array(z.string()).optional(),
  "http_content_type__n": z.array(z.string()).optional(),
  "http_content_type__nic": z.array(z.string()).optional(),
  "http_content_type__nie": z.array(z.string()).optional(),
  "http_content_type__niew": z.array(z.string()).optional(),
  "http_content_type__nisw": z.array(z.string()).optional(),
  "http_method": z.array(z.string()).optional(),
  "http_method__empty": z.boolean().optional(),
  "http_method__ic": z.array(z.string()).optional(),
  "http_method__ie": z.array(z.string()).optional(),
  "http_method__iew": z.array(z.string()).optional(),
  "http_method__isw": z.array(z.string()).optional(),
  "http_method__n": z.array(z.string()).optional(),
  "http_method__nic": z.array(z.string()).optional(),
  "http_method__nie": z.array(z.string()).optional(),
  "http_method__niew": z.array(z.string()).optional(),
  "http_method__nisw": z.array(z.string()).optional(),
  "id": z.array(z.number().int()).optional(),
  "id__empty": z.boolean().optional(),
  "id__gt": z.array(z.number().int()).optional(),
  "id__gte": z.array(z.number().int()).optional(),
  "id__lt": z.array(z.number().int()).optional(),
  "id__lte": z.array(z.number().int()).optional(),
  "id__n": z.array(z.number().int()).optional(),
  "last_updated": z.array(z.string().datetime({ offset: true })).optional(),
  "last_updated__empty": z.array(z.string().datetime({ offset: true })).optional(),
  "last_updated__gt": z.array(z.string().datetime({ offset: true })).optional(),
  "last_updated__gte": z.array(z.string().datetime({ offset: true })).optional(),
  "last_updated__lt": z.array(z.string().datetime({ offset: true })).optional(),
  "last_updated__lte": z.array(z.string().datetime({ offset: true })).optional(),
  "last_updated__n": z.array(z.string().datetime({ offset: true })).optional(),
  "limit": z.number().int().describe("Number of results to return per page.").optional(),
  "modified_by_request": z.string().uuid().optional(),
  "name": z.array(z.string()).optional(),
  "name__empty": z.boolean().optional(),
  "name__ic": z.array(z.string()).optional(),
  "name__ie": z.array(z.string()).optional(),
  "name__iew": z.array(z.string()).optional(),
  "name__isw": z.array(z.string()).optional(),
  "name__n": z.array(z.string()).optional(),
  "name__nic": z.array(z.string()).optional(),
  "name__nie": z.array(z.string()).optional(),
  "name__niew": z.array(z.string()).optional(),
  "name__nisw": z.array(z.string()).optional(),
  "offset": z.number().int().describe("The initial index from which to return the results.").optional(),
  "ordering": z.string().describe("Which field to use when ordering the results.").optional(),
  "payload_url": z.array(z.string()).optional(),
  "q": z.string().describe("Search").optional(),
  "secret": z.array(z.string()).optional(),
  "secret__empty": z.boolean().optional(),
  "secret__ic": z.array(z.string()).optional(),
  "secret__ie": z.array(z.string()).optional(),
  "secret__iew": z.array(z.string()).optional(),
  "secret__isw": z.array(z.string()).optional(),
  "secret__n": z.array(z.string()).optional(),
  "secret__nic": z.array(z.string()).optional(),
  "secret__nie": z.array(z.string()).optional(),
  "secret__niew": z.array(z.string()).optional(),
  "secret__nisw": z.array(z.string()).optional(),
  "ssl_verification": z.boolean().optional(),
  "tag": z.array(z.string()).optional(),
  "tag__n": z.array(z.string()).optional(),
  "tag_id": z.array(z.number().int()).optional(),
  "tag_id__n": z.array(z.number().int()).optional(),
  "updated_by_request": z.string().uuid().optional()
}