import { z } from "zod"

export const inputParamsSchema = {
  "chargeback": z.boolean().describe("Indica se é um chargeback").optional(),
  "company_id": z.string().describe("ID da empresa"),
  "workspace_id": z.string().describe("ID do workspace"),
  "application_id": z.string().describe("ID da aplicação"),
  "correlation_id": z.string().describe("ID de correlação").optional(),
  "nsu": z.string().describe("Número Sequencial Único").optional(),
  "authorization_code": z.string().describe("Código de autorização").optional(),
  "tid": z.string().describe("Terminal ID").optional(),
  "brand": z.string().describe("Bandeira do cartão"),
  "acquirer": z.string().describe("Adquirente").optional(),
  "payment_method": z.enum(["credit","debit","pix","boleto"]).describe("Método de pagamento").optional(),
  "installments": z.number().int().gte(1).describe("Número de parcelas").optional(),
  "current_installment": z.number().int().gte(1).describe("Parcela atual").optional(),
  "paid_amount": z.number().describe("Valor pago da transação"),
  "total_invoice_amount": z.number().describe("Valor total da fatura"),
  "interest_rate": z.number().describe("Taxa de juros ao consumidor").optional(),
  "transaction_date": z.string().datetime({ offset: true }).describe("Data da transação"),
  "original_date": z.string().datetime({ offset: true }).describe("Data original da transação").optional(),
  "transaction_type": z.string().describe("Tipo da transação").optional(),
  "reference_id": z.string().describe("ID de referência").optional(),
  "receita_tarifa_servico_b2c": z.number().describe("Receita de tarifa de serviço B2C").optional(),
  "receita_taxa_parcelamento": z.number().describe("Receita de taxa de parcelamento").optional(),
  "receita_b2b": z.number().describe("Receita B2B").optional(),
  "receita_aluguel_pos": z.number().describe("Receita de aluguel de POS").optional(),
  "mdr": z.number().describe("Taxa MDR (Merchant Discount Rate)").optional(),
  "anticipation_expenses": z.number().describe("Custos de antecipação").optional(),
  "tax_expenses": z.number().describe("Custos de impostos").optional(),
  "transfer_date": z.string().describe("Data de transferência").optional(),
  "liquid_final_amount": z.number().describe("Valor líquido final"),
  "adjustment_origin": z.string().describe("Origem do ajuste").optional(),
  "adjustment_detail": z.string().describe("Detalhes do ajuste"),
  "export_date": z.string().datetime({ offset: true }).describe("Data de exportação"),
  "nseq_pedido": z.string().describe("Número sequencial do pedido").optional(),
  "entity_document": z.string().describe("Documento da entidade").optional(),
  "tipo_client_b2c": z.string().describe("Tipo de cliente B2C").optional(),
  "invoice_count": z.number().int().describe("Quantidade de faturas").optional(),
  "capture_date": z.string().datetime({ offset: true }).describe("Data de captura").optional()
}