import { inputParamsSchema } from "./schema/root.js"
import type { OpenMCPServerTool } from "@open-mcp/core"

const tool: OpenMCPServerTool = {
  "toolName": "dcim_interface_templates_list",
  "toolDescription": "Get a list of interface template objects.",
  "baseUrl": "https://api.example.com",
  "path": "/api/dcim/interface-templates/",
  "method": "get",
  "security": [
    {
      "key": "sessionid",
      "value": "<mcp-env-var>SESSIONID</mcp-env-var>",
      "in": "cookie",
      "envVarName": "SESSIONID"
    },
    {
      "key": "Authorization",
      "value": "<mcp-env-var>AUTHORIZATION</mcp-env-var>",
      "in": "header",
      "envVarName": "AUTHORIZATION"
    }
  ],
  "paramsMap": {
    "query": {
      "bridge_id": "bridge_id",
      "bridge_id__n": "bridge_id__n",
      "created": "created",
      "created__empty": "created__empty",
      "created__gt": "created__gt",
      "created__gte": "created__gte",
      "created__lt": "created__lt",
      "created__lte": "created__lte",
      "created__n": "created__n",
      "created_by_request": "created_by_request",
      "description": "description",
      "description__empty": "description__empty",
      "description__ic": "description__ic",
      "description__ie": "description__ie",
      "description__iew": "description__iew",
      "description__isw": "description__isw",
      "description__n": "description__n",
      "description__nic": "description__nic",
      "description__nie": "description__nie",
      "description__niew": "description__niew",
      "description__nisw": "description__nisw",
      "device_type_id": "device_type_id",
      "device_type_id__n": "device_type_id__n",
      "enabled": "enabled",
      "id": "id",
      "id__empty": "id__empty",
      "id__gt": "id__gt",
      "id__gte": "id__gte",
      "id__lt": "id__lt",
      "id__lte": "id__lte",
      "id__n": "id__n",
      "label": "label",
      "label__empty": "label__empty",
      "label__ic": "label__ic",
      "label__ie": "label__ie",
      "label__iew": "label__iew",
      "label__isw": "label__isw",
      "label__n": "label__n",
      "label__nic": "label__nic",
      "label__nie": "label__nie",
      "label__niew": "label__niew",
      "label__nisw": "label__nisw",
      "last_updated": "last_updated",
      "last_updated__empty": "last_updated__empty",
      "last_updated__gt": "last_updated__gt",
      "last_updated__gte": "last_updated__gte",
      "last_updated__lt": "last_updated__lt",
      "last_updated__lte": "last_updated__lte",
      "last_updated__n": "last_updated__n",
      "limit": "limit",
      "mgmt_only": "mgmt_only",
      "modified_by_request": "modified_by_request",
      "module_type_id": "module_type_id",
      "module_type_id__n": "module_type_id__n",
      "name": "name",
      "name__empty": "name__empty",
      "name__ic": "name__ic",
      "name__ie": "name__ie",
      "name__iew": "name__iew",
      "name__isw": "name__isw",
      "name__n": "name__n",
      "name__nic": "name__nic",
      "name__nie": "name__nie",
      "name__niew": "name__niew",
      "name__nisw": "name__nisw",
      "offset": "offset",
      "ordering": "ordering",
      "poe_mode": "poe_mode",
      "poe_mode__empty": "poe_mode__empty",
      "poe_mode__ic": "poe_mode__ic",
      "poe_mode__ie": "poe_mode__ie",
      "poe_mode__iew": "poe_mode__iew",
      "poe_mode__isw": "poe_mode__isw",
      "poe_mode__n": "poe_mode__n",
      "poe_mode__nic": "poe_mode__nic",
      "poe_mode__nie": "poe_mode__nie",
      "poe_mode__niew": "poe_mode__niew",
      "poe_mode__nisw": "poe_mode__nisw",
      "poe_type": "poe_type",
      "poe_type__empty": "poe_type__empty",
      "poe_type__ic": "poe_type__ic",
      "poe_type__ie": "poe_type__ie",
      "poe_type__iew": "poe_type__iew",
      "poe_type__isw": "poe_type__isw",
      "poe_type__n": "poe_type__n",
      "poe_type__nic": "poe_type__nic",
      "poe_type__nie": "poe_type__nie",
      "poe_type__niew": "poe_type__niew",
      "poe_type__nisw": "poe_type__nisw",
      "q": "q",
      "rf_role": "rf_role",
      "rf_role__empty": "rf_role__empty",
      "rf_role__ic": "rf_role__ic",
      "rf_role__ie": "rf_role__ie",
      "rf_role__iew": "rf_role__iew",
      "rf_role__isw": "rf_role__isw",
      "rf_role__n": "rf_role__n",
      "rf_role__nic": "rf_role__nic",
      "rf_role__nie": "rf_role__nie",
      "rf_role__niew": "rf_role__niew",
      "rf_role__nisw": "rf_role__nisw",
      "type": "type",
      "type__empty": "type__empty",
      "type__ic": "type__ic",
      "type__ie": "type__ie",
      "type__iew": "type__iew",
      "type__isw": "type__isw",
      "type__n": "type__n",
      "type__nic": "type__nic",
      "type__nie": "type__nie",
      "type__niew": "type__niew",
      "type__nisw": "type__nisw",
      "updated_by_request": "updated_by_request"
    }
  },
  inputParamsSchema
}

export default tool