import { z } from "zod"

export const inputParamsSchema = {
  "prompt": z.string().describe("A string providing context for the model to complete."),
  "model": z.union([z.enum(["meta-llama/Llama-2-70b-hf","mistralai/Mistral-7B-v0.1","mistralai/Mixtral-8x7B-v0.1","Meta-Llama/Llama-Guard-7b"]), z.string()]).describe("The name of the model to query.<br> <br> [See all of Together AI's chat models](https://docs.together.ai/docs/serverless-models#chat-models)\n"),
  "max_tokens": z.number().int().describe("The maximum number of tokens to generate.").optional(),
  "stop": z.array(z.string()).describe("A list of string sequences that will truncate (stop) inference text output. For example, \"</s>\" will stop generation as soon as the model generates the given token.").optional(),
  "temperature": z.number().describe("A decimal number from 0-1 that determines the degree of randomness in the response. A temperature less than 1 favors more correctness and is appropriate for question answering or summarization. A value closer to 1 introduces more randomness in the output.").optional(),
  "top_p": z.number().describe("A percentage (also called the nucleus parameter) that's used to dynamically adjust the number of choices for each predicted token based on the cumulative probabilities. It specifies a probability threshold below which all less likely tokens are filtered out. This technique helps maintain diversity and generate more fluent and natural-sounding text.").optional(),
  "top_k": z.number().int().describe("An integer that's used to limit the number of choices for the next predicted word or token. It specifies the maximum number of tokens to consider at each step, based on their probability of occurrence. This technique helps to speed up the generation process and can improve the quality of the generated text by focusing on the most likely options.").optional(),
  "repetition_penalty": z.number().describe("A number that controls the diversity of generated text by reducing the likelihood of repeated sequences. Higher values decrease repetition.").optional(),
  "stream": z.boolean().describe("If true, stream tokens as Server-Sent Events as the model generates them instead of waiting for the full model response. The stream terminates with `data: [DONE]`. If false, return a single JSON object containing the results.").optional(),
  "logprobs": z.number().int().gte(0).lte(1).describe("Integer (0 or 1) that controls whether log probabilities of generated tokens are returned. Log probabilities help assess model confidence in token predictions.").optional(),
  "echo": z.boolean().describe("If true, the response will contain the prompt. Can be used with `logprobs` to return prompt logprobs.").optional(),
  "n": z.number().int().gte(1).lte(128).describe("The number of completions to generate for each prompt.").optional(),
  "safety_model": z.union([z.literal("Meta-Llama/Llama-Guard-7b"), z.string()]).describe("The name of the moderation model used to validate tokens. Choose from the available moderation models found [here](https://docs.together.ai/docs/inference-models#moderation-models).").optional(),
  "min_p": z.number().describe("A number between 0 and 1 that can be used as an alternative to top-p and top-k.").optional(),
  "presence_penalty": z.number().describe("A number between -2.0 and 2.0 where a positive value increases the likelihood of a model talking about new topics.").optional(),
  "frequency_penalty": z.number().describe("A number between -2.0 and 2.0 where a positive value decreases the likelihood of repeating tokens that have already been mentioned.").optional(),
  "logit_bias": z.record(z.any()).describe("<llm-instruction>This part of the input schema is truncated. If you want to pass the property `logit_bias` to the tool, first call the tool `expandSchema` with \"/properties/logit_bias\" in the list of pointers. This will return the expanded input schema which you can then use in the tool call. You may have to call `expandSchema` multiple times if the schema is nested.</llm-instruction>\n<property-description>Adjusts the likelihood of specific tokens appearing in the generated output.</property-description>").optional(),
  "seed": z.number().int().describe("Seed value for reproducibility.").optional()
}