import { z } from "zod"

export const toolName = `put_orders_orderid_deliverystate_driverassigned`
export const toolDescription = `Update order with driver assigned details`
export const baseUrl = `https://uk.api.just-eat.io`
export const path = `/orders/{orderId}/deliverystate/driverassigned`
export const method = `put`
export const security = []

export const inputParams = z.object({ "path": z.object({ "orderId": z.string().describe("Just Eat order identifier") }).optional(), "body": z.object({ "DriverContactNumber": z.string().describe("This should represent the driver's contact number.").optional(), "DriverName": z.string().describe("This should represent the driver's name.").optional(), "EtaAtDeliveryAddress": z.string().datetime({ offset: true }).describe("This should represent the delivery partner's best guess at when the driver will arrive at the delivery address.").optional(), "EtaAtRestaurant": z.string().datetime({ offset: true }).describe("This should represent the delivery partner's best guess at when the driver will arrive at the restaurant. In other words, it should not just contain the pick-up time initially requested by Just Eat.").optional(), "Location": z.object({ "Accuracy": z.number().describe("This should represent the accuracy of driver's location.").optional(), "Heading": z.number().describe("This should represent the degree of heading direction, for example, 0 is north, 90 is east.").optional(), "Latitude": z.number().describe("This should represent the latitude of the driver's location."), "Longitude": z.number().describe("This should represent the longitude of the driver's location."), "Speed": z.number().describe("This should represent the travel speed of the driver.").optional() }).describe("GeoLocation object containing latitude and longitude values.").optional(), "TimeStampWithUtcOffset": z.string().datetime({ offset: true }).describe("This should represent the driver assigned timestamp.").optional(), "VehicleDetails": z.object({ "Vehicle": z.string().optional(), "VehicleRegistration": z.string().optional() }).optional() }).optional() }).shape