import { z } from "zod"

export const inputParamsSchema = {
  "assigned_object_id": z.array(z.number().int()).optional(),
  "assigned_object_id__empty": z.boolean().optional(),
  "assigned_object_id__gt": z.array(z.number().int()).optional(),
  "assigned_object_id__gte": z.array(z.number().int()).optional(),
  "assigned_object_id__lt": z.array(z.number().int()).optional(),
  "assigned_object_id__lte": z.array(z.number().int()).optional(),
  "assigned_object_id__n": z.array(z.number().int()).optional(),
  "assigned_object_type": z.number().int().optional(),
  "assigned_object_type__n": z.number().int().optional(),
  "created": z.array(z.string().datetime({ offset: true })).optional(),
  "created__empty": z.array(z.string().datetime({ offset: true })).optional(),
  "created__gt": z.array(z.string().datetime({ offset: true })).optional(),
  "created__gte": z.array(z.string().datetime({ offset: true })).optional(),
  "created__lt": z.array(z.string().datetime({ offset: true })).optional(),
  "created__lte": z.array(z.string().datetime({ offset: true })).optional(),
  "created__n": z.array(z.string().datetime({ offset: true })).optional(),
  "created_by_request": z.string().uuid().optional(),
  "description": z.array(z.string()).optional(),
  "description__empty": z.boolean().optional(),
  "description__ic": z.array(z.string()).optional(),
  "description__ie": z.array(z.string()).optional(),
  "description__iew": z.array(z.string()).optional(),
  "description__isw": z.array(z.string()).optional(),
  "description__n": z.array(z.string()).optional(),
  "description__nic": z.array(z.string()).optional(),
  "description__nie": z.array(z.string()).optional(),
  "description__niew": z.array(z.string()).optional(),
  "description__nisw": z.array(z.string()).optional(),
  "device": z.array(z.string()).optional(),
  "device_id": z.array(z.number().int()).optional(),
  "id": z.array(z.number().int()).optional(),
  "id__empty": z.boolean().optional(),
  "id__gt": z.array(z.number().int()).optional(),
  "id__gte": z.array(z.number().int()).optional(),
  "id__lt": z.array(z.number().int()).optional(),
  "id__lte": z.array(z.number().int()).optional(),
  "id__n": z.array(z.number().int()).optional(),
  "interface": z.array(z.string()).describe("Interface (name)").optional(),
  "interface__n": z.array(z.string()).describe("Interface (name)").optional(),
  "interface_id": z.array(z.number().int()).describe("Interface (ID)").optional(),
  "interface_id__n": z.array(z.number().int()).describe("Interface (ID)").optional(),
  "last_updated": z.array(z.string().datetime({ offset: true })).optional(),
  "last_updated__empty": z.array(z.string().datetime({ offset: true })).optional(),
  "last_updated__gt": z.array(z.string().datetime({ offset: true })).optional(),
  "last_updated__gte": z.array(z.string().datetime({ offset: true })).optional(),
  "last_updated__lt": z.array(z.string().datetime({ offset: true })).optional(),
  "last_updated__lte": z.array(z.string().datetime({ offset: true })).optional(),
  "last_updated__n": z.array(z.string().datetime({ offset: true })).optional(),
  "limit": z.number().int().describe("Number of results to return per page.").optional(),
  "mac_address": z.array(z.string()).optional(),
  "mac_address__ic": z.array(z.string()).optional(),
  "mac_address__ie": z.array(z.string()).optional(),
  "mac_address__iew": z.array(z.string()).optional(),
  "mac_address__isw": z.array(z.string()).optional(),
  "mac_address__n": z.array(z.string()).optional(),
  "mac_address__nic": z.array(z.string()).optional(),
  "mac_address__nie": z.array(z.string()).optional(),
  "mac_address__niew": z.array(z.string()).optional(),
  "mac_address__nisw": z.array(z.string()).optional(),
  "modified_by_request": z.string().uuid().optional(),
  "offset": z.number().int().describe("The initial index from which to return the results.").optional(),
  "ordering": z.string().describe("Which field to use when ordering the results.").optional(),
  "q": z.string().describe("Search").optional(),
  "tag": z.array(z.string()).optional(),
  "tag__n": z.array(z.string()).optional(),
  "tag_id": z.array(z.number().int()).optional(),
  "tag_id__n": z.array(z.number().int()).optional(),
  "updated_by_request": z.string().uuid().optional(),
  "virtual_machine": z.array(z.string()).optional(),
  "virtual_machine_id": z.array(z.number().int()).optional(),
  "vminterface": z.array(z.string()).describe("VM interface (name)").optional(),
  "vminterface__n": z.array(z.string()).describe("VM interface (name)").optional(),
  "vminterface_id": z.array(z.number().int()).describe("VM interface (ID)").optional(),
  "vminterface_id__n": z.array(z.number().int()).describe("VM interface (ID)").optional()
}