import { z } from "zod"

export const inputParamsSchema = {
  "boundStreamId": z.string().describe("This value uniquely identifies the live stream bound to the broadcast.").optional(),
  "boundStreamLastUpdateTimeMs": z.string().datetime({ offset: true }).describe("The date and time that the live stream referenced by boundStreamId was last updated.").optional(),
  "closedCaptionsType": z.enum(["closedCaptionsTypeUnspecified","closedCaptionsDisabled","closedCaptionsHttpPost","closedCaptionsEmbedded"]).optional(),
  "enableAutoStart": z.boolean().describe("This setting indicates whether auto start is enabled for this broadcast. The default value for this property is false. This setting can only be used by Events.").optional(),
  "enableAutoStop": z.boolean().describe("This setting indicates whether auto stop is enabled for this broadcast. The default value for this property is false. This setting can only be used by Events.").optional(),
  "enableContentEncryption": z.boolean().describe("This setting indicates whether YouTube should enable content encryption for the broadcast.").optional(),
  "enableDvr": z.boolean().describe("This setting determines whether viewers can access DVR controls while watching the video. DVR controls enable the viewer to control the video playback experience by pausing, rewinding, or fast forwarding content. The default value for this property is true. *Important:* You must set the value to true and also set the enableArchive property's value to true if you want to make playback available immediately after the broadcast ends.").optional(),
  "enableEmbed": z.boolean().describe("This setting indicates whether the broadcast video can be played in an embedded player. If you choose to archive the video (using the enableArchive property), this setting will also apply to the archived video.").optional(),
  "latencyPreference": z.enum(["latencyPreferenceUnspecified","normal","low","ultraLow"]).describe("If both this and enable_low_latency are set, they must match. LATENCY_NORMAL should match enable_low_latency=false LATENCY_LOW should match enable_low_latency=true LATENCY_ULTRA_LOW should have enable_low_latency omitted.").optional(),
  "mesh": z.string().describe("The mesh for projecting the video if projection is mesh. The mesh value must be a UTF-8 string containing the base-64 encoding of 3D mesh data that follows the Spherical Video V2 RFC specification for an mshp box, excluding the box size and type but including the following four reserved zero bytes for the version and flags.").optional(),
  "monitorStream": z.record(z.any()).describe("<llm-instruction>This part of the input schema is truncated. If you want to pass the property `monitorStream` to the tool, first call the tool `expandSchema` with \"/properties/contentDetails/properties/monitorStream\" in the list of pointers. This will return the expanded input schema which you can then use in the tool call. You may have to call `expandSchema` multiple times if the schema is nested.</llm-instruction>\n<property-description>The monitorStream object contains information about the monitor stream, which the broadcaster can use to review the event content before the broadcast stream is shown publicly.</property-description>").optional(),
  "projection": z.enum(["projectionUnspecified","rectangular","360","mesh"]).describe("The projection format of this broadcast. This defaults to rectangular.").optional(),
  "recordFromStart": z.boolean().describe("Automatically start recording after the event goes live. The default value for this property is true. *Important:* You must also set the enableDvr property's value to true if you want the playback to be available immediately after the broadcast ends. If you set this property's value to true but do not also set the enableDvr property to true, there may be a delay of around one day before the archived video will be available for playback.").optional(),
  "startWithSlate": z.boolean().describe("This setting indicates whether the broadcast should automatically begin with an in-stream slate when you update the broadcast's status to live. After updating the status, you then need to send a liveCuepoints.insert request that sets the cuepoint's eventState to end to remove the in-stream slate and make your broadcast stream visible to viewers.").optional(),
  "stereoLayout": z.enum(["stereoLayoutUnspecified","mono","leftRight","topBottom"]).describe("The 3D stereo layout of this broadcast. This defaults to mono.").optional()
}