import { inputParamsSchema } from "./schema/root.js"
import type { OpenMCPServerTool } from "@open-mcp/core"

const tool: OpenMCPServerTool = {
  "toolName": "contents_create",
  "toolDescription": "",
  "baseUrl": "https://api.sporkbos.com",
  "path": "/api/contents/",
  "method": "post",
  "security": [
    {
      "key": "Authorization",
      "value": "Bearer <mcp-env-var>API_KEY</mcp-env-var>",
      "in": "header",
      "envVarName": "API_KEY"
    }
  ],
  "paramsMap": {
    "body": {
      "id": "id",
      "created_by": "created_by",
      "updated_by": "updated_by",
      "deleted_by": "deleted_by",
      "ulid": "ulid",
      "created_at": "created_at",
      "updated_at": "updated_at",
      "deleted_at": "deleted_at",
      "content_pages": "content_pages",
      "children": "children",
      "files": "files",
      "is_favourite": "is_favourite",
      "mark_children_complete": "mark_children_complete",
      "mark_children_cancel": "mark_children_cancel",
      "owner_data": "owner_data",
      "collaborators": "collaborators",
      "parent_data": "parent_data",
      "category_name": "category_name",
      "latest_result": "latest_result",
      "metric_collaborators_details": "metric_collaborators_details",
      "name": "name",
      "description": "description",
      "stage": "stage",
      "content_type": "content_type",
      "start_date": "start_date",
      "due_date": "due_date",
      "id_number": "id_number",
      "priority": "priority",
      "urgency": "urgency",
      "importance": "importance",
      "status": "status",
      "progress": "progress",
      "pace": "pace",
      "skill": "skill",
      "knowledge_level": "knowledge_level",
      "difficulty_level": "difficulty_level",
      "hours": "hours",
      "frequency": "frequency",
      "workload": "workload",
      "views": "views",
      "guide_type": "guide_type",
      "flag": "flag",
      "visibility": "visibility",
      "ignore_in_performance": "ignore_in_performance",
      "required_all_learn": "required_all_learn",
      "can_self_learn": "can_self_learn",
      "is_template": "is_template",
      "is_deleted": "is_deleted",
      "recurring_type": "recurring_type",
      "recurring_interval": "recurring_interval",
      "version": "version",
      "is_full_day": "is_full_day",
      "unit_of_measure": "unit_of_measure",
      "calculation": "calculation",
      "result_accuracy": "result_accuracy",
      "timeframe": "timeframe",
      "orientation": "orientation",
      "metric_status": "metric_status",
      "ceiling": "ceiling",
      "high": "high",
      "target": "target",
      "medium": "medium",
      "low": "low",
      "floor": "floor",
      "team": "team",
      "owner": "owner",
      "board": "board",
      "parent": "parent",
      "performance_type": "performance_type",
      "content_category": "content_category",
      "collaborators_users": "collaborators_users",
      "collaborators_groups": "collaborators_groups",
      "collaborators_positions": "collaborators_positions",
      "shared_users": "shared_users",
      "shared_groups": "shared_groups",
      "required_positions_learn": "required_positions_learn",
      "tags": "tags",
      "linked_contents": "linked_contents",
      "shared_positions": "shared_positions",
      "related_contents": "related_contents",
      "metric_shared_users": "metric_shared_users",
      "metric_shared_groups": "metric_shared_groups",
      "metric_shared_positions": "metric_shared_positions"
    }
  },
  inputParamsSchema
}

export default tool