import { inputParamsSchema } from "./schema/root.js"
import type { OpenMCPServerTool } from "@open-mcp/core"

const tool: OpenMCPServerTool = {
  "toolName": "updatecontract",
  "toolDescription": "Update contract",
  "baseUrl": "https://agepyme.finutive.com/api/",
  "path": "/businesses/{business_id}/laboral/contracts/{contract_id}",
  "method": "put",
  "security": [
    {
      "key": "wzu",
      "value": "<mcp-env-var>WZU</mcp-env-var>",
      "in": "cookie",
      "envVarName": "WZU"
    }
  ],
  "paramsMap": {
    "path": {
      "business_id": "business_id",
      "contract_id": "contract_id"
    },
    "body": {
      "user_id": "user_id",
      "modification_process": "modification_process",
      "automate_payroll": "automate_payroll",
      "date_contract": "date_contract",
      "birthdate": "birthdate",
      "title_date": "title_date",
      "seeker_date": "seeker_date",
      "start_date": "start_date",
      "end_date": "end_date",
      "replaces_to_limit_date": "replaces_to_limit_date",
      "hour": "hour",
      "number_social_security": "number_social_security",
      "dni": "dni",
      "firstname": "firstname",
      "surname1": "surname1",
      "surname2": "surname2",
      "previously_worked_company": "previously_worked_company",
      "origin_city": "origin_city",
      "origin_province": "origin_province",
      "civil_status": "civil_status",
      "nationality": "nationality",
      "number_children": "number_children",
      "address": "address",
      "zip": "zip",
      "population": "population",
      "province": "province",
      "country": "country",
      "phone": "phone",
      "mobile_phone": "mobile_phone",
      "email": "email",
      "iban": "iban",
      "title": "title",
      "job_functions": "job_functions",
      "category": "category",
      "business_name": "business_name",
      "hours": "hours",
      "hours_definition": "hours_definition",
      "hours_by_days": "hours_by_days",
      "days": "days",
      "replaces_to_person": "replaces_to_person",
      "replaces_affiliation_number": "replaces_affiliation_number",
      "replaces_cause": "replaces_cause",
      "observations": "observations",
      "job_seeker": "job_seeker",
      "youth_guarantee_fund": "youth_guarantee_fund",
      "salary": "salary",
      "contract_type": "contract_type",
      "contract_reason": "contract_reason",
      "work_in_weekend": "work_in_weekend",
      "notify_minimum_salary": "notify_minimum_salary",
      "account": "account",
      "time_offset": "time_offset",
      "trial_period": "trial_period",
      "trial_period_condition": "trial_period_condition",
      "number_payments": "number_payments",
      "number_payments_condition": "number_payments_condition",
      "headquarter": "headquarter",
      "irpf_worker": "irpf_worker",
      "irpf_perceived": "irpf_perceived",
      "irpf_retained": "irpf_retained",
      "project_details": "project_details",
      "extra_remuneration_concepts": "extra_remuneration_concepts",
      "dni_or_nif": "dni_or_nif",
      "detailed_timetable": "detailed_timetable",
      "dni_files": "dni_files",
      "academic_files": "academic_files",
      "bank_files": "bank_files",
      "model145": "model145",
      "signed_contract": "signed_contract",
      "last_payrolls": "last_payrolls",
      "scholarship_files": "scholarship_files",
      "attached_scholarship_files": "attached_scholarship_files",
      "create_flow": "create_flow"
    }
  },
  inputParamsSchema
}

export default tool