import { z } from "zod"

export const inputParams = {
  "alerts": z.record(z.any()).describe("<llm-instruction>This part of the input schema is truncated. If you want to pass the property `alerts` to the tool, first call the tool `expandSchema` with \"/properties/alerts\" in the list of pointers. This will return the expanded input schema which you can then use in the tool call. You may have to call `expandSchema` multiple times if the schema is nested.</llm-instruction>").optional(),
  "backups": z.record(z.any()).describe("<llm-instruction>This part of the input schema is truncated. If you want to pass the property `backups` to the tool, first call the tool `expandSchema` with \"/properties/backups\" in the list of pointers. This will return the expanded input schema which you can then use in the tool call. You may have to call `expandSchema` multiple times if the schema is nested.</llm-instruction>\n<property-description>Information about this Linode's backups status. For information about available backups, run [List backups](https://techdocs.akamai.com/linode-api/reference/get-backups).</property-description>").optional(),
  "capabilities": z.array(z.string()).describe("__Limited availability__, __Read-only__ A list of capabilities this compute instance supports.").readonly().optional(),
  "created": z.string().datetime({ offset: true }).describe("__Read-only__ When this Linode was created.").readonly().optional(),
  "disk_encryption": z.string().nullable().describe("__Limited availability__, __Read-only__ Indicates the local disk encryption setting for this Linode. If the Linode is part of an LKE cluster, the value is `null`.").readonly().optional(),
  "has_user_data": z.boolean().describe("__Read-only__ Whether this compute instance was provisioned with `user_data` provided via the Metadata service. See the [Create a Linode](https://techdocs.akamai.com/linode-api/reference/post-linode-instance) description for more information on Metadata.").readonly().optional(),
  "host_uuid": z.string().uuid().describe("__Read-only__ The Linode's host machine, as a UUID.").readonly().optional(),
  "hypervisor": z.literal("kvm").describe("__Read-only__ The virtualization software powering this Linode.").readonly().optional(),
  "id": z.number().int().describe("__Filterable__, __Read-only__ This Linode's ID which must be provided for all operations impacting this Linode.").readonly().optional(),
  "image": z.string().optional(),
  "ipv4": z.array(z.string()).describe("__Filterable__, __Read-only__ This Linode's IPv4 Addresses. Each Linode is assigned a single public IPv4 address upon creation, and may get a single private IPv4 address if needed. You may need to [Open a support ticket](https://techdocs.akamai.com/linode-api/reference/post-ticket) to get additional IPv4 addresses.\n\nIPv4 addresses may be reassigned between your Linodes, or shared with other Linodes. See the [networking](https://techdocs.akamai.com/linode-api/reference/post-firewalls) operations for details.").readonly().optional(),
  "ipv6": z.string().nullable().describe("__Read-only__ This Linode's IPv6 SLAAC address. This address is specific to a Linode, and may not be shared. If the Linode has not been assigned an IPv6 address, the return value will be `null`.").readonly().optional(),
  "label": z.string().regex(new RegExp("^[a-zA-Z]((?!--|__|\\.\\.)[a-zA-Z0-9-_.])+$")).min(3).max(64).describe("__Filterable__ Provides a name for the Linode. If not provided, the API generates one for it.\n\nLinode labels have the following constraints:\n\n- It needs to begin and end with an alphanumeric character.\n- It can only consist of alphanumeric characters, hyphens (`-`), underscores (`_`) or periods (`.`).\n- Cannot have two hyphens (`--`), underscores (`__`) or periods (`..`) in a row.").optional(),
  "lke_cluster_id": z.number().int().nullable().describe("__Read-only__ The ID of the Kubernetes cluster if the Linode is part of cluster.").readonly().optional(),
  "placement_group": z.record(z.any()).describe("<llm-instruction>This part of the input schema is truncated. If you want to pass the property `placement_group` to the tool, first call the tool `expandSchema` with \"/properties/placement_group\" in the list of pointers. This will return the expanded input schema which you can then use in the tool call. You may have to call `expandSchema` multiple times if the schema is nested.</llm-instruction>\n<property-description>__Read-only__ Details on the [placement group](https://www.linode.com/docs/products/compute/compute-instances/guides/placement-groups/) that this Linode belongs to. Empty if the Linode isn't in a placement group.</property-description>").optional(),
  "region": z.string().describe("__Filterable__, __Read-only__ The [region](https://techdocs.akamai.com/linode-api/reference/get-regions) where the Linode deployed. A Linode's region can only be changed by initiating a [cross data center migration](https://techdocs.akamai.com/linode-api/reference/post-migrate-linode-instance).").readonly().optional(),
  "specs": z.record(z.any()).describe("<llm-instruction>This part of the input schema is truncated. If you want to pass the property `specs` to the tool, first call the tool `expandSchema` with \"/properties/specs\" in the list of pointers. This will return the expanded input schema which you can then use in the tool call. You may have to call `expandSchema` multiple times if the schema is nested.</llm-instruction>\n<property-description>__Read-only__ Information about the resources available to this Linode.</property-description>").optional(),
  "status": z.enum(["running","offline","booting","busy","rebooting","shutting_down","provisioning","deleting","migrating","rebuilding","cloning","restoring","stopped","billing_suspension"]).describe("__Read-only__ A brief description of this Linode's current state. This field may change without direct action from you. For example, when a compute instance goes into maintenance mode, its status is `stopped`. Status is generally self-explanatory, based on its name.\n\n- `busy` indicates you've assigned the compute instance to a [placement group](https://techdocs.akamai.com/cloud-computing/docs/work-with-placement-groups), but the compute instance is currently booting. Once the boot completes, the API completes the assignment and updates the compute instance's `status` accordingly.\n- `provisioning` indicates that the API is applying operating system or Marketplace applications on the compute instance.\n- `billing_suspension` indicates that payment is past due on the compute instance, so we've suspended its use.").readonly().optional(),
  "tags": z.array(z.string()).describe("__Filterable__ Tags to help you organize your content.").optional(),
  "type": z.string().describe("__Read-only__ This is the [Linode type](https://techdocs.akamai.com/linode-api/reference/get-linode-types) that this Linode was deployed with. To change a Linode's type, use [Resize a Linode](https://techdocs.akamai.com/linode-api/reference/post-resize-linode-instance).").readonly().optional(),
  "updated": z.string().datetime({ offset: true }).describe("__Read-only__ When this Linode was last updated.").readonly().optional(),
  "watchdog_enabled": z.boolean().describe("The watchdog, named Lassie, is a Shutdown Watchdog that monitors your Linode and reboots it if it powers off unexpectedly. It works by issuing a boot job when your Linode powers off without a shutdown job being responsible. To prevent a loop, Lassie gives up if there have been more than 5 boot jobs issued within 15 minutes.").optional()
}