import { z } from "zod"

export const inputParamsSchema = {
  "editorSuggestionsAvailability": z.string().describe("This value indicates whether video editing suggestions, which might improve video quality or the playback experience, are available for the video. You can retrieve these suggestions by requesting the suggestions part in your videos.list() request.").optional(),
  "fileDetailsAvailability": z.string().describe("This value indicates whether file details are available for the uploaded video. You can retrieve a video's file details by requesting the fileDetails part in your videos.list() request.").optional(),
  "processingFailureReason": z.enum(["uploadFailed","transcodeFailed","streamingFailed","other"]).describe("The reason that YouTube failed to process the video. This property will only have a value if the processingStatus property's value is failed.").optional(),
  "processingIssuesAvailability": z.string().describe("This value indicates whether the video processing engine has generated suggestions that might improve YouTube's ability to process the the video, warnings that explain video processing problems, or errors that cause video processing problems. You can retrieve these suggestions by requesting the suggestions part in your videos.list() request.").optional(),
  "processingProgress": z.record(z.any()).describe("<llm-instruction>This part of the input schema is truncated. If you want to pass the property `processingProgress` to the tool, first call the tool `expandSchema` with \"/properties/processingDetails/properties/processingProgress\" in the list of pointers. This will return the expanded input schema which you can then use in the tool call. You may have to call `expandSchema` multiple times if the schema is nested.</llm-instruction>\n<property-description>The processingProgress object contains information about the progress YouTube has made in processing the video. The values are really only relevant if the video's processing status is processing.</property-description>").optional(),
  "processingStatus": z.enum(["processing","succeeded","failed","terminated"]).describe("The video's processing status. This value indicates whether YouTube was able to process the video or if the video is still being processed.").optional(),
  "tagSuggestionsAvailability": z.string().describe("This value indicates whether keyword (tag) suggestions are available for the video. Tags can be added to a video's metadata to make it easier for other users to find the video. You can retrieve these suggestions by requesting the suggestions part in your videos.list() request.").optional(),
  "thumbnailsAvailability": z.string().describe("This value indicates whether thumbnail images have been generated for the video.").optional()
}