import { z } from "zod"

export const inputParams = {
  "capabilities": z.array(z.string()).describe("__Read-only__ A list of the possible capabilities of this image.\n\n- `cloud-init`. The image supports the cloud-init multi-distribution method with our [Metadata service](https://www.linode.com/docs/products/compute/compute-instances/guides/metadata/#troubleshoot-metadata-and-cloud-init). This only applies to public images.\n\n- `distributed-sites`. Whether the image can be used in distributed compute regions. Compared to a core compute region, distributed compute regions offer limited functionality, but they're globally distributed. Your image can be geographically closer to you, potentially letting you deploy it quicker. See [Regions and images](https://techdocs.akamai.com/cloud-computing/docs/images#regions-and-images) for complete details.").readonly().optional(),
  "created": z.string().datetime({ offset: true }).describe("__Read-only__ When this image was created.").readonly().optional(),
  "created_by": z.string().describe("__Read-only__ The name of the user who created this image, or `linode` for public images.").readonly().optional(),
  "deprecated": z.boolean().describe("__Filterable__, __Read-only__ Whether this image is deprecated. Only public images can be deprecated.").readonly().optional(),
  "description": z.string().min(1).max(65000).nullable().describe("A detailed description of this image.").optional(),
  "eol": z.string().datetime({ offset: true }).nullable().describe("__Read-only__ The date of the public image's planned removal from service. This is `null` for private images.").readonly().optional(),
  "expiry": z.string().datetime({ offset: true }).nullable().describe("__Read-only__ Only images created automatically from a deleted compute instance (type=automatic) expire. This is `null` for private images.").readonly().optional(),
  "id": z.string().describe("__Read-only__ The unique identifier for each image.").readonly().optional(),
  "is_public": z.boolean().describe("__Filterable__, __Read-only__ Revealed as `true` if the image is a public distribution image. Private, account-specific images are listed as `false`.").readonly().optional(),
  "label": z.string().describe("__Filterable__ A short description of the image.").optional(),
  "regions": z.array(z.object({ "region": z.string().describe("The unique identifier for the core compute region where this image is stored.").optional(), "status": z.enum(["available","creating","pending","pending deletion","pending replication","replicating"]).describe("The status of the image in this `region`. Possible values are `available`, `creating`, `pending`, `pending deletion`, `pending replication`, or `replicating`.").optional() }).strict()).describe("__Read-only__ Details on the regions where this image is stored. See [Regions and images](https://techdocs.akamai.com/cloud-computing/docs/images#regions-and-images) for full details on support for `regions`.").readonly().optional(),
  "size": z.number().int().describe("__Filterable__, __Read-only__ The minimum size in MB this image needs to deploy.").readonly().optional(),
  "status": z.enum(["creating","pending_upload","available"]).describe("__Filterable__, __Read-only__ The current status of the image. Possible values are `available`, `creating`, and `pending_upload`.\n\n> 📘\n>\n> The `+order_by` and `+order` operators are not available when [filtering](https://techdocs.akamai.com/linode-api/reference/filtering-and-sorting) on this key.").readonly().optional(),
  "tags": z.array(z.string().min(3).max(100)).min(0).max(500).describe("__Filterable__ Tags used for organizational purposes. A tag can be from 3 to 100 characters long, and an image can have a maximum of 500 total tags.").optional(),
  "total_size": z.number().int().describe("__Read-only__ The total size in bytes of all instances of this image, in all `regions`.\n\n> 📘\n>\n> This object is empty for existing images. It's intended for use with future functionality.").readonly().optional(),
  "type": z.enum(["manual","automatic"]).describe("__Filterable__, __Read-only__ How the image was created. Create a `manual` image at any time. An `automatic` image is created automatically from a deleted compute instance.").readonly().optional(),
  "updated": z.string().datetime({ offset: true }).describe("__Read-only__ When this image was last updated.").readonly().optional(),
  "vendor": z.string().nullable().describe("__Filterable__, __Read-only__ The upstream distribution vendor. This is `null` for private images.").readonly().optional()
}