import { z } from "zod"

export const inputParamsSchema = {
  "keywords": z.enum(["asc","desc"]).describe("Total number of keywords.").optional(),
  "traff": z.enum(["asc","desc"]).describe("Traffic generated by the keywords.").optional(),
  "visible": z.enum(["asc","desc"]).describe("Visibility score.").optional(),
  "visible_static": z.enum(["asc","desc"]).describe("Static visibility.").optional(),
  "new_keywords": z.enum(["asc","desc"]).describe("Number of newly discovered keywords.").optional(),
  "out_keywords": z.enum(["asc","desc"]).describe("Number of keywords that dropped out.").optional(),
  "rised_keywords": z.enum(["asc","desc"]).describe("Number of keywords that increased in rank.").optional(),
  "down_keywords": z.enum(["asc","desc"]).describe("Number of keywords that decreased in rank.").optional(),
  "ad_keywords": z.enum(["asc","desc"]).describe("Number of keywords used in paid ads.").optional(),
  "ads": z.enum(["asc","desc"]).describe("Number of ads.").optional(),
  "date": z.enum(["asc","desc"]).describe("Date of the data entry.").optional()
}