import { z } from "zod"

export const inputParamsSchema = {
  "created": z.array(z.string().datetime({ offset: true })).optional(),
  "created__empty": z.array(z.string().datetime({ offset: true })).optional(),
  "created__gt": z.array(z.string().datetime({ offset: true })).optional(),
  "created__gte": z.array(z.string().datetime({ offset: true })).optional(),
  "created__lt": z.array(z.string().datetime({ offset: true })).optional(),
  "created__lte": z.array(z.string().datetime({ offset: true })).optional(),
  "created__n": z.array(z.string().datetime({ offset: true })).optional(),
  "created_by_request": z.string().uuid().optional(),
  "description": z.array(z.string()).optional(),
  "description__empty": z.boolean().optional(),
  "description__ic": z.array(z.string()).optional(),
  "description__ie": z.array(z.string()).optional(),
  "description__iew": z.array(z.string()).optional(),
  "description__isw": z.array(z.string()).optional(),
  "description__n": z.array(z.string()).optional(),
  "description__nic": z.array(z.string()).optional(),
  "description__nie": z.array(z.string()).optional(),
  "description__niew": z.array(z.string()).optional(),
  "description__nisw": z.array(z.string()).optional(),
  "exporting_l2vpn": z.array(z.number().int().gte(-9223372036854776000).lte(9223372036854776000).nullable()).describe("Exporting L2VPN (identifier)").optional(),
  "exporting_l2vpn__n": z.array(z.number().int().gte(-9223372036854776000).lte(9223372036854776000).nullable()).describe("Exporting L2VPN (identifier)").optional(),
  "exporting_l2vpn_id": z.array(z.number().int()).describe("Exporting L2VPN").optional(),
  "exporting_l2vpn_id__n": z.array(z.number().int()).describe("Exporting L2VPN").optional(),
  "exporting_vrf": z.array(z.string().nullable()).describe("Export VRF (RD)").optional(),
  "exporting_vrf__n": z.array(z.string().nullable()).describe("Export VRF (RD)").optional(),
  "exporting_vrf_id": z.array(z.number().int()).describe("Exporting VRF").optional(),
  "exporting_vrf_id__n": z.array(z.number().int()).describe("Exporting VRF").optional(),
  "id": z.array(z.number().int()).optional(),
  "id__empty": z.boolean().optional(),
  "id__gt": z.array(z.number().int()).optional(),
  "id__gte": z.array(z.number().int()).optional(),
  "id__lt": z.array(z.number().int()).optional(),
  "id__lte": z.array(z.number().int()).optional(),
  "id__n": z.array(z.number().int()).optional(),
  "importing_l2vpn": z.array(z.number().int().gte(-9223372036854776000).lte(9223372036854776000).nullable()).describe("Importing L2VPN (identifier)").optional(),
  "importing_l2vpn__n": z.array(z.number().int().gte(-9223372036854776000).lte(9223372036854776000).nullable()).describe("Importing L2VPN (identifier)").optional(),
  "importing_l2vpn_id": z.array(z.number().int()).describe("Importing L2VPN").optional(),
  "importing_l2vpn_id__n": z.array(z.number().int()).describe("Importing L2VPN").optional(),
  "importing_vrf": z.array(z.string().nullable()).describe("Import VRF (RD)").optional(),
  "importing_vrf__n": z.array(z.string().nullable()).describe("Import VRF (RD)").optional(),
  "importing_vrf_id": z.array(z.number().int()).describe("Importing VRF").optional(),
  "importing_vrf_id__n": z.array(z.number().int()).describe("Importing VRF").optional(),
  "last_updated": z.array(z.string().datetime({ offset: true })).optional(),
  "last_updated__empty": z.array(z.string().datetime({ offset: true })).optional(),
  "last_updated__gt": z.array(z.string().datetime({ offset: true })).optional(),
  "last_updated__gte": z.array(z.string().datetime({ offset: true })).optional(),
  "last_updated__lt": z.array(z.string().datetime({ offset: true })).optional(),
  "last_updated__lte": z.array(z.string().datetime({ offset: true })).optional(),
  "last_updated__n": z.array(z.string().datetime({ offset: true })).optional(),
  "limit": z.number().int().describe("Number of results to return per page.").optional(),
  "modified_by_request": z.string().uuid().optional(),
  "name": z.array(z.string()).optional(),
  "name__empty": z.boolean().optional(),
  "name__ic": z.array(z.string()).optional(),
  "name__ie": z.array(z.string()).optional(),
  "name__iew": z.array(z.string()).optional(),
  "name__isw": z.array(z.string()).optional(),
  "name__n": z.array(z.string()).optional(),
  "name__nic": z.array(z.string()).optional(),
  "name__nie": z.array(z.string()).optional(),
  "name__niew": z.array(z.string()).optional(),
  "name__nisw": z.array(z.string()).optional(),
  "offset": z.number().int().describe("The initial index from which to return the results.").optional(),
  "ordering": z.string().describe("Which field to use when ordering the results.").optional(),
  "q": z.string().describe("Search").optional(),
  "tag": z.array(z.string()).optional(),
  "tag__n": z.array(z.string()).optional(),
  "tag_id": z.array(z.number().int()).optional(),
  "tag_id__n": z.array(z.number().int()).optional(),
  "tenant": z.array(z.string()).describe("Tenant (slug)").optional(),
  "tenant__n": z.array(z.string()).describe("Tenant (slug)").optional(),
  "tenant_group": z.array(z.string()).optional(),
  "tenant_group__n": z.array(z.string()).optional(),
  "tenant_group_id": z.array(z.string()).optional(),
  "tenant_group_id__n": z.array(z.string()).optional(),
  "tenant_id": z.array(z.number().int().nullable()).describe("Tenant (ID)").optional(),
  "tenant_id__n": z.array(z.number().int().nullable()).describe("Tenant (ID)").optional(),
  "updated_by_request": z.string().uuid().optional()
}