import { z } from "zod"

export const inputParamsSchema = {
  "UseCaseId": z.string().uuid().describe("UseCaseId").optional(),
  "ExternalId": z.string().describe("Unique ExternalId generated by the external system").optional(),
  "FileName": z.string().describe("Name of the file").optional(),
  "LastUpdateDate": z.string().datetime({ offset: true }).describe("Date of the last update of the file").optional(),
  "FileContent": z.string().base64().describe("IFormFile with content of the file").optional(),
  "ProcessInBulk": z.boolean().describe("Flag to process in bulk").optional()
}