import { inputParamsSchema } from "./schema/root.js"
import type { OpenMCPServerTool } from "@open-mcp/core"

const tool: OpenMCPServerTool = {
  "toolName": "core_data_sources_list",
  "toolDescription": "Get a list of data source objects.",
  "baseUrl": "https://api.example.com",
  "path": "/api/core/data-sources/",
  "method": "get",
  "security": [
    {
      "key": "sessionid",
      "value": "<mcp-env-var>SESSIONID</mcp-env-var>",
      "in": "cookie",
      "envVarName": "SESSIONID"
    },
    {
      "key": "Authorization",
      "value": "<mcp-env-var>AUTHORIZATION</mcp-env-var>",
      "in": "header",
      "envVarName": "AUTHORIZATION"
    }
  ],
  "paramsMap": {
    "query": {
      "created": "created",
      "created__empty": "created__empty",
      "created__gt": "created__gt",
      "created__gte": "created__gte",
      "created__lt": "created__lt",
      "created__lte": "created__lte",
      "created__n": "created__n",
      "created_by_request": "created_by_request",
      "description": "description",
      "description__empty": "description__empty",
      "description__ic": "description__ic",
      "description__ie": "description__ie",
      "description__iew": "description__iew",
      "description__isw": "description__isw",
      "description__n": "description__n",
      "description__nic": "description__nic",
      "description__nie": "description__nie",
      "description__niew": "description__niew",
      "description__nisw": "description__nisw",
      "enabled": "enabled",
      "id": "id",
      "id__empty": "id__empty",
      "id__gt": "id__gt",
      "id__gte": "id__gte",
      "id__lt": "id__lt",
      "id__lte": "id__lte",
      "id__n": "id__n",
      "last_synced": "last_synced",
      "last_synced__empty": "last_synced__empty",
      "last_synced__gt": "last_synced__gt",
      "last_synced__gte": "last_synced__gte",
      "last_synced__lt": "last_synced__lt",
      "last_synced__lte": "last_synced__lte",
      "last_synced__n": "last_synced__n",
      "last_updated": "last_updated",
      "last_updated__empty": "last_updated__empty",
      "last_updated__gt": "last_updated__gt",
      "last_updated__gte": "last_updated__gte",
      "last_updated__lt": "last_updated__lt",
      "last_updated__lte": "last_updated__lte",
      "last_updated__n": "last_updated__n",
      "limit": "limit",
      "modified_by_request": "modified_by_request",
      "name": "name",
      "name__empty": "name__empty",
      "name__ic": "name__ic",
      "name__ie": "name__ie",
      "name__iew": "name__iew",
      "name__isw": "name__isw",
      "name__n": "name__n",
      "name__nic": "name__nic",
      "name__nie": "name__nie",
      "name__niew": "name__niew",
      "name__nisw": "name__nisw",
      "offset": "offset",
      "ordering": "ordering",
      "q": "q",
      "source_url": "source_url",
      "source_url__empty": "source_url__empty",
      "source_url__ic": "source_url__ic",
      "source_url__ie": "source_url__ie",
      "source_url__iew": "source_url__iew",
      "source_url__isw": "source_url__isw",
      "source_url__n": "source_url__n",
      "source_url__nic": "source_url__nic",
      "source_url__nie": "source_url__nie",
      "source_url__niew": "source_url__niew",
      "source_url__nisw": "source_url__nisw",
      "status": "status",
      "status__empty": "status__empty",
      "status__ic": "status__ic",
      "status__ie": "status__ie",
      "status__iew": "status__iew",
      "status__isw": "status__isw",
      "status__n": "status__n",
      "status__nic": "status__nic",
      "status__nie": "status__nie",
      "status__niew": "status__niew",
      "status__nisw": "status__nisw",
      "sync_interval": "sync_interval",
      "sync_interval__ic": "sync_interval__ic",
      "sync_interval__ie": "sync_interval__ie",
      "sync_interval__iew": "sync_interval__iew",
      "sync_interval__isw": "sync_interval__isw",
      "sync_interval__n": "sync_interval__n",
      "sync_interval__nic": "sync_interval__nic",
      "sync_interval__nie": "sync_interval__nie",
      "sync_interval__niew": "sync_interval__niew",
      "sync_interval__nisw": "sync_interval__nisw",
      "tag": "tag",
      "tag__n": "tag__n",
      "tag_id": "tag_id",
      "tag_id__n": "tag_id__n",
      "type": "type",
      "type__empty": "type__empty",
      "type__ic": "type__ic",
      "type__ie": "type__ie",
      "type__iew": "type__iew",
      "type__isw": "type__isw",
      "type__n": "type__n",
      "type__nic": "type__nic",
      "type__nie": "type__nie",
      "type__niew": "type__niew",
      "type__nisw": "type__nisw",
      "updated_by_request": "updated_by_request"
    }
  },
  inputParamsSchema
}

export default tool