import { z } from "zod"

export const inputParamsSchema = {
  "client_id": z.string().describe("Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header or as part of a request body.").optional(),
  "secret": z.string().describe("Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part of a request body.").optional(),
  "start_date": z.string().datetime({ offset: true }).nullable().describe("The start datetime of transfers to list. This should be in RFC 3339 format (i.e. `2019-12-06T22:35:49Z`)").optional(),
  "end_date": z.string().datetime({ offset: true }).nullable().describe("The end datetime of transfers to list. This should be in RFC 3339 format (i.e. `2019-12-06T22:35:49Z`)").optional(),
  "transfer_id": z.string().nullable().describe("Plaid’s unique identifier for a transfer.").optional(),
  "account_id": z.string().nullable().describe("The account ID to get events for all transactions to/from an account.").optional(),
  "transfer_type": z.union([z.literal("debit"), z.literal("credit"), z.literal(null)]).nullable().describe("The type of transfer. This will be either `debit` or `credit`.  A `debit` indicates a transfer of money into your origination account; a `credit` indicates a transfer of money out of your origination account.").optional(),
  "event_types": z.array(z.enum(["pending","cancelled","failed","posted","settled","funds_available","returned","swept","swept_settled","return_swept","sweep.pending","sweep.posted","sweep.settled","sweep.returned","sweep.failed","sweep.funds_available","refund.pending","refund.cancelled","refund.failed","refund.posted","refund.settled","refund.returned","refund.swept","refund.return_swept"]).describe("The type of event that this transfer represents. Event types with prefix `sweep` represents events for Plaid Ledger sweeps.\n\n`pending`: A new transfer was created; it is in the pending state.\n\n`cancelled`: The transfer was cancelled by the client.\n\n`failed`: The transfer failed, no funds were moved.\n\n`posted`: The transfer has been successfully submitted to the payment network.\n\n`settled`: The transfer has been successfully completed by the payment network.\n\n`funds_available`: Funds from the transfer have been released from hold and applied to the ledger's available balance. (Only applicable to ACH debits.)\n\n`returned`: A posted transfer was returned.\n\n`swept`: The transfer was swept to / from the sweep account.\n\n`swept_settled`: Credits are available to be withdrawn or debits have been deducted from the customer’s business checking account.\n\n`return_swept`: Due to the transfer being returned, funds were pulled from or pushed back to the sweep account.\n\n`sweep.pending`: A new ledger sweep was created; it is in the pending state.\n\n`sweep.posted`: The ledger sweep has been successfully submitted to the payment network.\n\n`sweep.settled`: The transaction has settled in the funding account. This means that funds withdrawn from Plaid Ledger balance have reached the funding account, or funds to be deposited into the Plaid Ledger Balance have been pulled, and the hold period has begun.\n\n`sweep.returned`: A posted ledger sweep was returned.\n\n`sweep.failed`: The ledger sweep failed, no funds were moved.\n\n`sweep.funds_available`: Funds from the ledger sweep have been released from hold and applied to the ledger's available balance. This is only applicable to debits.\n\n`refund.pending`: A new refund was created; it is in the pending state.\n\n`refund.cancelled`: The refund was cancelled.\n\n`refund.failed`: The refund failed, no funds were moved.\n\n`refund.posted`: The refund has been successfully submitted to the payment network.\n\n`refund.settled`: The refund transaction has settled in the Plaid linked account.\n\n`refund.returned`: A posted refund was returned.\n\n`refund.swept`: The refund was swept from the sweep account.\n\n`refund.return_swept`: Due to the refund being returned, funds were pushed back to the sweep account.")).describe("Filter events by event type.").optional(),
  "sweep_id": z.string().describe("Plaid’s unique identifier for a sweep.").optional(),
  "count": z.number().int().gte(1).lte(25).nullable().describe("The maximum number of transfer events to return. If the number of events matching the above parameters is greater than `count`, the most recent events will be returned.").optional(),
  "offset": z.number().int().gte(0).nullable().describe("The offset into the list of transfer events. When `count`=25 and `offset`=0, the first 25 events will be returned. When `count`=25 and `offset`=25, the next 25 events will be returned.").optional(),
  "originator_client_id": z.string().nullable().describe("Filter transfer events to only those with the specified originator client.").optional(),
  "funding_account_id": z.string().nullable().describe("Filter transfer events to only those with the specified `funding_account_id`.").optional()
}