import { inputParamsSchema } from "./schema/root.js"
import type { OpenMCPServerTool } from "@open-mcp/core"

const tool: OpenMCPServerTool = {
  "toolName": "users_users_list",
  "toolDescription": "Get a list of user objects.",
  "baseUrl": "https://api.example.com",
  "path": "/api/users/users/",
  "method": "get",
  "security": [
    {
      "key": "sessionid",
      "value": "<mcp-env-var>SESSIONID</mcp-env-var>",
      "in": "cookie",
      "envVarName": "SESSIONID"
    },
    {
      "key": "Authorization",
      "value": "<mcp-env-var>AUTHORIZATION</mcp-env-var>",
      "in": "header",
      "envVarName": "AUTHORIZATION"
    }
  ],
  "paramsMap": {
    "query": {
      "date_joined": "date_joined",
      "date_joined__empty": "date_joined__empty",
      "date_joined__gt": "date_joined__gt",
      "date_joined__gte": "date_joined__gte",
      "date_joined__lt": "date_joined__lt",
      "date_joined__lte": "date_joined__lte",
      "date_joined__n": "date_joined__n",
      "email": "email",
      "email__empty": "email__empty",
      "email__ic": "email__ic",
      "email__ie": "email__ie",
      "email__iew": "email__iew",
      "email__isw": "email__isw",
      "email__n": "email__n",
      "email__nic": "email__nic",
      "email__nie": "email__nie",
      "email__niew": "email__niew",
      "email__nisw": "email__nisw",
      "first_name": "first_name",
      "first_name__empty": "first_name__empty",
      "first_name__ic": "first_name__ic",
      "first_name__ie": "first_name__ie",
      "first_name__iew": "first_name__iew",
      "first_name__isw": "first_name__isw",
      "first_name__n": "first_name__n",
      "first_name__nic": "first_name__nic",
      "first_name__nie": "first_name__nie",
      "first_name__niew": "first_name__niew",
      "first_name__nisw": "first_name__nisw",
      "group": "group",
      "group__n": "group__n",
      "group_id": "group_id",
      "group_id__n": "group_id__n",
      "id": "id",
      "id__empty": "id__empty",
      "id__gt": "id__gt",
      "id__gte": "id__gte",
      "id__lt": "id__lt",
      "id__lte": "id__lte",
      "id__n": "id__n",
      "is_active": "is_active",
      "is_staff": "is_staff",
      "is_superuser": "is_superuser",
      "last_login": "last_login",
      "last_login__empty": "last_login__empty",
      "last_login__gt": "last_login__gt",
      "last_login__gte": "last_login__gte",
      "last_login__lt": "last_login__lt",
      "last_login__lte": "last_login__lte",
      "last_login__n": "last_login__n",
      "last_name": "last_name",
      "last_name__empty": "last_name__empty",
      "last_name__ic": "last_name__ic",
      "last_name__ie": "last_name__ie",
      "last_name__iew": "last_name__iew",
      "last_name__isw": "last_name__isw",
      "last_name__n": "last_name__n",
      "last_name__nic": "last_name__nic",
      "last_name__nie": "last_name__nie",
      "last_name__niew": "last_name__niew",
      "last_name__nisw": "last_name__nisw",
      "limit": "limit",
      "notification_group_id": "notification_group_id",
      "notification_group_id__n": "notification_group_id__n",
      "offset": "offset",
      "ordering": "ordering",
      "permission_id": "permission_id",
      "permission_id__n": "permission_id__n",
      "q": "q",
      "username": "username",
      "username__empty": "username__empty",
      "username__ic": "username__ic",
      "username__ie": "username__ie",
      "username__iew": "username__iew",
      "username__isw": "username__isw",
      "username__n": "username__n",
      "username__nic": "username__nic",
      "username__nie": "username__nie",
      "username__niew": "username__niew",
      "username__nisw": "username__nisw"
    }
  },
  inputParamsSchema
}

export default tool