import { z } from "zod"

export const inputParamsSchema = {
  "assocAssignedCode": z.string().optional(),
  "commonAccessRef": z.string().optional(),
  "controllingAgency": z.enum(["AA","AB","AC","AD","AE","CC","CE","EC","ED","EE","EN","ER","EU","EX","IA","KE","LI","OD","RI","RT","UN"]).optional(),
  "release": z.enum(["ODETTERELEASE_1","ODETTERELEASE_2","ODETTERELEASE_902","ODETTERELEASE_911","ODETTERELEASE_912","ODETTERELEASE_921","ODETTERELEASE_932","ODETTERELEASE_93A","ODETTERELEASE_94A","ODETTERELEASE_94B","ODETTERELEASE_95A","ODETTERELEASE_95B","ODETTERELEASE_96A","ODETTERELEASE_96B","ODETTERELEASE_97A","ODETTERELEASE_97B","ODETTERELEASE_98A","ODETTERELEASE_98B","ODETTERELEASE_99A","ODETTERELEASE_99B","ODETTERELEASE_00A","ODETTERELEASE_00B","ODETTERELEASE_01A","ODETTERELEASE_01B","ODETTERELEASE_02A","ODETTERELEASE_02B","ODETTERELEASE_03A","ODETTERELEASE_03B","ODETTERELEASE_04A","ODETTERELEASE_04B","ODETTERELEASE_05A","ODETTERELEASE_05B","ODETTERELEASE_06A","ODETTERELEASE_06B","ODETTERELEASE_07A","ODETTERELEASE_07B","ODETTERELEASE_08A","ODETTERELEASE_08B","ODETTERELEASE_09A","ODETTERELEASE_09B"]).optional(),
  "version": z.enum(["ODETTEVERSION_1","ODETTEVERSION_2","ODETTEVERSION_4","ODETTEVERSION_88","ODETTEVERSION_89","ODETTEVERSION_90","ODETTEVERSION_D","ODETTEVERSION_S"]).optional()
}