import { z } from "zod"

export const inputParamsSchema = {
  "apiKey": z.string().describe("Your API key"),
  "eventUri": z.string().describe("Specify the URI of the event you would like to see returned."),
  "resultType": z.enum(["info","articles","articleUris","keywordAggr","sourceExAggr","dateMentionAggr","articleTrend","similarEvents"]).describe("Define what kind of results you would like to get. Each result type corresponds to the prefix that'll be used for other parameters.").optional(),
  "articlesLang": z.array(z.string()).describe("if resultType is `articles` then use this parameter if you wish to obtain only articles about the event in specific language(s).").optional(),
  "articlesIncludeDuplicates": z.boolean().describe("if resultType is `articles` then set this value to `true` in order to return also articles that are copies of other articles (possibly from other news sources).\n").optional(),
  "keyword": z.array(z.string()).describe("Find articles that mention the specified keyword or a phrase. You can specify at most 60 keywords in a single search. If you specify multiple `keyword` parameters, then only articles that mention all of them will be returned, unless you specify `keywordOper` parameter and set it to 'or'.\n").optional(),
  "conceptUri": z.array(z.string()).describe("Find articles that mention the concept with a concept uri. You can specify at most 50 concepts in a single search. If multiple `conceptUri` parameters are provided, then only articles that are about all specified concepts will be returned, unless you specify `conceptOper` parameter and set it to 'or'. Check [autosuggest methods](https://eventregistry.org/documentation?tab=suggConcepts) to get concept URI value for a specified concept label.\n").optional(),
  "categoryUri": z.array(z.string()).describe("Find articles that are assigned to a particular category. You can specify at most 20 categories in a single search. If multiple `categoryUri` parameters are provided, then articles that are about any of the specified categories will be returned, unless you specify `categoryOper` parameter and set it to 'and'. Check [autosuggest methods](https://eventregistry.org/documentation?tab=suggCategories) to get value for a specified category name.\n").optional(),
  "sourceUri": z.array(z.string()).describe("Find articles that have been published by a news source. If you specify multiple `sourceUri` parameters, then articles from any of the specified sources will be returned. Check [autosuggest methods](https://eventregistry.org/documentation?tab=suggSources) to get value for a source name.\n").optional(),
  "sourceLocationUri": z.array(z.string()).describe("Find articles that were published by news sources located at the given geographic location (city or country). If you specify multiple `sourceLocationUri` parameters, then articles from sources from any of the specified sources will be returned. Check [autosuggest methods](https://eventregistry.org/documentation?tab=suggLocations) to get value for a location name.\n").optional(),
  "sourceGroupUri": z.array(z.string()).describe("Find articles that were published by news sources that are assigned to some predefined group of news sources. Check [autosuggest methods](https://eventregistry.org/documentation?tab=suggSourceGroups) to get value for a source group or find the uri.\n").optional(),
  "authorUri": z.array(z.string()).describe("Find articles that were written by a particular author. Check [autosuggest methods](https://eventregistry.org/documentation?tab=suggAuthors) to get value for author uri based on the author name (and potentially source url).").optional(),
  "locationUri": z.array(z.string()).describe("Find articles that describe something that occured at a particular location (based on the location mentioned in the dateline). Check [autosuggest methods](https://eventregistry.org/documentation?tab=suggLocations) to get value for a location name.").optional(),
  "lang": z.array(z.enum(["eng","spa","deu","zho","slv","cat","por","ita","fra","rus","ara","tur","hrv","srp","ind","ces","slk","pol","eus","hun","nld","swe","fin","dan","ell","ron","bul","ukr","fas","hin","urd","vie"])).describe("Find articles in the specific language(s). If not specified, all languages will be included. You can specify at most 5 languages in a single search.").optional(),
  "dateStart": z.string().describe("The starting date on or after the articles of interest were published.").optional(),
  "dateEnd": z.string().describe("The last date on which the articles of interest were published.").optional(),
  "dateMentionStart": z.string().describe("Ignore events (that contain one or more articles) or articles that explicitly mention a date that is equal or greater than `dateMentionStart`.").optional(),
  "dateMentionEnd": z.string().describe("Ignore events (that contain one or more articles) or articles that explicitly mention a date that is lower or equal to `dateMentionEnd`.").optional(),
  "keywordLoc": z.enum(["body","title","body,title"]).describe("What data should be used when searching using the keywords provided by `keywords` parameter.").optional(),
  "keywordOper": z.enum(["and","or"]).describe("If more keywords are provided with the `keyword` parameter, what should be the Boolean operator used. If 'and' (default) then all of the specified keywords have to be present in the article; if 'or' then an article will be returned if it mentions any of the provided keywords.").optional(),
  "conceptOper": z.enum(["and","or"]).describe("If more concepts are provided with the `conceptUri` parameter, what should be the Boolean operator used. If 'and' (default) then all of the specified concepts have to be present in the article; if 'or' then an article will be returned if it mentions any of the provided concepts.").optional(),
  "categoryOper": z.enum(["and","or"]).describe("If more categories are provided with the `categoryUri` parameter, what should be the Boolean operator used. If 'and' then all of the specified categories have to be present in the article; if 'or' then an article will be returned if it mentions any of the provided categories.").optional(),
  "startSourceRankPercentile": z.number().int().describe("starting [ranking percentile of the sources](https://github.com/EventRegistry/event-registry-python/wiki/Source-filtering#filtering-of-sources-based-on-their-ranking) to consider in the results (default: 0). Value should be in range 0-90 and divisible by 10.").optional(),
  "endSourceRankPercentile": z.number().int().describe("ending [ranking percentile of the sources](https://github.com/EventRegistry/event-registry-python/wiki/Source-filtering#filtering-of-sources-based-on-their-ranking) to consider in the results (default: 100). Value should be in range 10-100 and divisible by 10.").optional(),
  "minSentimentArticle": z.number().int().describe("the minimum value of the sentiment, the article should have. Valid value is any floating number between -1 (very negative) to 1 (very positive). 0 represents neutral sentiment. Note that setting the value will automatically reduce results to just English articles, since the sentiment can only be computed for English language.").optional(),
  "maxSentimentArticle": z.number().int().describe("the maximum value of the sentiment, the article should have. Valid value is any floating number between -1 (very negative) to 1 (very positive). 0 represents neutral sentiment. Note that setting the value will automatically reduce results to just English articles, since the sentiment can only be computed for English language.").optional(),
  "includeEventTitle": z.boolean().describe("Set this parameter to true to include the event title in the response.").optional(),
  "includeEventSummary": z.boolean().describe("Set this parameter to true to include the event summary in the response.").optional(),
  "includeEventSocialScore": z.boolean().describe("Set this parameter to true to include the event social score in the response.").optional(),
  "includeEventSentiment": z.boolean().describe("Set this parameter to true to include the event sentiment in the response.").optional(),
  "includeEventLocation": z.boolean().describe("Set this parameter to true to include the event location in the response.").optional(),
  "includeEventDate": z.boolean().describe("Set this parameter to true to include the event date in the response.").optional(),
  "includeEventArticleCounts": z.boolean().describe("Set this parameter to true to include the article counts for events in the response.").optional(),
  "includeEventConcepts": z.boolean().describe("Set this parameter to true to include the event concepts in the response.").optional(),
  "includeEventCategories": z.boolean().describe("Set this parameter to true to include the event categories in the response.").optional(),
  "includeEventCommonDates": z.boolean().describe("Set this parameter to true to include the event commmon dates in the response.").optional(),
  "includeEventStories": z.boolean().describe("Set this parameter to true to include the event stories in the response.").optional(),
  "eventImageCount": z.number().int().describe("Define how many images you would like to have in the response.").optional(),
  "includeConceptLabel": z.boolean().describe("Set this parameter to true to include the concept label in the response.").optional(),
  "includeConceptImage": z.boolean().describe("Set this parameter to true to include the concept image in the response.").optional(),
  "includeConceptSynonyms": z.boolean().describe("Set this parameter to true to include the concept synonyms in the response.").optional(),
  "includeConceptTrendingScore": z.boolean().describe("Set this parameter to true to include concept trending score in the response.").optional(),
  "conceptLang": z.string().describe("Define the language of the concept label.").optional(),
  "includeStoryBasicStats": z.boolean().describe("Set this parameter to true to include story basic stats in the response.").optional(),
  "includeStoryTitle": z.boolean().describe("Set this parameter to true to include the story title in the response.").optional(),
  "includeStoryLocation": z.boolean().describe("Set this parameter to true to include the story location in the response.").optional(),
  "includeStoryDate": z.boolean().describe("Set this parameter to true to include the story date in the response.").optional(),
  "includeStoryConcepts": z.boolean().describe("Set this parameter to true to include the story concepts in the response.").optional(),
  "includeStoryCategories": z.boolean().describe("Set this parameter to true to include the story categories in the response.").optional(),
  "includeStoryMedoidArticle": z.boolean().describe("Set this parameter to true to include story medoid article in the response.").optional(),
  "includeStoryCommonDates": z.boolean().describe("Set this parameter to true to include story common dates in the response.").optional(),
  "storyImageCount": z.number().int().describe("Define how many images you would like to have in the response.").optional(),
  "includeArticleTitle": z.boolean().describe("Set this parameter to true to include the article title in the response.").optional(),
  "includeArticleBasicInfo": z.boolean().describe("Set this parameter to true to include the core article information in the response.").optional(),
  "includeArticleBody": z.boolean().describe("Set this parameter to true to include the article body in the response.").optional(),
  "includeArticleEventUri": z.boolean().describe("Set this parameter to true to include the uri of the event (to which the article belongs) in the response.").optional(),
  "includeArticleSocialScore": z.boolean().describe("Set this parameter to true to include the information about how many times the article was shared on different social media.").optional(),
  "includeArticleSentiment": z.boolean().describe("Set this parameter to true to include the article sentiment in the response (value will be non-null only for English articles).").optional(),
  "includeArticleConcepts": z.boolean().describe("Set this parameter to true to include the article concepts in the response.").optional(),
  "includeArticleCategories": z.boolean().describe("Set this parameter to true to include the article categories in the response.").optional(),
  "includeArticleLocation": z.boolean().describe("Set this parameter to true to include the article location in the response.").optional(),
  "includeArticleImage": z.boolean().describe("Set this parameter to true to include the article image in the response.").optional(),
  "includeArticleAuthors": z.boolean().describe("Set this parameter to true to include the article authors in the response.").optional(),
  "includeArticleVideos": z.boolean().describe("Set this parameter to true to include the article videos in the response.").optional(),
  "includeArticleLinks": z.boolean().describe("Set this parameter to true to include the article links in the response.").optional(),
  "includeArticleExtractedDates": z.boolean().describe("Set this parameter to true to include article extracted dates in the response.").optional(),
  "includeArticleDuplicateList": z.boolean().describe("Set this parameter to true to include the list of duplicate articles in the response.").optional(),
  "includeArticleOriginalArticle": z.boolean().describe("Set this parameter to true to include the original article in the response.").optional(),
  "articleBodyLen": z.number().int().describe("Set the size of the article body that'll be returned in the response. Use -1 for full article body.").optional(),
  "includeSourceTitle": z.boolean().describe("Set this parameter to true to include the source title in the response.").optional(),
  "includeSourceDescription": z.boolean().describe("Set this parameter to true to include the source description in the response.").optional(),
  "includeSourceLocation": z.boolean().describe("Set this parameter to true to include the source location in the response.").optional(),
  "includeSourceRanking": z.boolean().describe("Set this parameter to true to include the source ranking in the response.").optional(),
  "includeLocationPopulation": z.boolean().describe("Set to true to include the population size of the location").optional(),
  "includeLocationGeoNamesId": z.boolean().describe("Set to true to include the GeoNames id of the location").optional(),
  "includeLocationCountryArea": z.boolean().describe("Set to true to include the are of the location in squared km.").optional(),
  "includeLocationCountryContinent": z.boolean().describe("Set to true to get the continent of the country for location objects.").optional()
}