import { z } from "zod"

export const inputParamsSchema = {
  "address": z.array(z.string()).optional(),
  "address__empty": z.boolean().optional(),
  "address__ic": z.array(z.string()).optional(),
  "address__ie": z.array(z.string()).optional(),
  "address__iew": z.array(z.string()).optional(),
  "address__isw": z.array(z.string()).optional(),
  "address__n": z.array(z.string()).optional(),
  "address__nic": z.array(z.string()).optional(),
  "address__nie": z.array(z.string()).optional(),
  "address__niew": z.array(z.string()).optional(),
  "address__nisw": z.array(z.string()).optional(),
  "created": z.array(z.string().datetime({ offset: true })).optional(),
  "created__empty": z.array(z.string().datetime({ offset: true })).optional(),
  "created__gt": z.array(z.string().datetime({ offset: true })).optional(),
  "created__gte": z.array(z.string().datetime({ offset: true })).optional(),
  "created__lt": z.array(z.string().datetime({ offset: true })).optional(),
  "created__lte": z.array(z.string().datetime({ offset: true })).optional(),
  "created__n": z.array(z.string().datetime({ offset: true })).optional(),
  "created_by_request": z.string().uuid().optional(),
  "description": z.array(z.string()).optional(),
  "description__empty": z.boolean().optional(),
  "description__ic": z.array(z.string()).optional(),
  "description__ie": z.array(z.string()).optional(),
  "description__iew": z.array(z.string()).optional(),
  "description__isw": z.array(z.string()).optional(),
  "description__n": z.array(z.string()).optional(),
  "description__nic": z.array(z.string()).optional(),
  "description__nie": z.array(z.string()).optional(),
  "description__niew": z.array(z.string()).optional(),
  "description__nisw": z.array(z.string()).optional(),
  "email": z.array(z.string()).optional(),
  "email__empty": z.boolean().optional(),
  "email__ic": z.array(z.string()).optional(),
  "email__ie": z.array(z.string()).optional(),
  "email__iew": z.array(z.string()).optional(),
  "email__isw": z.array(z.string()).optional(),
  "email__n": z.array(z.string()).optional(),
  "email__nic": z.array(z.string()).optional(),
  "email__nie": z.array(z.string()).optional(),
  "email__niew": z.array(z.string()).optional(),
  "email__nisw": z.array(z.string()).optional(),
  "group": z.array(z.string()).optional(),
  "group__n": z.array(z.string()).optional(),
  "group_id": z.array(z.string()).optional(),
  "group_id__n": z.array(z.string()).optional(),
  "id": z.array(z.number().int()).optional(),
  "id__empty": z.boolean().optional(),
  "id__gt": z.array(z.number().int()).optional(),
  "id__gte": z.array(z.number().int()).optional(),
  "id__lt": z.array(z.number().int()).optional(),
  "id__lte": z.array(z.number().int()).optional(),
  "id__n": z.array(z.number().int()).optional(),
  "last_updated": z.array(z.string().datetime({ offset: true })).optional(),
  "last_updated__empty": z.array(z.string().datetime({ offset: true })).optional(),
  "last_updated__gt": z.array(z.string().datetime({ offset: true })).optional(),
  "last_updated__gte": z.array(z.string().datetime({ offset: true })).optional(),
  "last_updated__lt": z.array(z.string().datetime({ offset: true })).optional(),
  "last_updated__lte": z.array(z.string().datetime({ offset: true })).optional(),
  "last_updated__n": z.array(z.string().datetime({ offset: true })).optional(),
  "limit": z.number().int().describe("Number of results to return per page.").optional(),
  "link": z.array(z.string()).optional(),
  "link__empty": z.boolean().optional(),
  "link__ic": z.array(z.string()).optional(),
  "link__ie": z.array(z.string()).optional(),
  "link__iew": z.array(z.string()).optional(),
  "link__isw": z.array(z.string()).optional(),
  "link__n": z.array(z.string()).optional(),
  "link__nic": z.array(z.string()).optional(),
  "link__nie": z.array(z.string()).optional(),
  "link__niew": z.array(z.string()).optional(),
  "link__nisw": z.array(z.string()).optional(),
  "modified_by_request": z.string().uuid().optional(),
  "name": z.array(z.string()).optional(),
  "name__empty": z.boolean().optional(),
  "name__ic": z.array(z.string()).optional(),
  "name__ie": z.array(z.string()).optional(),
  "name__iew": z.array(z.string()).optional(),
  "name__isw": z.array(z.string()).optional(),
  "name__n": z.array(z.string()).optional(),
  "name__nic": z.array(z.string()).optional(),
  "name__nie": z.array(z.string()).optional(),
  "name__niew": z.array(z.string()).optional(),
  "name__nisw": z.array(z.string()).optional(),
  "offset": z.number().int().describe("The initial index from which to return the results.").optional(),
  "ordering": z.string().describe("Which field to use when ordering the results.").optional(),
  "phone": z.array(z.string()).optional(),
  "phone__empty": z.boolean().optional(),
  "phone__ic": z.array(z.string()).optional(),
  "phone__ie": z.array(z.string()).optional(),
  "phone__iew": z.array(z.string()).optional(),
  "phone__isw": z.array(z.string()).optional(),
  "phone__n": z.array(z.string()).optional(),
  "phone__nic": z.array(z.string()).optional(),
  "phone__nie": z.array(z.string()).optional(),
  "phone__niew": z.array(z.string()).optional(),
  "phone__nisw": z.array(z.string()).optional(),
  "q": z.string().describe("Search").optional(),
  "tag": z.array(z.string()).optional(),
  "tag__n": z.array(z.string()).optional(),
  "tag_id": z.array(z.number().int()).optional(),
  "tag_id__n": z.array(z.number().int()).optional(),
  "title": z.array(z.string()).optional(),
  "title__empty": z.boolean().optional(),
  "title__ic": z.array(z.string()).optional(),
  "title__ie": z.array(z.string()).optional(),
  "title__iew": z.array(z.string()).optional(),
  "title__isw": z.array(z.string()).optional(),
  "title__n": z.array(z.string()).optional(),
  "title__nic": z.array(z.string()).optional(),
  "title__nie": z.array(z.string()).optional(),
  "title__niew": z.array(z.string()).optional(),
  "title__nisw": z.array(z.string()).optional(),
  "updated_by_request": z.string().uuid().optional()
}