import { z } from "zod"

export const inputParamsSchema = {
  "search_string": z.string().optional(),
  "order": z.string().optional(),
  "order_direction": z.string().optional(),
  "invitation_start_date": z.string().datetime({ offset: true }).optional(),
  "invitation_end_date": z.string().datetime({ offset: true }).optional(),
  "opportunity_start_date": z.number().int().optional(),
  "opportunity_end_date": z.number().int().optional(),
  "paid_start_date": z.string().datetime({ offset: true }).optional(),
  "paid_end_date": z.string().datetime({ offset: true }).optional(),
  "discarded_start_date": z.number().int().optional(),
  "discarded_end_date": z.number().int().optional(),
  "updated_start_date": z.number().int().optional(),
  "updated_end_date": z.number().int().optional(),
  "recurrent_start_date": z.number().int().optional(),
  "recurrent_end_date": z.number().int().optional(),
  "products": z.array(z.string()).optional(),
  "products_out": z.array(z.string()).optional(),
  "services": z.array(z.string()).optional(),
  "services_out": z.array(z.string()).optional(),
  "not_blocked": z.number().int().optional(),
  "connected": z.number().int().optional(),
  "discarded": z.number().int().optional(),
  "opportunity": z.number().int().optional(),
  "paid": z.number().int().optional(),
  "recurrent": z.number().int().optional(),
  "has_products": z.number().int().optional(),
  "has_services": z.number().int().optional(),
  "assigned_client": z.number().int().optional(),
  "signed": z.number().int().optional(),
  "with_recurrency": z.number().int().optional(),
  "with_bank_account": z.number().int().optional(),
  "with_fiscal_documents": z.number().int().optional(),
  "gocardless_active": z.number().int().optional(),
  "sage_active": z.number().int().optional(),
  "onboarding_completed": z.number().int().optional(),
  "opportunity_labels": z.array(z.string()).optional(),
  "label_filter_mode": z.string().optional(),
  "postal_code": z.string().optional(),
  "province": z.string().optional(),
  "business_type": z.string().optional(),
  "min_anual_budget": z.number().int().optional(),
  "max_anual_budget": z.number().int().optional(),
  "startup_certified": z.number().int().optional(),
  "message_language": z.string().optional(),
  "has_offer": z.number().int().optional()
}