import { z } from "zod"

export const inputParamsSchema = {
  "business_id": z.string(),
  "contract_modification_id": z.string(),
  "b_business_id": z.string().optional(),
  "contract_id": z.string().optional(),
  "temporality": z.string().optional(),
  "value": z.string().optional(),
  "status": z.string().optional(),
  "contract_modification_timestamp": z.number().int().optional(),
  "job_functions": z.string().optional(),
  "category": z.string().optional(),
  "start_date": z.string().datetime({ offset: true }).optional(),
  "end_date": z.string().datetime({ offset: true }).optional(),
  "hours": z.number().int().optional(),
  "hours_definition": z.string().optional(),
  "hours_by_days": z.string().optional(),
  "days": z.string().optional(),
  "replaces_to_person": z.string().optional(),
  "replaces_to_limit_date": z.string().datetime({ offset: true }).optional(),
  "replaces_affiliation_number": z.string().optional(),
  "replaces_cause": z.string().optional(),
  "observations": z.string().optional(),
  "salary_year": z.number().int().optional(),
  "type": z.string().optional(),
  "account_id": z.string().optional(),
  "headquarter_id": z.string().optional(),
  "contract_reason": z.string().optional(),
  "work_in_weekend": z.boolean().optional(),
  "notify_minimum_salary": z.boolean().optional(),
  "trial_period": z.string().optional(),
  "trial_period_condition": z.number().int().optional(),
  "number_payments": z.number().int().optional(),
  "number_payments_condition": z.number().int().optional(),
  "irpf_worker": z.number().int().optional(),
  "irpf_perceived": z.number().int().optional(),
  "irpf_retained": z.number().int().optional(),
  "project_details": z.string().optional(),
  "email": z.string().optional(),
  "date_submit": z.string().datetime({ offset: true }).optional()
}