import { inputParamsSchema } from "./schema/root.js"
import type { OpenMCPServerTool } from "@open-mcp/core"

const tool: OpenMCPServerTool = {
  "toolName": "ipam_ip_addresses_list",
  "toolDescription": "Get a list of IP address objects.",
  "baseUrl": "https://api.example.com",
  "path": "/api/ipam/ip-addresses/",
  "method": "get",
  "security": [
    {
      "key": "sessionid",
      "value": "<mcp-env-var>SESSIONID</mcp-env-var>",
      "in": "cookie",
      "envVarName": "SESSIONID"
    },
    {
      "key": "Authorization",
      "value": "<mcp-env-var>AUTHORIZATION</mcp-env-var>",
      "in": "header",
      "envVarName": "AUTHORIZATION"
    }
  ],
  "paramsMap": {
    "query": {
      "address": "address",
      "assigned": "assigned",
      "assigned_object_id": "assigned_object_id",
      "assigned_object_id__empty": "assigned_object_id__empty",
      "assigned_object_id__gt": "assigned_object_id__gt",
      "assigned_object_id__gte": "assigned_object_id__gte",
      "assigned_object_id__lt": "assigned_object_id__lt",
      "assigned_object_id__lte": "assigned_object_id__lte",
      "assigned_object_id__n": "assigned_object_id__n",
      "assigned_object_type": "assigned_object_type",
      "assigned_object_type__n": "assigned_object_type__n",
      "assigned_to_interface": "assigned_to_interface",
      "contact": "contact",
      "contact__n": "contact__n",
      "contact_group": "contact_group",
      "contact_group__n": "contact_group__n",
      "contact_role": "contact_role",
      "contact_role__n": "contact_role__n",
      "created": "created",
      "created__empty": "created__empty",
      "created__gt": "created__gt",
      "created__gte": "created__gte",
      "created__lt": "created__lt",
      "created__lte": "created__lte",
      "created__n": "created__n",
      "created_by_request": "created_by_request",
      "description": "description",
      "description__empty": "description__empty",
      "description__ic": "description__ic",
      "description__ie": "description__ie",
      "description__iew": "description__iew",
      "description__isw": "description__isw",
      "description__n": "description__n",
      "description__nic": "description__nic",
      "description__nie": "description__nie",
      "description__niew": "description__niew",
      "description__nisw": "description__nisw",
      "device": "device",
      "device_id": "device_id",
      "dns_name": "dns_name",
      "dns_name__empty": "dns_name__empty",
      "dns_name__ic": "dns_name__ic",
      "dns_name__ie": "dns_name__ie",
      "dns_name__iew": "dns_name__iew",
      "dns_name__isw": "dns_name__isw",
      "dns_name__n": "dns_name__n",
      "dns_name__nic": "dns_name__nic",
      "dns_name__nie": "dns_name__nie",
      "dns_name__niew": "dns_name__niew",
      "dns_name__nisw": "dns_name__nisw",
      "family": "family",
      "fhrpgroup_id": "fhrpgroup_id",
      "fhrpgroup_id__n": "fhrpgroup_id__n",
      "id": "id",
      "id__empty": "id__empty",
      "id__gt": "id__gt",
      "id__gte": "id__gte",
      "id__lt": "id__lt",
      "id__lte": "id__lte",
      "id__n": "id__n",
      "interface": "interface",
      "interface__n": "interface__n",
      "interface_id": "interface_id",
      "interface_id__n": "interface_id__n",
      "last_updated": "last_updated",
      "last_updated__empty": "last_updated__empty",
      "last_updated__gt": "last_updated__gt",
      "last_updated__gte": "last_updated__gte",
      "last_updated__lt": "last_updated__lt",
      "last_updated__lte": "last_updated__lte",
      "last_updated__n": "last_updated__n",
      "limit": "limit",
      "mask_length": "mask_length",
      "mask_length__gte": "mask_length__gte",
      "mask_length__lte": "mask_length__lte",
      "modified_by_request": "modified_by_request",
      "nat_inside_id": "nat_inside_id",
      "nat_inside_id__n": "nat_inside_id__n",
      "offset": "offset",
      "ordering": "ordering",
      "parent": "parent",
      "present_in_vrf": "present_in_vrf",
      "present_in_vrf_id": "present_in_vrf_id",
      "q": "q",
      "role": "role",
      "role__empty": "role__empty",
      "role__ic": "role__ic",
      "role__ie": "role__ie",
      "role__iew": "role__iew",
      "role__isw": "role__isw",
      "role__n": "role__n",
      "role__nic": "role__nic",
      "role__nie": "role__nie",
      "role__niew": "role__niew",
      "role__nisw": "role__nisw",
      "service_id": "service_id",
      "service_id__n": "service_id__n",
      "status": "status",
      "status__empty": "status__empty",
      "status__ic": "status__ic",
      "status__ie": "status__ie",
      "status__iew": "status__iew",
      "status__isw": "status__isw",
      "status__n": "status__n",
      "status__nic": "status__nic",
      "status__nie": "status__nie",
      "status__niew": "status__niew",
      "status__nisw": "status__nisw",
      "tag": "tag",
      "tag__n": "tag__n",
      "tag_id": "tag_id",
      "tag_id__n": "tag_id__n",
      "tenant": "tenant",
      "tenant__n": "tenant__n",
      "tenant_group": "tenant_group",
      "tenant_group__n": "tenant_group__n",
      "tenant_group_id": "tenant_group_id",
      "tenant_group_id__n": "tenant_group_id__n",
      "tenant_id": "tenant_id",
      "tenant_id__n": "tenant_id__n",
      "updated_by_request": "updated_by_request",
      "virtual_machine": "virtual_machine",
      "virtual_machine_id": "virtual_machine_id",
      "vminterface": "vminterface",
      "vminterface__n": "vminterface__n",
      "vminterface_id": "vminterface_id",
      "vminterface_id__n": "vminterface_id__n",
      "vrf": "vrf",
      "vrf__n": "vrf__n",
      "vrf_id": "vrf_id",
      "vrf_id__n": "vrf_id__n"
    }
  },
  inputParamsSchema
}

export default tool