import { inputParamsSchema } from "./schema/root.js"
import type { OpenMCPServerTool } from "@open-mcp/core"

const tool: OpenMCPServerTool = {
  "toolName": "ipam_fhrp_groups_list",
  "toolDescription": "Get a list of FHRP group objects.",
  "baseUrl": "https://api.example.com",
  "path": "/api/ipam/fhrp-groups/",
  "method": "get",
  "security": [
    {
      "key": "sessionid",
      "value": "<mcp-env-var>SESSIONID</mcp-env-var>",
      "in": "cookie",
      "envVarName": "SESSIONID"
    },
    {
      "key": "Authorization",
      "value": "<mcp-env-var>AUTHORIZATION</mcp-env-var>",
      "in": "header",
      "envVarName": "AUTHORIZATION"
    }
  ],
  "paramsMap": {
    "query": {
      "auth_key": "auth_key",
      "auth_key__empty": "auth_key__empty",
      "auth_key__ic": "auth_key__ic",
      "auth_key__ie": "auth_key__ie",
      "auth_key__iew": "auth_key__iew",
      "auth_key__isw": "auth_key__isw",
      "auth_key__n": "auth_key__n",
      "auth_key__nic": "auth_key__nic",
      "auth_key__nie": "auth_key__nie",
      "auth_key__niew": "auth_key__niew",
      "auth_key__nisw": "auth_key__nisw",
      "auth_type": "auth_type",
      "auth_type__empty": "auth_type__empty",
      "auth_type__ic": "auth_type__ic",
      "auth_type__ie": "auth_type__ie",
      "auth_type__iew": "auth_type__iew",
      "auth_type__isw": "auth_type__isw",
      "auth_type__n": "auth_type__n",
      "auth_type__nic": "auth_type__nic",
      "auth_type__nie": "auth_type__nie",
      "auth_type__niew": "auth_type__niew",
      "auth_type__nisw": "auth_type__nisw",
      "created": "created",
      "created__empty": "created__empty",
      "created__gt": "created__gt",
      "created__gte": "created__gte",
      "created__lt": "created__lt",
      "created__lte": "created__lte",
      "created__n": "created__n",
      "created_by_request": "created_by_request",
      "description": "description",
      "description__empty": "description__empty",
      "description__ic": "description__ic",
      "description__ie": "description__ie",
      "description__iew": "description__iew",
      "description__isw": "description__isw",
      "description__n": "description__n",
      "description__nic": "description__nic",
      "description__nie": "description__nie",
      "description__niew": "description__niew",
      "description__nisw": "description__nisw",
      "group_id": "group_id",
      "group_id__empty": "group_id__empty",
      "group_id__gt": "group_id__gt",
      "group_id__gte": "group_id__gte",
      "group_id__lt": "group_id__lt",
      "group_id__lte": "group_id__lte",
      "group_id__n": "group_id__n",
      "id": "id",
      "id__empty": "id__empty",
      "id__gt": "id__gt",
      "id__gte": "id__gte",
      "id__lt": "id__lt",
      "id__lte": "id__lte",
      "id__n": "id__n",
      "last_updated": "last_updated",
      "last_updated__empty": "last_updated__empty",
      "last_updated__gt": "last_updated__gt",
      "last_updated__gte": "last_updated__gte",
      "last_updated__lt": "last_updated__lt",
      "last_updated__lte": "last_updated__lte",
      "last_updated__n": "last_updated__n",
      "limit": "limit",
      "modified_by_request": "modified_by_request",
      "name": "name",
      "name__empty": "name__empty",
      "name__ic": "name__ic",
      "name__ie": "name__ie",
      "name__iew": "name__iew",
      "name__isw": "name__isw",
      "name__n": "name__n",
      "name__nic": "name__nic",
      "name__nie": "name__nie",
      "name__niew": "name__niew",
      "name__nisw": "name__nisw",
      "offset": "offset",
      "ordering": "ordering",
      "protocol": "protocol",
      "protocol__empty": "protocol__empty",
      "protocol__ic": "protocol__ic",
      "protocol__ie": "protocol__ie",
      "protocol__iew": "protocol__iew",
      "protocol__isw": "protocol__isw",
      "protocol__n": "protocol__n",
      "protocol__nic": "protocol__nic",
      "protocol__nie": "protocol__nie",
      "protocol__niew": "protocol__niew",
      "protocol__nisw": "protocol__nisw",
      "q": "q",
      "related_ip": "related_ip",
      "tag": "tag",
      "tag__n": "tag__n",
      "tag_id": "tag_id",
      "tag_id__n": "tag_id__n",
      "updated_by_request": "updated_by_request"
    }
  },
  inputParamsSchema
}

export default tool