import { z } from "zod"

export const inputParamsSchema = {
  "business_id": z.string().describe("Business ID"),
  "business_type": z.string().optional(),
  "start_company_date": z.string().datetime({ offset: true }).optional(),
  "completed": z.string().optional(),
  "name_mode": z.string().optional(),
  "legal_name": z.string().optional(),
  "name_granted_file": z.array(z.string()).optional(),
  "city": z.string().optional(),
  "iban": z.string().optional(),
  "desired_constitution_company_date": z.string().datetime({ offset: true }).optional(),
  "activity_direccion": z.string().optional(),
  "activity_postal_code": z.string().optional(),
  "activity_town": z.string().optional(),
  "activity_province": z.string().optional(),
  "personal_address": z.string().optional(),
  "personal_zipcode": z.string().optional(),
  "personal_town": z.string().optional(),
  "personal_province": z.string().optional(),
  "social_direccion": z.string().optional(),
  "social_postal_code": z.string().optional(),
  "social_town": z.string().optional(),
  "social_province": z.string().optional(),
  "fiscal_direccion": z.string().optional(),
  "fiscal_postal_code": z.string().optional(),
  "fiscal_town": z.string().optional(),
  "fiscal_province": z.string().optional(),
  "meters_local": z.number().int().optional(),
  "meters_activity": z.number().int().optional(),
  "principal_activity": z.string().optional(),
  "secondary_activity": z.string().optional(),
  "regimen_iva": z.string().optional(),
  "regimen_irpf": z.string().optional(),
  "intracomunitario": z.string().optional(),
  "vivir_en_extranjero": z.string().optional(),
  "bank_account": z.string().optional(),
  "civil_state": z.string().optional(),
  "civil_state_date": z.string().datetime({ offset: true }).optional(),
  "name": z.string().optional(),
  "lastname_1": z.string().optional(),
  "lastname_2": z.string().optional(),
  "dni": z.string().optional(),
  "passport": z.string().optional(),
  "social_security": z.string().optional(),
  "sell_eu": z.string().optional(),
  "buy_eu": z.string().optional(),
  "suscribe_services": z.string().optional(),
  "job_seeker": z.string().optional(),
  "activity_place": z.string().optional(),
  "cadastral_reference": z.string().optional(),
  "birth_date": z.string().datetime({ offset: true }).optional(),
  "nationality": z.string().optional(),
  "document_type": z.string().optional(),
  "have_social_security_number": z.string().optional(),
  "birth_place": z.string().optional(),
  "birth_province": z.string().optional(),
  "birth_country": z.string().optional(),
  "father_name_surname": z.string().optional(),
  "mother_name_surname": z.string().optional(),
  "mother_single_surname": z.string().optional(),
  "contribution_base_select": z.string().optional(),
  "contribution_base_number": z.string().optional(),
  "termination_of_activity_select": z.string().optional(),
  "mutual_company": z.string().optional(),
  "youth": z.string().optional(),
  "dni_file": z.array(z.string()).optional(),
  "sepa_file": z.array(z.string()).optional(),
  "roi_file": z.array(z.string()).optional(),
  "europa_out": z.string().optional(),
  "monetary_contribution": z.string().optional(),
  "availability": z.string().optional(),
  "amount_contribution": z.string().optional(),
  "contibution_objects": z.string().optional(),
  "partners": z.array(z.object({ "id": z.string().optional(), "name": z.string().optional(), "lastname_1": z.string().optional(), "lastname_2": z.string().optional(), "birth_date": z.string().datetime({ offset: true }).optional(), "document_type": z.string().optional(), "dni": z.string().optional(), "passport": z.string().optional(), "nationality": z.string().optional(), "country_of_residence": z.string().optional(), "social_security": z.string().optional(), "bank_account": z.string().optional(), "iban": z.string().optional(), "iban_2": z.string().optional(), "civil_state": z.string().optional(), "civil_state_date": z.string().datetime({ offset: true }).optional(), "separation_property": z.string().optional(), "name_spouse": z.string().optional(), "dni_spouse": z.string().optional(), "administrator": z.string().optional(), "work_in_society": z.string().optional(), "have_social_security_number": z.string().optional(), "birth_place": z.string().optional(), "birth_province": z.string().optional(), "birth_country": z.string().optional(), "father_name_surname": z.string().optional(), "mother_name_surname": z.string().optional(), "contribution_base_select": z.string().optional(), "contribution_base_number": z.number().int().optional(), "termination_of_activity_select": z.string().optional(), "mutual_company": z.string().optional(), "is_autonomous": z.string().optional(), "personal_address": z.string().optional(), "personal_zipcode": z.string().optional(), "personal_town": z.string().optional(), "personal_province": z.string().optional(), "partner_type": z.string().optional(), "legal_name": z.string().optional(), "nif": z.string().optional(), "establishment_date": z.string().datetime({ offset: true }).optional(), "registration_date": z.string().datetime({ offset: true }).optional(), "contribution_new_company": z.string().optional(), "representative_name": z.string().optional(), "representative_lastname_1": z.string().optional(), "representative_lastname_2": z.string().optional(), "representative_nationality": z.string().optional(), "representative_document_type": z.string().optional(), "representative_dni": z.string().optional(), "representative_address": z.string().optional(), "representative_zipcode": z.string().optional(), "representative_town": z.string().optional(), "representative_province": z.string().optional(), "legal_person_social_address": z.string().optional(), "legal_person_social_zipcode": z.string().optional(), "legal_person_social_town": z.string().optional(), "legal_person_social_province": z.string().optional(), "capitalized_unemployment": z.string().optional(), "freelancer_10_months": z.string().optional(), "dni_document": z.array(z.string()).optional(), "sepa_document": z.array(z.string()).optional(), "percentage": z.number().int().optional(), "percentage_2": z.number().int().optional() })).optional(),
  "capital_document": z.array(z.string()).optional(),
  "simplify": z.string().optional(),
  "name1": z.string().optional(),
  "name2": z.string().optional(),
  "name3": z.string().optional(),
  "name4": z.string().optional(),
  "name5": z.string().optional()
}