import { inputParamsSchema } from "./schema/root.js"
import type { OpenMCPServerTool } from "@open-mcp/core"

const tool: OpenMCPServerTool = {
  "toolName": "virtualization_interfaces_list",
  "toolDescription": "Get a list of interface objects.",
  "baseUrl": "https://api.example.com",
  "path": "/api/virtualization/interfaces/",
  "method": "get",
  "security": [
    {
      "key": "sessionid",
      "value": "<mcp-env-var>SESSIONID</mcp-env-var>",
      "in": "cookie",
      "envVarName": "SESSIONID"
    },
    {
      "key": "Authorization",
      "value": "<mcp-env-var>AUTHORIZATION</mcp-env-var>",
      "in": "header",
      "envVarName": "AUTHORIZATION"
    }
  ],
  "paramsMap": {
    "query": {
      "bridge_id": "bridge_id",
      "bridge_id__n": "bridge_id__n",
      "cluster": "cluster",
      "cluster__n": "cluster__n",
      "cluster_id": "cluster_id",
      "cluster_id__n": "cluster_id__n",
      "created": "created",
      "created__empty": "created__empty",
      "created__gt": "created__gt",
      "created__gte": "created__gte",
      "created__lt": "created__lt",
      "created__lte": "created__lte",
      "created__n": "created__n",
      "created_by_request": "created_by_request",
      "description": "description",
      "description__empty": "description__empty",
      "description__ic": "description__ic",
      "description__ie": "description__ie",
      "description__iew": "description__iew",
      "description__isw": "description__isw",
      "description__n": "description__n",
      "description__nic": "description__nic",
      "description__nie": "description__nie",
      "description__niew": "description__niew",
      "description__nisw": "description__nisw",
      "enabled": "enabled",
      "id": "id",
      "id__empty": "id__empty",
      "id__gt": "id__gt",
      "id__gte": "id__gte",
      "id__lt": "id__lt",
      "id__lte": "id__lte",
      "id__n": "id__n",
      "l2vpn": "l2vpn",
      "l2vpn__n": "l2vpn__n",
      "l2vpn_id": "l2vpn_id",
      "l2vpn_id__n": "l2vpn_id__n",
      "last_updated": "last_updated",
      "last_updated__empty": "last_updated__empty",
      "last_updated__gt": "last_updated__gt",
      "last_updated__gte": "last_updated__gte",
      "last_updated__lt": "last_updated__lt",
      "last_updated__lte": "last_updated__lte",
      "last_updated__n": "last_updated__n",
      "limit": "limit",
      "mac_address": "mac_address",
      "mac_address__ic": "mac_address__ic",
      "mac_address__ie": "mac_address__ie",
      "mac_address__iew": "mac_address__iew",
      "mac_address__isw": "mac_address__isw",
      "mac_address__n": "mac_address__n",
      "mac_address__nic": "mac_address__nic",
      "mac_address__nie": "mac_address__nie",
      "mac_address__niew": "mac_address__niew",
      "mac_address__nisw": "mac_address__nisw",
      "mode": "mode",
      "mode__empty": "mode__empty",
      "mode__ic": "mode__ic",
      "mode__ie": "mode__ie",
      "mode__iew": "mode__iew",
      "mode__isw": "mode__isw",
      "mode__n": "mode__n",
      "mode__nic": "mode__nic",
      "mode__nie": "mode__nie",
      "mode__niew": "mode__niew",
      "mode__nisw": "mode__nisw",
      "modified_by_request": "modified_by_request",
      "mtu": "mtu",
      "mtu__empty": "mtu__empty",
      "mtu__gt": "mtu__gt",
      "mtu__gte": "mtu__gte",
      "mtu__lt": "mtu__lt",
      "mtu__lte": "mtu__lte",
      "mtu__n": "mtu__n",
      "name": "name",
      "name__empty": "name__empty",
      "name__ic": "name__ic",
      "name__ie": "name__ie",
      "name__iew": "name__iew",
      "name__isw": "name__isw",
      "name__n": "name__n",
      "name__nic": "name__nic",
      "name__nie": "name__nie",
      "name__niew": "name__niew",
      "name__nisw": "name__nisw",
      "offset": "offset",
      "ordering": "ordering",
      "parent_id": "parent_id",
      "parent_id__n": "parent_id__n",
      "primary_mac_address": "primary_mac_address",
      "primary_mac_address__n": "primary_mac_address__n",
      "primary_mac_address_id": "primary_mac_address_id",
      "primary_mac_address_id__n": "primary_mac_address_id__n",
      "q": "q",
      "tag": "tag",
      "tag__n": "tag__n",
      "tag_id": "tag_id",
      "tag_id__n": "tag_id__n",
      "updated_by_request": "updated_by_request",
      "virtual_machine": "virtual_machine",
      "virtual_machine__n": "virtual_machine__n",
      "virtual_machine_id": "virtual_machine_id",
      "virtual_machine_id__n": "virtual_machine_id__n",
      "vlan": "vlan",
      "vlan_id": "vlan_id",
      "vlan_translation_policy": "vlan_translation_policy",
      "vlan_translation_policy__n": "vlan_translation_policy__n",
      "vlan_translation_policy_id": "vlan_translation_policy_id",
      "vlan_translation_policy_id__n": "vlan_translation_policy_id__n",
      "vrf": "vrf",
      "vrf__n": "vrf__n",
      "vrf_id": "vrf_id",
      "vrf_id__n": "vrf_id__n"
    }
  },
  inputParamsSchema
}

export default tool