import { inputParamsSchema } from "./schema/root.js"
import type { OpenMCPServerTool } from "@open-mcp/core"

const tool: OpenMCPServerTool = {
  "toolName": "getevent",
  "toolDescription": "Obtain details about a single event",
  "baseUrl": "https://eventregistry.org",
  "path": "/api/v1/event/getEvent",
  "method": "get",
  "security": [],
  "paramsMap": {
    "query": {
      "apiKey": "apiKey",
      "eventUri": "eventUri",
      "resultType": "resultType",
      "articlesLang": "articlesLang",
      "articlesIncludeDuplicates": "articlesIncludeDuplicates",
      "keyword": "keyword",
      "conceptUri": "conceptUri",
      "categoryUri": "categoryUri",
      "sourceUri": "sourceUri",
      "sourceLocationUri": "sourceLocationUri",
      "sourceGroupUri": "sourceGroupUri",
      "authorUri": "authorUri",
      "locationUri": "locationUri",
      "lang": "lang",
      "dateStart": "dateStart",
      "dateEnd": "dateEnd",
      "dateMentionStart": "dateMentionStart",
      "dateMentionEnd": "dateMentionEnd",
      "keywordLoc": "keywordLoc",
      "keywordOper": "keywordOper",
      "conceptOper": "conceptOper",
      "categoryOper": "categoryOper",
      "startSourceRankPercentile": "startSourceRankPercentile",
      "endSourceRankPercentile": "endSourceRankPercentile",
      "minSentimentArticle": "minSentimentArticle",
      "maxSentimentArticle": "maxSentimentArticle",
      "includeEventTitle": "includeEventTitle",
      "includeEventSummary": "includeEventSummary",
      "includeEventSocialScore": "includeEventSocialScore",
      "includeEventSentiment": "includeEventSentiment",
      "includeEventLocation": "includeEventLocation",
      "includeEventDate": "includeEventDate",
      "includeEventArticleCounts": "includeEventArticleCounts",
      "includeEventConcepts": "includeEventConcepts",
      "includeEventCategories": "includeEventCategories",
      "includeEventCommonDates": "includeEventCommonDates",
      "includeEventStories": "includeEventStories",
      "eventImageCount": "eventImageCount",
      "includeConceptLabel": "includeConceptLabel",
      "includeConceptImage": "includeConceptImage",
      "includeConceptSynonyms": "includeConceptSynonyms",
      "includeConceptTrendingScore": "includeConceptTrendingScore",
      "conceptLang": "conceptLang",
      "includeStoryBasicStats": "includeStoryBasicStats",
      "includeStoryTitle": "includeStoryTitle",
      "includeStoryLocation": "includeStoryLocation",
      "includeStoryDate": "includeStoryDate",
      "includeStoryConcepts": "includeStoryConcepts",
      "includeStoryCategories": "includeStoryCategories",
      "includeStoryMedoidArticle": "includeStoryMedoidArticle",
      "includeStoryCommonDates": "includeStoryCommonDates",
      "storyImageCount": "storyImageCount",
      "includeArticleTitle": "includeArticleTitle",
      "includeArticleBasicInfo": "includeArticleBasicInfo",
      "includeArticleBody": "includeArticleBody",
      "includeArticleEventUri": "includeArticleEventUri",
      "includeArticleSocialScore": "includeArticleSocialScore",
      "includeArticleSentiment": "includeArticleSentiment",
      "includeArticleConcepts": "includeArticleConcepts",
      "includeArticleCategories": "includeArticleCategories",
      "includeArticleLocation": "includeArticleLocation",
      "includeArticleImage": "includeArticleImage",
      "includeArticleAuthors": "includeArticleAuthors",
      "includeArticleVideos": "includeArticleVideos",
      "includeArticleLinks": "includeArticleLinks",
      "includeArticleExtractedDates": "includeArticleExtractedDates",
      "includeArticleDuplicateList": "includeArticleDuplicateList",
      "includeArticleOriginalArticle": "includeArticleOriginalArticle",
      "articleBodyLen": "articleBodyLen",
      "includeSourceTitle": "includeSourceTitle",
      "includeSourceDescription": "includeSourceDescription",
      "includeSourceLocation": "includeSourceLocation",
      "includeSourceRanking": "includeSourceRanking",
      "includeLocationPopulation": "includeLocationPopulation",
      "includeLocationGeoNamesId": "includeLocationGeoNamesId",
      "includeLocationCountryArea": "includeLocationCountryArea",
      "includeLocationCountryContinent": "includeLocationCountryContinent"
    }
  },
  inputParamsSchema
}

export default tool