import { inputParamsSchema } from "./schema/root.js"
import type { OpenMCPServerTool } from "@open-mcp/core"

const tool: OpenMCPServerTool = {
  "toolName": "circuits_virtual_circuit_terminations_list",
  "toolDescription": "Get a list of virtual circuit termination objects.",
  "baseUrl": "https://api.example.com",
  "path": "/api/circuits/virtual-circuit-terminations/",
  "method": "get",
  "security": [
    {
      "key": "sessionid",
      "value": "<mcp-env-var>SESSIONID</mcp-env-var>",
      "in": "cookie",
      "envVarName": "SESSIONID"
    },
    {
      "key": "Authorization",
      "value": "<mcp-env-var>AUTHORIZATION</mcp-env-var>",
      "in": "header",
      "envVarName": "AUTHORIZATION"
    }
  ],
  "paramsMap": {
    "query": {
      "created": "created",
      "created__empty": "created__empty",
      "created__gt": "created__gt",
      "created__gte": "created__gte",
      "created__lt": "created__lt",
      "created__lte": "created__lte",
      "created__n": "created__n",
      "created_by_request": "created_by_request",
      "description": "description",
      "description__empty": "description__empty",
      "description__ic": "description__ic",
      "description__ie": "description__ie",
      "description__iew": "description__iew",
      "description__isw": "description__isw",
      "description__n": "description__n",
      "description__nic": "description__nic",
      "description__nie": "description__nie",
      "description__niew": "description__niew",
      "description__nisw": "description__nisw",
      "id": "id",
      "id__empty": "id__empty",
      "id__gt": "id__gt",
      "id__gte": "id__gte",
      "id__lt": "id__lt",
      "id__lte": "id__lte",
      "id__n": "id__n",
      "interface_id": "interface_id",
      "interface_id__n": "interface_id__n",
      "last_updated": "last_updated",
      "last_updated__empty": "last_updated__empty",
      "last_updated__gt": "last_updated__gt",
      "last_updated__gte": "last_updated__gte",
      "last_updated__lt": "last_updated__lt",
      "last_updated__lte": "last_updated__lte",
      "last_updated__n": "last_updated__n",
      "limit": "limit",
      "modified_by_request": "modified_by_request",
      "offset": "offset",
      "ordering": "ordering",
      "provider": "provider",
      "provider__n": "provider__n",
      "provider_account": "provider_account",
      "provider_account__n": "provider_account__n",
      "provider_account_id": "provider_account_id",
      "provider_account_id__n": "provider_account_id__n",
      "provider_id": "provider_id",
      "provider_id__n": "provider_id__n",
      "provider_network_id": "provider_network_id",
      "provider_network_id__n": "provider_network_id__n",
      "q": "q",
      "role": "role",
      "role__empty": "role__empty",
      "role__ic": "role__ic",
      "role__ie": "role__ie",
      "role__iew": "role__iew",
      "role__isw": "role__isw",
      "role__n": "role__n",
      "role__nic": "role__nic",
      "role__nie": "role__nie",
      "role__niew": "role__niew",
      "role__nisw": "role__nisw",
      "tag": "tag",
      "tag__n": "tag__n",
      "tag_id": "tag_id",
      "tag_id__n": "tag_id__n",
      "updated_by_request": "updated_by_request",
      "virtual_circuit_id": "virtual_circuit_id",
      "virtual_circuit_id__n": "virtual_circuit_id__n"
    }
  },
  inputParamsSchema
}

export default tool