import { z } from "zod"

export const inputParamsSchema = {
  "asset_report_id": z.string().describe("The `asset_report_id` of an asset report associated with the user, as provided by `/asset_report/create`. Providing an `asset_report_id` is optional and can be used to verify the user through a streamlined flow. If provided, the bank linking flow will be skipped.").optional(),
  "access_tokens": z.array(z.string().describe("The access token associated with the Item data is being requested for.")).nullable().describe("An array of access tokens corresponding to Items that a user has previously connected with. Data from these institutions will be cross-referenced with document data received during the Document Income flow to help verify that the uploaded documents are accurate. If the `transactions` product was not initialized for these Items during link, it will be initialized after this Link session.\n\nThis field should only be used with the `payroll` income source type.").optional(),
  "income_source_types": z.array(z.enum(["bank","payroll"]).describe("The types of source income data that users should be able to share")).describe("The types of source income data that users will be permitted to share. Options include `bank` and `payroll`. Currently you can only specify one of these options.").optional(),
  "bank_income": z.record(z.any()).describe("<llm-instruction>This part of the input schema is truncated. If you want to pass the property `bank_income` to the tool, first call the tool `expandSchema` with \"/properties/income_verification/properties/bank_income\" in the list of pointers. This will return the expanded input schema which you can then use in the tool call. You may have to call `expandSchema` multiple times if the schema is nested.</llm-instruction>\n<property-description>Specifies options for initializing Link for use with Bank Income. This field is required if `income_verification` is included in the `products` array and `bank` is specified in `income_source_types`.</property-description>").optional(),
  "payroll_income": z.record(z.any()).describe("<llm-instruction>This part of the input schema is truncated. If you want to pass the property `payroll_income` to the tool, first call the tool `expandSchema` with \"/properties/income_verification/properties/payroll_income\" in the list of pointers. This will return the expanded input schema which you can then use in the tool call. You may have to call `expandSchema` multiple times if the schema is nested.</llm-instruction>\n<property-description>Specifies options for initializing Link for use with Payroll Income (including Document Income). Further customization options for Document Income, such as customizing which document types may be uploaded, are also available via the [Link Customization pane](https://dashboard.plaid.com/link) in the Dashboard. (Requires Production enablement.)</property-description>").optional(),
  "stated_income_sources": z.array(z.object({ "employer": z.string().describe("The employer corresponding to an income source specified by the user").optional(), "category": z.enum(["OTHER","SALARY","UNEMPLOYMENT","CASH","GIG_ECONOMY","RENTAL","CHILD_SUPPORT","MILITARY","RETIREMENT","LONG_TERM_DISABILITY","BANK_INTEREST"]).describe("The income category for a specified income source").optional(), "pay_per_cycle": z.number().describe("The income amount paid per cycle for a specified income source").optional(), "pay_annual": z.number().describe("The income amount paid annually for a specified income source").optional(), "pay_type": z.enum(["UNKNOWN","GROSS","NET"]).describe("The pay type - `GROSS`, `NET`, or `UNKNOWN` for a specified income source").optional(), "pay_frequency": z.enum(["UNKNOWN","WEEKLY","BIWEEKLY","SEMI_MONTHLY","MONTHLY"]).describe("The pay frequency of a specified income source").optional() }).describe("Specifies user stated income sources for the Income product")).describe("A list of user stated income sources").optional()
}